(() => {
  const TE=window.TE5;const D=TE.Data,P=TE.Players,S=TE.Storage,DP=TE.DrillProfile,T=TE.Training,TT=TE.TeamTraining,SC=TE.Scanner,R=TE.Recommendations,F=TE.Formation;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state={page:'dashboard',squadFilter:'ALL',search:'',scan:null,scanAbilities:[],scanDuplicateKey:'',playerKey:'',profileAbilities:[],trainingKey:'',session:null,tacticMode:'balanced'};

  function toast(msg,type='ok'){const el=$('#toast');if(!el)return;el.textContent=msg;el.className='toast show'+(type==='err'?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800);}
  function roleAsset(pos){return `assets/roles/${P.roleGroup(pos)}.webp`;}
  function drillAsset(name='',cat=''){const n=String(name).toLowerCase(),c=String(cat).toLowerCase();if(/one[- ]?on[- ]?one|1v1|attacker|defender/.test(n))return'assets/drills/one-v-one.webp';if(/shoot|finish|free kick|penalt|set[- ]?piece|attack.*master/.test(n))return'assets/drills/shoot.webp';if(/pass|possession|piggy|video analysis|midfield.*master/.test(n))return'assets/drills/pass.webp';if(/head|aerial|cross|corner|press the play|defend.*master/.test(n))return'assets/drills/aerial.webp';if(/sprint|agility|fitness|stretch|warm|condition|shuttle|gym|fast|physical.*master/.test(n)||c.includes('physical'))return'assets/drills/agility.webp';return'assets/drills/dribble.webp';}
  function diffClass(d){return String(d||'').replace(/\s+/g,'');}
  function fmt(n,d=1){return Number.isFinite(Number(n))?Number(n).toFixed(d):'—';}
  function rolesLabel(p){return P.normaliseRoles(p).join(' / ');}

  async function go(page){if(!document.getElementById('page-'+page))page='dashboard';state.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));$$('.nav-btn[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===page));$('#moreBackdrop')?.classList.remove('open');window.scrollTo({top:0,behavior:'instant'});
    if(page==='dashboard')await renderDashboard();else if(page==='squad')await renderSquad();else if(page==='player')await renderPlayerProfile();else if(page==='training')await renderTrainingPicker();else if(page==='my-drills')await renderMyDrills();else if(page==='team-training')await renderTeamTraining();else if(page==='formation')await renderFormationPage();else if(page==='tactics')await renderTactics();else if(page==='playmakers')await renderPlaymakers();}
  document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){go(g.dataset.go);}});
  $('#moreBtn')?.addEventListener('click',()=>$('#moreBackdrop')?.classList.toggle('open'));
  $('#moreBackdrop')?.addEventListener('click',e=>{if(e.target===$('#moreBackdrop'))$('#moreBackdrop').classList.remove('open');});

  // ---------- Dashboard / Squad ----------
  async function renderDashboard(){const players=await P.all(),avg=players.length?players.reduce((a,p)=>a+Number(p.ovr||0),0)/players.length:0,high=players.length?Math.max(...players.map(p=>Number(p.ovr||0))):0;$('#dashboardStats').innerHTML=`<div class="stat lime"><b>${players.length}</b><span>Players</span></div><div class="stat"><b>${players.length?Math.round(avg):'—'}</b><span>Avg OVR</span></div><div class="stat"><b>${players.length?high:'—'}</b><span>Highest</span></div>`;$('#dashboardSquadLabel').textContent=players.length?`${players.length} saved player${players.length===1?'':'s'}`:'Add your first player';}
  function category(pos){if(pos==='GK')return'GK';if(['DL','DC','DR','DML','DMC','DMR'].includes(pos))return'DEF';if(['ML','MC','MR'].includes(pos))return'MID';return'ATT';}
  async function renderSquad(){const players=await P.all(),counts={ALL:players.length,GK:0,DEF:0,MID:0,ATT:0};players.forEach(p=>counts[category(p.position)]++);$('#squadFilters').innerHTML=['ALL','GK','DEF','MID','ATT'].map(x=>`<button class="chip ${state.squadFilter===x?'active':''}" data-squad-filter="${x}">${x}<small>${counts[x]}</small></button>`).join('');const q=state.search.trim().toLowerCase();const filtered=players.filter(p=>(state.squadFilter==='ALL'||category(p.position)===state.squadFilter)&&(!q||String(p.name||'').toLowerCase().includes(q)||rolesLabel(p).toLowerCase().includes(q)));$('#squadList').innerHTML=filtered.length?filtered.map((p,i)=>`<button class="player-row" data-player-key="${esc(p.key)}"><div class="squad-rank">${i+1}</div><img class="player-art" src="${roleAsset(p.position)}"><div class="player-copy"><div class="player-name">${esc(p.name||'Unnamed Player')}</div><div class="player-meta"><span class="pos-tag">${esc(p.position||'?')}</span>${esc(P.normaliseRoles(p).slice(1).join(' · '))}${p.age?` · Age ${esc(p.age)}`:''}</div></div><div class="ovr"><span>OVR</span><b>${esc(p.ovr||'—')}</b></div><div class="row-arrow">›</div></button>`).join(''):`<div class="empty"><b>No players here</b>${players.length?'Change the search or filter.':'Add your first player with Scanner v2.'}</div>`;}
  $('#squadSearch')?.addEventListener('input',e=>{state.search=e.target.value;renderSquad();});$('#clearSearchBtn')?.addEventListener('click',()=>{$('#squadSearch').value='';state.search='';renderSquad();});$('#refreshSquadBtn')?.addEventListener('click',renderSquad);
  document.addEventListener('click',e=>{const f=e.target.closest('[data-squad-filter]');if(f){state.squadFilter=f.dataset.squadFilter;renderSquad();}const row=e.target.closest('[data-player-key]');if(row){state.playerKey=row.dataset.playerKey;go('player');}});

  // ---------- Player profile ----------
  function profileGroups(player){return player.position==='GK'?D.GROUPS_GK:D.GROUPS_OUTFIELD;}
  function weakestKeySkills(player,limit=6){const white=new Set(D.whiteSkillsForRoles(P.normaliseRoles(player)));return Object.entries(player.skills||{}).filter(([name,v])=>white.has(name)&&Number.isFinite(Number(v))).sort((a,b)=>Number(a[1])-Number(b[1])||a[0].localeCompare(b[0])).slice(0,limit);}
  function renderProfileAbilities(){$('#profileAbilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button type="button" class="chip profile-ability-chip ${state.profileAbilities.includes(a)?'active':''}" data-profile-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  function fillRoleSelect(id,value,allowBlank=false,allowed=D.ALL_POSITIONS){$(id).innerHTML=(allowBlank?'<option value="">None</option>':'')+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');}
  async function renderPlayerProfile(){if(!state.playerKey){go('squad');return;}const p=await P.get(state.playerKey);if(!p){toast('Player could not be loaded','err');state.playerKey='';go('squad');return;}const roles=P.normaliseRoles(p),white=new Set(D.whiteSkillsForRoles(roles));$('#profileRoleArt').src=roleAsset(p.position);$('#profileRoleArt').alt=`${P.roleGroup(p.position).toUpperCase()} role artwork`;$('#profileName').textContent=p.name||'Player';$('#profileOvr').textContent=p.ovr||'—';$('#profileEyebrow').textContent=`${p.position} · Player Profile`;$('#profileMeta').innerHTML=`${roles.map(r=>`<span>${esc(r)}</span>`).join('')}${p.age?`<span>Age ${esc(p.age)}</span>`:''}`;const badges=[];if(p.playstyle)badges.push(`<div class="profile-badge"><strong>PLAYSTYLE</strong> · ${esc(p.playstyle)}${D.LEGACY_PLAYSTYLES.includes(p.playstyle)?' · LEGACY':''}</div>`);for(const a of p.specialAbilities||[])badges.push(`<div class="profile-badge gold"><strong>ABILITY</strong> · ${esc(a)}</div>`);if(p.scanner?.version)badges.push(`<div class="profile-badge"><strong>SCAN</strong> · v${esc(p.scanner.version)}${p.scanner.confidence?.overall?' · '+Math.round(p.scanner.confidence.overall*100)+'%':''}</div>`);$('#profileBadges').innerHTML=badges.join('')||'<div class="profile-badge">No playstyle or special ability selected</div>';const weak=weakestKeySkills(p);$('#profileKeySkills').innerHTML=weak.length?weak.map(([name,v])=>`<div class="profile-key"><span>${esc(name)}</span><div class="track"><i style="width:${Math.max(3,Math.min(100,Number(v)/2.5))}%"></i></div><b>${esc(v)}</b></div>`).join(''):'<div class="empty"><b>No skill data</b>Update this player from a scan to populate attributes.</div>';$('#profileSkills').innerHTML=Object.entries(profileGroups(p)).map(([group,names])=>`<div class="skill-group"><h3>${esc(group)}</h3><div class="skill-grid">${names.map(name=>`<div class="skill ${white.has(name)?'white':'grey'}"><span>${esc(name)}</span><b>${esc(p.skills?.[name]??'—')}</b></div>`).join('')}</div></div>`).join('');$('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';$('#profileEditNote').textContent='';}
  async function openProfileEdit(){const p=await P.get(state.playerKey);if(!p)return;const roles=P.normaliseRoles(p);state.profileAbilities=[...(p.specialAbilities||[])].slice(0,2);$('#profileEditName').value=p.name||'';$('#profileEditAge').value=p.age??'';$('#profileEditOvr').value=p.ovr??'';const allowed=p.position==='GK'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK');fillRoleSelect('#profileEditRole1',roles[0]||p.position,false,allowed);fillRoleSelect('#profileEditRole2',roles[1]||'',true,p.position==='GK'?[]:allowed);fillRoleSelect('#profileEditRole3',roles[2]||'',true,p.position==='GK'?[]:allowed);$('#profileEditRole2').disabled=p.position==='GK';$('#profileEditRole3').disabled=p.position==='GK';const legacy=p.playstyle&&!D.PLAYSTYLES.includes(p.playstyle)?`<option value="${esc(p.playstyle)}" selected>${esc(p.playstyle)} (legacy)</option>`:'';$('#profileEditPlaystyle').innerHTML='<option value="">No playstyle</option>'+legacy+D.PLAYSTYLES.map(x=>`<option value="${esc(x)}" ${x===p.playstyle?'selected':''}>${esc(x)}</option>`).join('');renderProfileAbilities();$('#profileEditCard').style.display='block';$('#profileEditBtn').textContent='Editing';$('#profileEditCard').scrollIntoView({behavior:'smooth',block:'start'});}
  $('#profileBackBtn')?.addEventListener('click',()=>go('squad'));$('#profileTrainBtn')?.addEventListener('click',()=>{if(state.playerKey){state.trainingKey=state.playerKey;go('training');}});$('#profileEditBtn')?.addEventListener('click',openProfileEdit);$('#profileCancelEditBtn')?.addEventListener('click',()=>{$('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-ability]');if(!b)return;const a=b.dataset.profileAbility;if(state.profileAbilities.includes(a))state.profileAbilities=state.profileAbilities.filter(x=>x!==a);else if(state.profileAbilities.length<2)state.profileAbilities.push(a);else{toast('Maximum two special abilities','err');return;}renderProfileAbilities();});
  $('#profileSaveBtn')?.addEventListener('click',async()=>{const existing=await P.get(state.playerKey);if(!existing)return;const name=$('#profileEditName').value.trim(),age=Number($('#profileEditAge').value),ovr=Number($('#profileEditOvr').value),primary=$('#profileEditRole1').value;if(!name||!primary){toast('Name and primary role are required','err');return;}if(!Number.isFinite(age)||age<15||age>60){toast('Age must be between 15 and 60','err');return;}if(!Number.isFinite(ovr)||ovr<1||ovr>520){toast('OVR must be between 1 and 520','err');return;}const duplicate=(await P.all()).find(x=>x.key!==state.playerKey&&String(x.name||'').trim().toLowerCase()===name.toLowerCase());if(duplicate){toast('Another player already uses that name','err');return;}const roles=[primary,$('#profileEditRole2').value,$('#profileEditRole3').value].filter((r,i,a)=>r&&a.indexOf(r)===i).slice(0,3);await P.save({...existing,name,age,ovr,position:primary,roles,playstyle:$('#profileEditPlaystyle').value,specialAbilities:[...state.profileAbilities]},state.playerKey);toast('Player updated');await renderDashboard();await renderPlayerProfile();});
  $('#profileDeleteBtn')?.addEventListener('click',async()=>{const b=$('#profileDeleteBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to delete';$('#profileEditNote').textContent='This permanently removes the player and their saved training session.';setTimeout(()=>{delete b.dataset.armed;b.textContent='Delete Player';},3500);return;}const p=await P.get(state.playerKey);await P.remove(state.playerKey);state.playerKey='';state.trainingKey='';delete b.dataset.armed;b.textContent='Delete Player';toast(`${p?.name||'Player'} deleted`);await renderDashboard();go('squad');});

  // ---------- Scanner v2 ----------
  function resetScanner(){state.scan=null;state.scanAbilities=[];state.scanDuplicateKey='';$('#scanFile').value='';$('#scanWindow').className='scan-window';$('#scanPreview').removeAttribute('src');$('#scanReview').style.display='none';$('#scanProgressBar').style.width='0%';$('#scanProgressText').textContent='Waiting for screenshot';$('#scanPercent').textContent='0%';$('#scanSaveNote').textContent='';}
  $('#rescanBtn')?.addEventListener('click',resetScanner);
  function progress(p){const pct=Math.round((p.progress||0)*100);$('#scanProgressBar').style.width=pct+'%';$('#scanProgressText').textContent=p.label||'Scanning';$('#scanPercent').textContent=pct+'%';}
  function confidenceBadge(v){const n=Math.round((v||0)*100);return `<span class="chip active">${n}% confidence</span>`;}
  function renderAbilityPicker(){$('#abilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button class="chip ${state.scanAbilities.includes(a)?'active':''}" data-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-ability]');if(!b)return;const a=b.dataset.ability;if(state.scanAbilities.includes(a))state.scanAbilities=state.scanAbilities.filter(x=>x!==a);else if(state.scanAbilities.length<2)state.scanAbilities.push(a);else{toast('Maximum two special abilities','err');return;}renderAbilityPicker();});
  function renderScanSkills(scan){const groups=scan.layout==='gk'?D.GROUPS_GK:D.GROUPS_OUTFIELD;$('#scanSkills').innerHTML=Object.entries(groups).map(([g,names])=>`<div class="skill-group"><h3>${esc(g)}</h3><div class="skill-grid">${names.map(s=>`<div class="skill"><span>${esc(s)}</span><b>${esc(scan.skills[s]??'—')}</b></div>`).join('')}</div></div>`).join('');}
  function populateScanReview(scan){state.scan=scan;state.scanDuplicateKey='';$('#scanReview').style.display='block';$('#scanConfidence').innerHTML=confidenceBadge(scan.confidence.overall);$('#scanChecks').innerHTML=Object.entries(scan.checks||{}).map(([name,c])=>`<div class="verify ${c.ok?'ok':'warn'}"><strong>${c.ok?'✓':'!'} ${esc(name)}</strong><span>${c.error==null?'No aggregate available':`difference ${Number(c.error).toFixed(1)}`}</span></div>`).join('');$('#scanName').value=scan.name||'';$('#scanAge').value=scan.age??'';$('#scanOvr').value=scan.ovr??'';const allowed=scan.layout==='gk'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK');const fill=(id,value,label)=>{$(id).innerHTML=`<option value="">${label}</option>`+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');};fill('#scanRole',scan.roles?.[0]||scan.position,'Choose role');fill('#scanRole2',scan.roles?.[1]||'','None');fill('#scanRole3',scan.roles?.[2]||'','None');$('#scanRole2').disabled=scan.layout==='gk';$('#scanRole3').disabled=scan.layout==='gk';$('#detectedRoles').innerHTML=(scan.roles||[]).map((r,i)=>`<span class="chip ${i===0?'active':''}">${esc(r)}${i===0?' · primary':''}</span>`).join('')||( '<span class="mini-note">Role needs review.</span>');$('#scanPlaystyle').innerHTML='<option value="">No playstyle</option>'+D.PLAYSTYLES.map(x=>`<option>${esc(x)}</option>`).join('');renderAbilityPicker();renderScanSkills(scan);$('#scanSaveNote').textContent=(scan.repairNotes||[]).join(' · ')||'Numbers were parsed locally and cross-checked against the visible group totals.';}
  $('#scanFile')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const url=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});$('#scanPreview').src=url;$('#scanWindow').classList.add('has-image','scanning');$('#scanReview').style.display='none';progress({progress:.02,label:'Preparing scanner'});try{const scan=await SC.scan(url,progress);$('#scanWindow').classList.remove('scanning');populateScanReview(scan);toast(`Scan complete · ${Math.round(scan.confidence.overall*100)}% confidence`);}catch(err){$('#scanWindow').classList.remove('scanning');$('#scanProgressText').textContent='Scan failed';toast(err.message||'Scanner failed','err');console.error(err);}});
  function scanFormData(){const name=$('#scanName').value.trim(),age=Number($('#scanAge').value),ovr=Number($('#scanOvr').value),position=$('#scanRole').value,roles=[position,$('#scanRole2').value,$('#scanRole3').value].filter((r,i,a)=>r&&a.indexOf(r)===i).slice(0,3);return{name,age,ovr,position,roles};}
  function validateScanForm(x){if(!state.scan)return'No scan loaded';if(!x.name||!x.position)return'Check the name and primary role before saving';if(!Number.isFinite(x.age)||x.age<15||x.age>60)return'Check the player age before saving';if(!Number.isFinite(x.ovr)||x.ovr<1||x.ovr>520)return'Check the OVR before saving';if(state.scan.layout==='gk'&&x.roles.some(r=>r!=='GK'))return'GK scans can only be saved as GK';if(state.scan.layout!=='gk'&&x.roles.includes('GK'))return'Outfield scans cannot be saved as GK';return'';}
  async function saveScanToKey(key=null){const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return false;}const existing=key?await P.get(key):null;await P.save({...existing,...x,skills:state.scan.skills,playstyle:$('#scanPlaystyle').value||existing?.playstyle||'',specialAbilities:state.scanAbilities.length?[...state.scanAbilities]:(existing?.specialAbilities||[]),scanner:{version:2,confidence:state.scan.confidence,checks:state.scan.checks}},key);return true;}
  $('#saveScannedPlayer')?.addEventListener('click',async()=>{const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return;}const duplicate=(await P.all()).find(p=>String(p.name||'').trim().toLowerCase()===x.name.toLowerCase());if(duplicate){state.scanDuplicateKey=duplicate.key;$('#scanSaveNote').innerHTML=`<b>${esc(x.name)}</b> already exists. <button class="inline-action-btn" id="updateExistingScanBtn">Update existing player</button>`;toast('Existing player found','err');return;}try{if(await saveScanToKey()){toast(`${x.name} saved to My Squad`);resetScanner();await renderDashboard();go('squad');}}catch(e){toast(e.message||'Save failed','err');}});
  document.addEventListener('click',async e=>{if(!e.target.closest('#updateExistingScanBtn'))return;if(!state.scanDuplicateKey)return;try{const name=$('#scanName').value.trim();if(await saveScanToKey(state.scanDuplicateKey)){toast(`${name} updated from scan`);state.playerKey=state.scanDuplicateKey;resetScanner();await renderDashboard();go('player');}}catch(err){toast(err.message||'Update failed','err');}});

  // ---------- Drill profile ----------
  async function renderMyDrills(){const {normal,master}=await DP.ensure();$('#normalDrillConfig').innerHTML=D.NORMAL_DRILLS.map(d=>{const s=normal.drills[d.drillId]||{unlocked:false,level:0};return `<div class="drill-config-row" data-drill-id="${esc(d.drillId)}"><div class="drill-config-main"><img src="${drillAsset(d.name,d.cat)}"><div><b>${esc(d.name)}</b><span>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</span></div></div><label class="unlock-control"><input type="checkbox" data-normal-unlock="${esc(d.drillId)}" ${s.unlocked?'checked':''}><i></i></label><select class="level-select" data-normal-level="${esc(d.drillId)}" ${s.unlocked?'':'disabled'}><option value="1" ${Number(s.level)===1?'selected':''}>Semi-pro +10%</option><option value="2" ${Number(s.level)===2?'selected':''}>Pro +20%</option><option value="3" ${Number(s.level)===3?'selected':''}>World-class +30%</option></select></div>`;}).join('');$('#masterStockConfig').innerHTML=D.MASTER_CAMPUS_DRILLS.map(d=>`<div class="master-card"><img src="${drillAsset(d.name,d.cat)}"><div class="master-card-copy"><span class="master-badge">MASTER +${esc(d.additionalTrainingEffectPercent)}%</span><b>${esc(d.name)}</b><small>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small><small>${esc(d.skills.join(' · '))}</small></div><label><span>CARDS OWNED</span><input type="number" min="0" step="1" inputmode="numeric" data-master-stock="${esc(d.drillId)}" value="${Math.max(0,Number(master.stock[d.drillId]||0))}"></label></div>`).join('');}
  document.addEventListener('change',async e=>{if(e.target.matches('[data-normal-unlock]')){const id=e.target.dataset.normalUnlock,row=e.target.closest('.drill-config-row'),sel=row.querySelector('[data-normal-level]'),unlocked=e.target.checked;sel.disabled=!unlocked;const level=unlocked?(Number(sel.value)||1):(Number(sel.value)||0);await DP.setNormal(id,{unlocked,level});clearTrainingSessionView();toast(`${row.querySelector('b').textContent} ${unlocked?'enabled':'locked'} · saved sessions cleared`);await updateTrainingIntel();}else if(e.target.matches('[data-normal-level]')){const id=e.target.dataset.normalLevel,row=e.target.closest('.drill-config-row'),unlock=row.querySelector('[data-normal-unlock]');await DP.setNormal(id,{unlocked:unlock.checked,level:Number(e.target.value)});clearTrainingSessionView();toast('Drill level saved · sessions cleared');}else if(e.target.matches('[data-master-stock]')){const q=await DP.setMasterStock(e.target.dataset.masterStock,e.target.value);e.target.value=q;clearTrainingSessionView();toast('Master stock saved · sessions cleared');await updateTrainingIntel();}});
  $('#resetDrillsBtn')?.addEventListener('click',async()=>{const b=$('#resetDrillsBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again';setTimeout(()=>{delete b.dataset.armed;b.textContent='Reset snapshot';},3000);return;}await DP.resetToCapturedSnapshot();clearTrainingSessionView();delete b.dataset.armed;b.textContent='Reset snapshot';toast('Captured drill snapshot restored · sessions cleared');await renderMyDrills();await updateTrainingIntel();});

  // ---------- Individual training ----------
  function clearTrainingSessionView(message=''){state.session=null;if($('#trainingResults'))$('#trainingResults').style.display='none';if(message&&$('#trainingStatus'))$('#trainingStatus').textContent=message;}
  function trainingSourceSnapshot(player,normal,master){return {playerUpdatedAt:String(player?.updatedAt||''),normalUpdatedAt:String(normal?.updatedAt||''),masterUpdatedAt:String(master?.updatedAt||'')};}
  function sameTrainingSource(a,b){return !!a&&a.playerUpdatedAt===b.playerUpdatedAt&&a.normalUpdatedAt===b.normalUpdatedAt&&a.masterUpdatedAt===b.masterUpdatedAt;}
  async function updateTrainingIntel(){const {normal,master}=await DP.ensure();const unlocked=Object.values(normal.drills).filter(x=>x.unlocked).length,totalMaster=Object.values(master.stock).reduce((a,b)=>a+Math.max(0,Number(b)||0),0);if($('#intelNormalCount'))$('#intelNormalCount').textContent=unlocked;if($('#intelMasterCount'))$('#intelMasterCount').textContent=totalMaster;}
  async function renderTrainingPicker(){await updateTrainingIntel();const players=await P.all();$('#trainingPlayer').innerHTML='<option value="">Select a player</option>'+players.map(p=>`<option value="${esc(p.key)}" ${p.key===state.trainingKey?'selected':''}>${esc(p.name)} · ${esc(rolesLabel(p))} · ${esc(p.ovr||'—')} OVR</option>`).join('');clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey&&!players.some(p=>p.key===state.trainingKey)){state.trainingKey='';return;}if(state.trainingKey)await restoreTrainingSession();}
  async function persistTraining(){if(!state.trainingKey||!state.session)return;await S.set(`training:session:${state.trainingKey}`,JSON.stringify({gameDataVersion:D.GAME_DATA_VERSION,session:state.session,savedAt:new Date().toISOString()}));}
  async function restoreTrainingSession(){clearTrainingSessionView();const key=`training:session:${state.trainingKey}`,raw=await S.get(key);if(!raw)return false;try{const x=JSON.parse(raw);if(x.gameDataVersion!==D.GAME_DATA_VERSION||x.session?.meta?.model!==T.MODEL_VERSION){await S.del(key);$('#trainingStatus').textContent='A previous recommendation used older training data. Build a fresh session.';return false;}const player=await P.get(state.trainingKey);if(!player){await S.del(key);return false;}const {normal,master}=await DP.ensure(),current=trainingSourceSnapshot(player,normal,master);if(!sameTrainingSource(x.session?.sourceSnapshot,current)){await S.del(key);$('#trainingStatus').textContent='Saved recommendation expired because the player or My Drills changed. Build a fresh session.';return false;}state.session=x.session;renderSession();$('#trainingStatus').textContent=state.session.completed?'Completed session restored.':'Saved recommendation restored.';return true;}catch(_){await S.del(key);$('#trainingStatus').textContent='Saved recommendation could not be restored. Build a fresh session.';return false;}}
  $('#trainingPlayer')?.addEventListener('change',async e=>{state.trainingKey=e.target.value;clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey)await restoreTrainingSession();});
  async function buildTraining(){if(!state.trainingKey){toast('Select a player first','err');return;}const player=await P.get(state.trainingKey);if(!player){toast('Player could not be loaded','err');return;}const {normal,master}=await DP.ensure();const result=T.buildIndividualSession({player,normalProfile:normal,masterStock:master,slots:6});if(result.error==='missing-white-attributes'){$('#trainingStatus').textContent=`Cannot optimise reliably: ${result.missingAttributes.join(', ')} are missing from this player profile. Rescan or update the player first.`;$('#trainingResults').style.display='none';toast('Player profile is incomplete','err');return;}state.session={...result,playerKey:state.trainingKey,playerName:player.name,completed:false,stockDeducted:false,createdAt:new Date().toISOString(),sourceSnapshot:trainingSourceSnapshot(player,normal,master)};renderSession();await persistTraining();$('#trainingStatus').textContent=result.drills.length===6?`Built 6 slots from ${result.meta.normalCandidateCount} unlocked normal drills and ${result.meta.masterCandidateCount} owned Master drill types. Ranking follows the build-30527 contract; no exact gain is predicted.`:`Only ${result.drills.length}/6 legal slots could be built from your saved drill library.`;}
  $('#buildSessionBtn')?.addEventListener('click',buildTraining);$('#rebuildBtn')?.addEventListener('click',buildTraining);
  function masterProjectionHtml(r){const usage=Object.entries(r.meta?.masterUsage||{}).filter(([,n])=>Number(n)>0);if(!usage.length)return'';return `<div class="master-projection wide"><span>Master stock ${r.completed?'remaining':'projection'}</span><div>${usage.map(([id,n])=>{const name=D.MASTER_CAMPUS_DRILLS.find(d=>d.drillId===id)?.name||id,used=Number(n)||0,remaining=Number(r.meta?.remainingMasterStock?.[id]??0),owned=remaining+used;return `<section><b>${esc(name)}</b><small>${owned} owned at build</small><strong>${used} used</strong><em>${remaining} ${r.completed?'remaining now':'projected remaining'}</em></section>`;}).join('')}</div></div>`;}
  function renderSession(){const r=state.session;if(!r)return;$('#trainingResults').style.display='block';const priority=(r.meta?.priorityAttributes||[]).slice(0,5);$('#priorityAttributes').innerHTML=priority.map((x,i)=>`<div class="priority-pill"><span>${i+1}</span><b>${esc(x.attribute)}</b><small>${esc(x.value)}</small></div>`).join('');const masterSeen={};$('#sessionList').innerHTML=r.drills?.length?r.drills.map((d,i)=>{let stockLine='';if(d.isMaster){masterSeen[d.drillId]=(masterSeen[d.drillId]||0)+1;const used=Number(r.meta?.masterUsage?.[d.drillId]||0),remaining=Number(r.meta?.remainingMasterStock?.[d.drillId]??0),owned=remaining+used;stockLine=`<div class="master-use-line">Card ${masterSeen[d.drillId]}/${used} · ${owned} owned · ${remaining} ${r.completed?'remaining':'left after this session'}</div>`;}return `<div class="drill-row ${d.isMaster?'master':''}"><div class="slot-no">${String(i+1).padStart(2,'0')}</div><img src="${drillAsset(d.name,d.cat)}"><div class="drill-copy"><div class="drill-title-line"><b>${esc(d.name)}</b>${d.isMaster?'<span class="master-badge small">MASTER</span>':''}</div><small>${d.isMaster?`+${d.effectPct}% Training Effect`:`${esc(d.levelName)} · +${d.effectPct}%`} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small>${stockLine}<div class="target-line"><span>Targets</span>${d.targetedWhiteAttributes.map(a=>`<i>${esc(a)}</i>`).join('')}${d.greyApplicableAttributes.length?`<em>Grey: ${esc(d.greyApplicableAttributes.join(', '))}</em>`:''}</div></div><span class="diff ${diffClass(d.diff)}">${esc(d.diff)}</span></div>`;}).join(''):'<div class="empty"><b>No legal session</b>Check My Drills and the selected player profile.</div>';$('#sessionSummary').innerHTML=`<div><span>Total condition</span><b>${fmt(r.meta?.totalCondition,2)}%</b></div><div><span>Total XP</span><b>${fmt(r.meta?.totalXp,0)}</b></div><div><span>Useful Training Score</span><b>${fmt(r.meta?.totalUsefulScore,1)}</b></div>${masterProjectionHtml(r)}<p>This score ranks useful development into current white/key needs. It is not a predicted +X% attribute gain.</p>`;$('#completeSessionBtn').disabled=!!r.completed;$('#completeSessionBtn').textContent=r.completed?'Session Completed ✓':'Mark Session Completed';$('#sessionCompleteNote').textContent=r.completed?(r.stockDeducted?'Master card stock has been deducted once; the remaining figures above are current.':'Completed. No Master cards were used.'):'Master figures above are projected only. Stock changes when you complete the whole session.';}
  $('#completeSessionBtn')?.addEventListener('click',async()=>{if(!state.session||state.session.completed)return;const usage=state.session.meta?.masterUsage||{};if(Object.values(usage).some(n=>Number(n)>0)&&!state.session.stockDeducted){const updatedMaster=await DP.deductMasterUsage(usage);state.session.stockDeducted=true;if(state.session.sourceSnapshot)state.session.sourceSnapshot.masterUpdatedAt=String(updatedMaster.updatedAt||'');}state.session.completed=true;state.session.completedAt=new Date().toISOString();await persistTraining();renderSession();await updateTrainingIntel();toast('Training session completed');});

  // ---------- Team normal-drill group planner ----------
  async function renderTeamTraining(){const normal=await DP.getNormal();$('#teamTrainingCards').innerHTML=Object.entries(D.TEAM_GROUPS).map(([key,g])=>{const r=TT.buildTeamSession(key,{normalProfile:normal});return `<div class="team-card"><div class="team-card-top"><img src="assets/icons/team.svg"><div><span>6 NORMAL DRILLS</span><b>${esc(g.title)}</b></div></div><div class="team-mini-list">${r.drills.map(d=>`<div><b>${esc(d.name)}</b><span>${esc(d.diff)} · +${d.effectPct}%</span></div>`).join('')}</div><small>Separate from Top Eleven's TeamPlayTrainingDrill protocol.</small></div>`;}).join('');}

  // ---------- Formation ----------
  function clearPitch(){$('#formationPitch').querySelectorAll('.pitch-player').forEach(e=>e.remove());}
  function benchCard(p){return `<button class="bench-card" data-player-key="${esc(p.key)}"><b>${esc(p.name||'Player')}</b><span>${esc(rolesLabel(p))} · OVR ${esc(p.ovr||'—')}</span></button>`;}
  function showFormationEmpty(players){const count=players.length,needed=Math.max(0,11-count),empty=$('#formationEmpty');clearPitch();$('#formationName').textContent=count?'Squad incomplete':'No squad yet';$('#formationSummary').textContent=count?`Add ${needed} more player${needed===1?'':'s'} to build a full XI.`:'Add players to unlock automatic formation selection.';$('#formationBenchTitle').textContent=count?'Available players':'Squad';$('#formationBench').innerHTML=count?players.map(p=>benchCard(p)).join(''):'<div class="empty formation-list-empty"><b>No players added</b>Use Add Player to scan your first profile.</div>';$('#teamSelectBtn').disabled=true;if(empty){empty.style.display='grid';empty.innerHTML=`<img src="assets/icons/squad.svg" alt=""><b>${count}/11 PLAYERS</b><span>${count?`${needed} more required for Team Select.`:'Build your squad before choosing a formation.'}</span><button class="btn primary compact" data-go="add-player">+ Add Player</button>`;}}
  async function renderFormationPage(){const players=await P.all();if(players.length>=11)renderFormationResult(F.choose(players));else showFormationEmpty(players);}
  function renderFormationResult(result){if(result.error){showFormationEmpty([]);$('#formationSummary').textContent=result.error;return;}$('#formationName').textContent=result.formation.name;$('#formationSummary').textContent=`${result.exact}/11 natural-role selections · role fit first, then OVR and relevant saved attributes.`;$('#teamSelectBtn').disabled=false;$('#formationBenchTitle').textContent='Bench';const empty=$('#formationEmpty');if(empty)empty.style.display='none';clearPitch();result.chosen.forEach(({player,slot,xy})=>{const el=document.createElement('button');el.className='pitch-player';el.style.left=xy[0]+'%';el.style.top=xy[1]+'%';el.dataset.playerKey=player.key;const last=String(player.name||'Player').trim().split(/\s+/).pop();el.innerHTML=`<span class="pitch-player-ring"><img src="${roleAsset(player.position)}"></span><b>${esc(last)}</b><small>${esc(player.position)} · ${esc(player.ovr||'—')}</small>`;$('#formationPitch').appendChild(el);});$('#formationBench').innerHTML=result.remaining.length?result.remaining.slice(0,10).map(benchCard).join(''):'<div class="empty formation-list-empty"><b>No substitutes</b>Every saved player is in the selected XI.</div>';}
  $('#teamSelectBtn')?.addEventListener('click',async()=>{const players=await P.all(),r=F.choose(players);if(r.error){showFormationEmpty(players);toast(r.error,'err');return;}renderFormationResult(r);toast(`${r.formation.name} selected`);});

  // ---------- Tactics / Playmakers ----------
  async function renderTactics(){const players=await P.all();$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.tacticMode));if(!players.length){$('#mentorStrip').innerHTML='<div class="empty"><b>Add players first</b>Mentor and tactic recommendations need squad data.</div>';$('#tacticPlan').innerHTML='';return;}const plan=R.recommendTactics(players,state.tacticMode);$('#mentorStrip').innerHTML=R.MENTORS.map(m=>`<div class="mentor ${m.name===plan.mentor.name?'active':''}"><img src="assets/mentors/${m.asset}"><div class="mentor-copy"><b>${esc(m.name)}</b><span>${esc(m.title)}</span></div></div>`).join('');const items={'Shooting':plan.shoot,'Passing':plan.pass,'Focus':plan.focus,'Crossing':plan.cross,'Possession Lost':plan.lost,'Possession Won':plan.won,'Mentality':plan.mentality,'Marking':plan.mark,'Pressing':plan.press,'Back Line':plan.back,'Tackling':plan.tackle};$('#tacticPlan').innerHTML=Object.entries(items).map(([k,v])=>`<div class="plan-item"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');}
  $$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.tacticMode=b.dataset.mode;renderTactics();}));
  function rankRow(x,i,label=''){const p=x.player;return `<div class="rank-card"><div class="rank-num">${label||i+1}</div><img src="${roleAsset(p.position)}"><div><div class="rank-name">${esc(p.name)}</div><div class="rank-meta">${esc(rolesLabel(p))} · ${esc(p.ovr||'—')} OVR</div></div><div class="rank-score">${Math.round(x.score)}</div></div>`;}
  async function renderPlaymakers(){const players=await P.all();if(!players.length){$('#penaltyRank').innerHTML='<div class="empty"><b>No squad yet</b>Add players to rank specialists.</div>';$('#specialistRank').innerHTML='';return;}const r=R.rankPlaymakers(players);$('#penaltyRank').innerHTML=r.penalties.map((x,i)=>rankRow(x,i)).join('');const specs=[['C',r.corner],['FK',r.freeKick],['★',r.captain]].filter(x=>x[1]);$('#specialistRank').innerHTML=specs.map(x=>rankRow(x[1],0,x[0])).join('');}

  // ---------- Settings / startup ----------
  $('#clearDataBtn')?.addEventListener('click',async()=>{const b=$('#clearDataBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to confirm';setTimeout(()=>{delete b.dataset.armed;b.textContent='Clear all squad data';},3500);return;}for(const k of await S.list('player:'))await S.del(k);for(const k of await S.list('training:session:'))await S.del(k);delete b.dataset.armed;b.textContent='Clear all squad data';toast('Squad data cleared');renderDashboard();});
  async function init(){await DP.ensure();resetScanner();await renderDashboard();await updateTrainingIntel();}
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.warn));
  init().catch(err=>{console.error(err);toast('App initialisation failed','err');});
})();
