(() => {
  const TE=window.TE5;const D=TE.Data,P=TE.Players,S=TE.Storage,DP=TE.DrillProfile,T=TE.Training,TT=TE.TeamTraining,SC=TE.Scanner,R=TE.Recommendations,F=TE.Formation,TP=TE.TeamPlan,TAC=TE.Tactics,M=TE.Mentor,B=TE.BibleData;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state={page:'dashboard',squadFilter:'ALL',search:'',squadRole:'',squadAgeMin:'',squadAgeMax:'',squadOvrMin:'',squadOvrMax:'',squadPlaystyle:'',squadAvailability:'',scan:null,scanAbilities:[],scanRelatedRoles:[],scanDuplicateKey:'',scanPreservedRoles:[],scanQueue:[],scanQueueReviewIndex:-1,scanQueueScanning:false,scanQueueSeq:0,scanManualVerified:false,playerKey:'',profileAbilities:[],profileRelatedRoles:[],profilePreservedRoles:[],trainingKey:'',trainingTab:'individual',session:null,approach:'balanced',drainLimit:'Medium'};
  const UI_STATE_KEY='te:ui:state:v5213',SCAN_QUEUE_META_KEY='scanner:queue:v1',QUEUE_DB_NAME='te-scanner-queue-v1',QUEUE_STORE='images';
  const scanControllers=new Map();
  let drawerOpen=false,deleteTarget=null,pendingDrawerNavigation=null,openSquadSwipeKey='',suppressSquadClickUntil=0;

  function toast(msg,type='ok'){const el=$('#toast');if(!el)return;el.textContent=msg;el.className='toast show'+(type==='err'?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800);}
  function roleAsset(pos){return `assets/roles/${P.roleGroup(pos)}.webp`;}
  function drillAsset(name='',cat=''){const n=String(name).toLowerCase(),c=String(cat).toLowerCase();if(/one[- ]?on[- ]?one|1v1|attacker|defender/.test(n))return'assets/drills/one-v-one.webp';if(/shoot|finish|free kick|penalt|set[- ]?piece|attack.*master/.test(n))return'assets/drills/shoot.webp';if(/pass|possession|piggy|video analysis|midfield.*master/.test(n))return'assets/drills/pass.webp';if(/head|aerial|cross|corner|press the play|defend.*master/.test(n))return'assets/drills/aerial.webp';if(/sprint|agility|fitness|stretch|warm|condition|shuttle|gym|fast|physical.*master/.test(n)||c.includes('physical'))return'assets/drills/agility.webp';return'assets/drills/dribble.webp';}
  function diffClass(d){return String(d||'').replace(/\s+/g,'');}
  function fmt(n,d=1){return Number.isFinite(Number(n))?Number(n).toFixed(d):'—';}
  function rolesLabel(p){return P.normaliseRoles(p).join(' / ');}

  function uiSnapshot(){return{page:state.page,squadFilter:state.squadFilter,search:state.search,squadRole:state.squadRole,squadAgeMin:state.squadAgeMin,squadAgeMax:state.squadAgeMax,squadOvrMin:state.squadOvrMin,squadOvrMax:state.squadOvrMax,squadPlaystyle:state.squadPlaystyle,squadAvailability:state.squadAvailability,playerKey:state.playerKey,trainingKey:state.trainingKey,trainingTab:state.trainingTab,approach:state.approach,drainLimit:state.drainLimit};}
  function persistUiState(){try{sessionStorage.setItem(UI_STATE_KEY,JSON.stringify(uiSnapshot()));}catch(_){/* refresh-state persistence is best effort */}}
  function restoreUiState(){try{const saved=JSON.parse(sessionStorage.getItem(UI_STATE_KEY)||'null');if(saved&&typeof saved==='object')for(const k of Object.keys(uiSnapshot()))if(saved[k]!=null)state[k]=saved[k];}catch(_){/* ignore corrupt UI state */}}
  function routeState(page=state.page,extra={}){return{teTopEleven:true,page,playerKey:state.playerKey||'',trainingKey:state.trainingKey||'',trainingTab:state.trainingTab||'individual',...extra};}
  function sameRoute(a,b){return!!(a&&b&&a.teTopEleven&&b.teTopEleven&&a.page===b.page&&String(a.playerKey||'')===String(b.playerKey||'')&&String(a.trainingKey||'')===String(b.trainingKey||'')&&String(a.trainingTab||'')===String(b.trainingTab||'')&&!a.overlay&&!b.overlay);}
  async function applyPage(page,{scroll=true}={}){if(!document.getElementById('page-'+page))page='dashboard';state.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));$$('.nav-btn[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===page));if(scroll)window.scrollTo({top:0,behavior:'instant'});persistUiState();updateDrawerActive();
    if(page==='dashboard')await renderDashboard();else if(page==='squad')await renderSquad();else if(page==='player')await renderPlayerProfile();else if(page==='training')await renderTrainingPicker();else if(page==='my-drills')await renderMyDrills();else if(page==='team-plan')await renderTeamPlan();else if(page==='playmakers')await renderPlaymakers();}
  async function go(page,{historyMode='push',scroll=true}={}){if(!document.getElementById('page-'+page))page='dashboard';const next=routeState(page),current=history.state;if(historyMode==='replace')history.replaceState(next,'');else if(historyMode==='push'&&!sameRoute(current,next))history.pushState(next,'');await applyPage(page,{scroll});}
  function hideDrawer(){drawerOpen=false;$('#moreBackdrop')?.classList.remove('open');document.body.classList.remove('drawer-open');}
  function closeDrawer(){if(!drawerOpen)return;if(history.state?.overlay==='drawer')history.back();else hideDrawer();}
  function drawerItems(){const pages=[...document.querySelectorAll('.page[data-nav-label]')],items=[];for(const page of pages){const id=page.dataset.page;if(id==='training'){const tabs=[...page.querySelectorAll('[data-training-tab]')];for(const tab of tabs)items.push({page:id,tab:tab.dataset.trainingTab,label:`${tab.textContent.trim()} Training`,icon:tab.querySelector('img')?.getAttribute('src')||'assets/icons/training.svg'});}else items.push({page:id,label:page.dataset.navLabel,icon:page.dataset.navIcon||'assets/icons/more.svg'});}return items;}
  function buildDrawer(){const el=$('#drawerNav');if(!el)return;el.innerHTML=drawerItems().map(x=>`<button class="drawer-item" data-drawer-page="${esc(x.page)}" ${x.tab?`data-drawer-tab="${esc(x.tab)}"`:''}><img src="${esc(x.icon)}"><span>${esc(x.label)}</span></button>`).join('');updateDrawerActive();}
  function updateDrawerActive(){$$('#drawerNav .drawer-item').forEach(b=>b.classList.toggle('active',b.dataset.drawerPage===state.page&&(!b.dataset.drawerTab||b.dataset.drawerTab===state.trainingTab)));}
  function openDrawer(){closeOpenSquadSwipe();buildDrawer();drawerOpen=true;$('#moreBackdrop')?.classList.add('open');document.body.classList.add('drawer-open');if(history.state?.overlay!=='drawer')history.pushState(routeState(state.page,{overlay:'drawer'}),'');}
  function hideDeleteDialog(){deleteTarget=null;$('#confirmDialogBackdrop')?.classList.remove('open');}
  function closeDeleteDialog(){if(!deleteTarget)return;if(history.state?.overlay==='delete')history.back();else hideDeleteDialog();}
  function openDeleteDialog(key,name){deleteTarget={key,name};$('#confirmDialogTitle').textContent=`Delete ${name||'player'}?`;$('#confirmDialogCopy').textContent='Are you sure you want to permanently remove this player from your squad?';$('#confirmDialogBackdrop')?.classList.add('open');if(history.state?.overlay!=='delete')history.pushState(routeState(state.page,{overlay:'delete'}),'');}
  window.addEventListener('popstate',async e=>{hideDrawer();hideDeleteDialog();closeOpenSquadSwipe();const r=e.state;if(r?.teTopEleven){if('playerKey'in r)state.playerKey=r.playerKey||'';if('trainingKey'in r)state.trainingKey=r.trainingKey||'';if(r.trainingTab)state.trainingTab=r.trainingTab;await applyPage(r.page||'dashboard',{scroll:false});if(state.page==='training')setTrainingTab(state.trainingTab);}const pending=pendingDrawerNavigation;pendingDrawerNavigation=null;if(pending){if(pending.tab)state.trainingTab=pending.tab;await go(pending.page);if(pending.page==='training'&&pending.tab)setTrainingTab(pending.tab);}});
  document.addEventListener('click',e=>{const d=e.target.closest('[data-drawer-page]');if(d){pendingDrawerNavigation={page:d.dataset.drawerPage,tab:d.dataset.drawerTab||''};closeDrawer();return;}const g=e.target.closest('[data-go]');if(g&&!e.target.closest('#drawerNav')){go(g.dataset.go);}});
  $('#moreBtn')?.addEventListener('click',()=>drawerOpen?closeDrawer():openDrawer());
  $('#moreBackdrop')?.addEventListener('click',e=>{if(e.target===$('#moreBackdrop'))closeDrawer();});
  $('#drawerCloseBtn')?.addEventListener('click',closeDrawer);
  const drawerSwipe={active:false,startX:0,startY:0,lastX:0,pointerId:null,mode:''};
  $('#navDrawer')?.addEventListener('pointerdown',e=>{Object.assign(drawerSwipe,{active:true,startX:e.clientX,startY:e.clientY,lastX:e.clientX,pointerId:e.pointerId,mode:''});});
  $('#navDrawer')?.addEventListener('pointermove',e=>{if(!drawerSwipe.active||e.pointerId!==drawerSwipe.pointerId)return;const dx=e.clientX-drawerSwipe.startX,dy=e.clientY-drawerSwipe.startY;drawerSwipe.lastX=e.clientX;if(!drawerSwipe.mode){if(Math.abs(dy)>10&&Math.abs(dy)>Math.abs(dx)){drawerSwipe.mode='vertical';return;}if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.2)drawerSwipe.mode='horizontal';}if(drawerSwipe.mode==='horizontal'&&dx<0){e.preventDefault();$('#navDrawer').style.transform=`translateX(${Math.max(-110,dx)}px)`;}});
  function finishDrawerSwipe(e){if(!drawerSwipe.active||(e?.pointerId!=null&&e.pointerId!==drawerSwipe.pointerId))return;const dx=drawerSwipe.lastX-drawerSwipe.startX;drawerSwipe.active=false;$('#navDrawer')?.style.removeProperty('transform');if(drawerSwipe.mode==='horizontal'&&dx<-65)closeDrawer();}
  $('#navDrawer')?.addEventListener('pointerup',finishDrawerSwipe);$('#navDrawer')?.addEventListener('pointercancel',finishDrawerSwipe);
  $('#confirmDialogBackdrop')?.addEventListener('click',e=>{if(e.target===$('#confirmDialogBackdrop'))closeDeleteDialog();});
  $('#confirmCancelBtn')?.addEventListener('click',closeDeleteDialog);
  $('#confirmDeleteBtn')?.addEventListener('click',async()=>{const target=deleteTarget;if(!target)return;hideDeleteDialog();if(history.state?.overlay==='delete')history.back();await P.remove(target.key);if(state.playerKey===target.key)state.playerKey='';closeOpenSquadSwipe();await renderSquad();await renderDashboard();toast(`${target.name||'Player'} deleted`);persistUiState();});

  // ---------- Dashboard / Squad ----------
  async function renderDashboard(){const players=await P.all(),avg=players.length?players.reduce((a,p)=>a+Number(p.ovr||0),0)/players.length:0,high=players.length?Math.max(...players.map(p=>Number(p.ovr||0))):0;$('#dashboardStats').innerHTML=`<div class="stat lime"><b>${players.length}</b><span>Players</span></div><div class="stat"><b>${players.length?Math.round(avg):'—'}</b><span>Avg OVR</span></div><div class="stat"><b>${players.length?high:'—'}</b><span>Highest</span></div>`;$('#dashboardSquadLabel').textContent=players.length?`${players.length} saved player${players.length===1?'':'s'}`:'Add your first player';}
  function category(pos){if(pos==='GK')return'GK';if(['DL','DC','DR','DMC'].includes(pos))return'DEF';if(['ML','MC','MR'].includes(pos))return'MID';return'ATT';}
  async function renderSquad(){
    const players=await P.all(),counts={ALL:players.length,GK:0,DEF:0,MID:0,ATT:0};players.forEach(p=>counts[category(p.position)]++);
    $('#squadFilters').innerHTML=['ALL','GK','DEF','MID','ATT'].map(x=>`<button class="chip ${state.squadFilter===x?'active':''}" data-squad-filter="${x}">${x}<small>${counts[x]}</small></button>`).join('');
    $('#squadRoleFilter').innerHTML='<option value="">Any role</option>'+D.ALL_POSITIONS.map(r=>`<option value="${r}" ${state.squadRole===r?'selected':''}>${r}</option>`).join('');
    const knownPlaystyles=[...new Set(players.map(P.playstyleName).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    $('#squadPlaystyleFilter').innerHTML='<option value="">Any playstyle</option>'+knownPlaystyles.map(x=>`<option value="${esc(x)}" ${state.squadPlaystyle===x?'selected':''}>${esc(x)}</option>`).join('');
    const knownAvailability=[...new Set(players.map(p=>String(p.availability??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    $('#squadAvailabilityFilter').innerHTML='<option value="">Any availability</option><option value="__unknown" '+(state.squadAvailability==='__unknown'?'selected':'')+'>Not stored</option>'+knownAvailability.map(x=>`<option value="${esc(x)}" ${state.squadAvailability===x?'selected':''}>${esc(x)}</option>`).join('');
    $('#squadAgeMin').value=state.squadAgeMin;$('#squadAgeMax').value=state.squadAgeMax;$('#squadOvrMin').value=state.squadOvrMin;$('#squadOvrMax').value=state.squadOvrMax;
    const q=state.search.trim().toLowerCase(),minAge=Number(state.squadAgeMin),maxAge=Number(state.squadAgeMax),minOvr=Number(state.squadOvrMin),maxOvr=Number(state.squadOvrMax);
    const filtered=players.filter(p=>{
      const roles=P.normaliseRoles(p),ps=P.playstyleName(p),availability=String(p.availability??'').trim(),age=Number(p.age),ovr=Number(p.ovr);
      if(state.squadFilter!=='ALL'&&category(p.position)!==state.squadFilter)return false;
      if(state.squadRole&&!roles.includes(state.squadRole))return false;
      if(state.squadPlaystyle&&ps!==state.squadPlaystyle)return false;
      if(state.squadAvailability==='__unknown'&&availability)return false;
      if(state.squadAvailability&&state.squadAvailability!=='__unknown'&&availability!==state.squadAvailability)return false;
      if(state.squadAgeMin!==''&&(!Number.isFinite(age)||age<minAge))return false;
      if(state.squadAgeMax!==''&&(!Number.isFinite(age)||age>maxAge))return false;
      if(state.squadOvrMin!==''&&(!Number.isFinite(ovr)||ovr<minOvr))return false;
      if(state.squadOvrMax!==''&&(!Number.isFinite(ovr)||ovr>maxOvr))return false;
      if(q&&!String(p.name||'').toLowerCase().includes(q)&&!rolesLabel(p).toLowerCase().includes(q)&&!ps.toLowerCase().includes(q))return false;
      return true;
    });
    $('#squadList').innerHTML=filtered.length?filtered.map((p,i)=>`<div class="player-swipe ${openSquadSwipeKey===p.key?'open':''}" data-swipe-key="${esc(p.key)}"><div class="player-delete-rail"><button type="button" class="player-delete-action" data-squad-delete="${esc(p.key)}" data-player-name="${esc(p.name||'Unnamed Player')}">Delete</button></div><button class="player-row player-swipe-content" data-player-open="${esc(p.key)}"><div class="squad-rank">${i+1}</div><img class="player-art" src="${roleAsset(p.position)}"><div class="player-copy"><div class="player-name">${esc(p.name||'Unnamed Player')}</div><div class="player-meta"><span class="pos-tag">${esc(p.position||'?')}</span>${esc(P.normaliseRoles(p).slice(1).join(' · '))}${p.age?` · Age ${esc(p.age)}`:''}${psLabel(p)?` · ${esc(psLabel(p))}`:''}</div></div><div class="ovr"><span>OVR</span><b>${esc(p.ovr||'—')}</b></div><div class="row-arrow">›</div></button></div>`).join(''):`<div class="empty"><b>No players here</b>${players.length?'Change the search or filters.':'Add your first player with Scanner v4.'}</div>`;
  }
  function psLabel(p){return P.playstyleName(p)||'';}
  $('#squadSearch')?.addEventListener('input',e=>{state.search=e.target.value;persistUiState();renderSquad();});
  $('#clearSearchBtn')?.addEventListener('click',()=>{$('#squadSearch').value='';state.search='';persistUiState();renderSquad();});
  $('#squadRoleFilter')?.addEventListener('change',e=>{state.squadRole=e.target.value;persistUiState();renderSquad();});
  $('#squadPlaystyleFilter')?.addEventListener('change',e=>{state.squadPlaystyle=e.target.value;persistUiState();renderSquad();});
  $('#squadAvailabilityFilter')?.addEventListener('change',e=>{state.squadAvailability=e.target.value;persistUiState();renderSquad();});
  for(const [id,key] of [['#squadAgeMin','squadAgeMin'],['#squadAgeMax','squadAgeMax'],['#squadOvrMin','squadOvrMin'],['#squadOvrMax','squadOvrMax']])$(id)?.addEventListener('input',e=>{state[key]=e.target.value;persistUiState();renderSquad();});
  $('#clearSquadFiltersBtn')?.addEventListener('click',()=>{Object.assign(state,{squadFilter:'ALL',search:'',squadRole:'',squadAgeMin:'',squadAgeMax:'',squadOvrMin:'',squadOvrMax:'',squadPlaystyle:'',squadAvailability:''});$('#squadSearch').value='';persistUiState();renderSquad();});
  $('#refreshSquadBtn')?.addEventListener('click',renderSquad);
  function closeOpenSquadSwipe(){if(!openSquadSwipeKey)return;const el=document.querySelector(`.player-swipe[data-swipe-key="${CSS.escape(openSquadSwipeKey)}"]`);el?.classList.remove('open');el?.querySelector('.player-swipe-content')?.style.removeProperty('transform');openSquadSwipeKey='';}
  function openSquadSwipe(key,el){if(openSquadSwipeKey&&openSquadSwipeKey!==key)closeOpenSquadSwipe();openSquadSwipeKey=key;el?.classList.add('open');el?.querySelector('.player-swipe-content')?.style.removeProperty('transform');}
  const squadSwipe={active:false,key:'',el:null,startX:0,startY:0,lastX:0,lastY:0,mode:'',pointerId:null};
  $('#squadList')?.addEventListener('pointerdown',e=>{if(e.target.closest('[data-squad-delete]'))return;const el=e.target.closest('.player-swipe');if(!el)return;if(openSquadSwipeKey&&openSquadSwipeKey!==el.dataset.swipeKey)closeOpenSquadSwipe();Object.assign(squadSwipe,{active:true,key:el.dataset.swipeKey,el,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,mode:'',pointerId:e.pointerId});});
  $('#squadList')?.addEventListener('pointermove',e=>{if(!squadSwipe.active||e.pointerId!==squadSwipe.pointerId||!squadSwipe.el)return;const dx=e.clientX-squadSwipe.startX,dy=e.clientY-squadSwipe.startY;squadSwipe.lastX=e.clientX;squadSwipe.lastY=e.clientY;if(!squadSwipe.mode){if(Math.abs(dy)>10&&Math.abs(dy)>Math.abs(dx)*1.2){squadSwipe.mode='vertical';return;}if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.25)squadSwipe.mode='horizontal';}if(squadSwipe.mode==='horizontal'){e.preventDefault();const base=openSquadSwipeKey===squadSwipe.key?-82:0,offset=Math.max(-82,Math.min(0,base+dx));squadSwipe.el.querySelector('.player-swipe-content').style.transform=`translateX(${offset}px)`;}});
  function finishSquadSwipe(e){if(!squadSwipe.active||(e?.pointerId!=null&&e.pointerId!==squadSwipe.pointerId))return;const dx=squadSwipe.lastX-squadSwipe.startX,dy=squadSwipe.lastY-squadSwipe.startY,el=squadSwipe.el,key=squadSwipe.key,wasHorizontal=squadSwipe.mode==='horizontal',wasOpen=openSquadSwipeKey===key;squadSwipe.active=false;if(wasHorizontal){suppressSquadClickUntil=Date.now()+350;if(wasOpen){if(dx>35)closeOpenSquadSwipe();else openSquadSwipe(key,el);}else if(dx<-42)openSquadSwipe(key,el);else closeOpenSquadSwipe();}else if(Math.abs(dx)>Math.abs(dy)*1.5&&dx<-55){suppressSquadClickUntil=Date.now()+350;openSquadSwipe(key,el);}if(el&&!el.classList.contains('open'))el.querySelector('.player-swipe-content')?.style.removeProperty('transform');}
  $('#squadList')?.addEventListener('pointerup',finishSquadSwipe);$('#squadList')?.addEventListener('pointercancel',finishSquadSwipe);
  document.addEventListener('click',e=>{const f=e.target.closest('[data-squad-filter]');if(f){state.squadFilter=f.dataset.squadFilter;persistUiState();renderSquad();return;}const del=e.target.closest('[data-squad-delete]');if(del){openDeleteDialog(del.dataset.squadDelete,del.dataset.playerName);return;}const row=e.target.closest('[data-player-open]');if(row){if(Date.now()<suppressSquadClickUntil)return;if(openSquadSwipeKey){closeOpenSquadSwipe();return;}state.playerKey=row.dataset.playerOpen;persistUiState();go('player');return;}if(openSquadSwipeKey&&!e.target.closest('.player-swipe'))closeOpenSquadSwipe();});

  // ---------- Player profile ----------
  function profileGroups(player){return player.position==='GK'?D.GROUPS_GK:D.GROUPS_OUTFIELD;}
  function weakestKeySkills(player,limit=6){const white=new Set(D.whiteSkillsForRoles(P.normaliseRoles(player)));return Object.entries(player.skills||{}).filter(([name,v])=>white.has(name)&&Number.isFinite(Number(v))).sort((a,b)=>Number(a[1])-Number(b[1])||a[0].localeCompare(b[0])).slice(0,limit);}
  function renderProfileAbilities(){$('#profileAbilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button type="button" class="chip profile-ability-chip ${state.profileAbilities.includes(a)?'active':''}" data-profile-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  function renderProfileRelated(){const natural=new Set([...currentEditRoles(),...state.profilePreservedRoles]);state.profileRelatedRoles=state.profileRelatedRoles.filter(r=>!natural.has(r));$('#profileRelatedPicker').innerHTML=D.ALL_POSITIONS.filter(a=>!natural.has(a)).map(a=>`<button type="button" class="chip ${state.profileRelatedRoles.includes(a)?'active':''}" data-profile-related="${a}">${a}</button>`).join('');}
  function fillRoleSelect(id,value,allowBlank=false,allowed=D.ALL_POSITIONS){$(id).innerHTML=(allowBlank?'<option value="">None</option>':'')+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');}
  function playstyleOptions(roles,current){const allowed=D.playstylesForRoles(roles),currentName=typeof current==='object'?P.playstyleName({playstyle:current}):String(current||'');const legacy=currentName&&!allowed.includes(currentName)?`<option value="${esc(currentName)}" selected>${esc(currentName)} (preserved)</option>`:'';return '<option value="">No playstyle</option>'+legacy+allowed.map(x=>`<option value="${esc(x)}" ${x===currentName?'selected':''}>${esc(x)}</option>`).join('');}
  function playstyleLevelLabel(ps){
    if(!ps?.type)return 'No playstyle';
    const level=Number(ps.level)||0;
    if(level===0)return 'Level not captured';
    return B.PLAYSTYLE_LEVELS.find(x=>x.id===level)?.name||`Level ${level}`;
  }
  function playstyleLevelOptions(current=0,hasPlaystyle=true){
    const n=Number(current)||0;
    const rows=B.PLAYSTYLE_LEVELS.filter(x=>x.id>=1&&x.name!=='Standard');
    return `<option value="">${hasPlaystyle?'Tier not captured':'No playstyle'}</option>`+rows.map(x=>`<option value="${x.id}" ${x.id===n?'selected':''}>${esc(x.name)}</option>`).join('');
  }
  function renderPlaystyleState(p){
    const ps=P.normalisePlaystyle(p.playstyle),name=P.playstyleName(p);
    const rows=[];
    rows.push(['Playstyle',name||'None']);
    rows.push(['Level',playstyleLevelLabel(ps)]);
    if(ps.points!=null)rows.push(['Points',ps.points]);
    if(ps.nextLevelProgress!=null)rows.push(['Next-level progress',ps.nextLevelProgress]);
    if(ps.nextLevelPrice!=null)rows.push(['Next-level price',ps.nextLevelPrice]);
    if(ps.isTrainingNextLevel!=null)rows.push(['Training next level',ps.isTrainingNextLevel?'Yes':'No']);
    if(ps.isNextLevelAvailable!=null)rows.push(['Next level available',ps.isNextLevelAvailable?'Yes':'No']);
    if(ps.boost!=null)rows.push(['Captured boost',Array.isArray(ps.boost)?JSON.stringify(ps.boost):ps.boost]);
    $('#profilePlaystyleState').innerHTML=rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');
    $('#profilePlaystyleCard').style.display=name||rows.length>2?'block':'none';
  }
  async function renderPlayerProfile(){
    if(!state.playerKey){go('squad',{historyMode:'replace'});return;}
    const p=await P.get(state.playerKey);if(!p){toast('Player could not be loaded','err');state.playerKey='';go('squad',{historyMode:'replace'});return;}
    const roles=P.normaliseRoles(p),related=P.normaliseRelatedRoles(p),white=new Set(D.whiteSkillsForRoles(roles));
    $('#profileRoleArt').src=roleAsset(p.position);$('#profileRoleArt').alt=`${P.roleGroup(p.position).toUpperCase()} role artwork`;
    $('#profileName').textContent=p.name||'Player';$('#profileOvr').textContent=p.ovr||'—';$('#profileEyebrow').textContent=`${p.position} · Player Profile`;
    $('#profileMeta').innerHTML=`${roles.map(r=>`<span>${esc(r)}</span>`).join('')}${related.length?`<span>Related ${esc(related.join('/'))}</span>`:''}${p.age?`<span>Age ${esc(p.age)}</span>`:''}`;
    const badges=[],ps=P.playstyleName(p);if(ps)badges.push(`<div class="profile-badge"><strong>PLAYSTYLE</strong> · ${esc(ps)} · ${esc(playstyleLevelLabel(p.playstyle))}</div>`);for(const a of p.specialAbilities||[])badges.push(`<div class="profile-badge gold"><strong>ABILITY</strong> · ${esc(a)}</div>`);if(p.scanner?.version){const verified=!!(p.scanner.validation?.resolved||p.scanner.validation?.manualVerified);badges.push(`<div class="profile-badge"><strong>SCAN</strong> · v${esc(p.scanner.version)} · ${verified?'VERIFIED':(p.scanner.confidence?.overall?Math.round(p.scanner.confidence.overall*100)+'% AI read':'REVIEW')}</div>`);}$('#profileBadges').innerHTML=badges.join('')||'<div class="profile-badge">No playstyle or special ability selected</div>';
    const facts=[];if(p.condition!=null&&p.condition!=='')facts.push(['Condition',`${esc(p.condition)}%`]);if(p.availability!=null&&p.availability!=='')facts.push(['Availability',esc(p.availability)]);if(p.morale!=null&&p.morale!=='')facts.push(['Morale',esc(p.morale)]);$('#profileFacts').innerHTML=facts.map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('');$('#profileFacts').style.display=facts.length?'grid':'none';
    renderPlaystyleState(p);
    const weak=weakestKeySkills(p);$('#profileKeySkills').innerHTML=weak.length?weak.map(([name,v])=>`<div class="profile-key"><span>${esc(name)}</span><div class="track"><i style="width:${Math.max(3,Math.min(100,Number(v)/2.5))}%"></i></div><b>${esc(v)}</b></div>`).join(''):'<div class="empty"><b>No skill data</b>Update this player from a scan to populate attributes.</div>';
    $('#profileRoleScores').innerHTML=roles.map(role=>{const rs=F.roleStats(p,role);return rs?`<div class="profile-key"><span>${role} · Top Eleven Tool Role Score</span><div class="track"><i style="width:${Math.min(100,rs.roleMean/2.5)}%"></i></div><b>${fmt(rs.roleMean,1)}</b><small>Weakest 3: ${esc(rs.weakest.map(x=>`${x.attribute} ${x.value}`).join(' · '))}</small></div>`:'';}).join('')||'<div class="empty">Role score needs complete visible attributes.</div>';
    $('#profileSkills').innerHTML=Object.entries(profileGroups(p)).map(([group,names])=>`<div class="skill-group"><h3>${esc(group)}</h3><div class="skill-grid">${names.map(name=>`<div class="skill ${white.has(name)?'white':'grey'}"><span>${esc(name)}</span><b>${esc(p.skills?.[name]??'—')}</b></div>`).join('')}</div></div>`).join('');
    $('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';$('#profileEditNote').textContent=p.legacyRoles?.length?`Legacy roles preserved but not selectable: ${p.legacyRoles.join(', ')}`:'';
  }
  async function openProfileEdit(){
    const p=await P.get(state.playerKey);if(!p)return;const roles=P.normaliseRoles(p);
    state.profileAbilities=[...(p.specialAbilities||[])];state.profileRelatedRoles=[...P.normaliseRelatedRoles(p)];state.profilePreservedRoles=roles.slice(3);
    $('#profileEditName').value=p.name||'';$('#profileEditAge').value=p.age??'';$('#profileEditOvr').value=p.ovr??'';
    const allowed=p.position==='GK'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK');
    fillRoleSelect('#profileEditRole1',roles[0]||p.position,false,allowed);fillRoleSelect('#profileEditRole2',roles[1]||'',true,p.position==='GK'?[]:allowed);fillRoleSelect('#profileEditRole3',roles[2]||'',true,p.position==='GK'?[]:allowed);
    $('#profileEditRole2').disabled=p.position==='GK';$('#profileEditRole3').disabled=p.position==='GK';$('#profileEditPlaystyle').innerHTML=playstyleOptions(roles,p.playstyle);const profilePs=P.normalisePlaystyle(p.playstyle);$('#profileEditPlaystyleLevel').innerHTML=playstyleLevelOptions(profilePs.level,!!P.playstyleName(p));$('#profileEditPlaystyleLevel').disabled=!P.playstyleName(p);
    $('#profilePreservedRolesNote').textContent=state.profilePreservedRoles.length?`Additional imported natural roles preserved: ${state.profilePreservedRoles.join(', ')}. This three-role editor will not delete them.`:'';
    renderProfileAbilities();renderProfileRelated();$('#profileEditCard').style.display='block';$('#profileEditBtn').textContent='Editing';$('#profileEditCard').scrollIntoView({behavior:'smooth',block:'start'});
  }
  function currentEditRoles(){return [$('#profileEditRole1')?.value,$('#profileEditRole2')?.value,$('#profileEditRole3')?.value].filter((r,i,a)=>r&&a.indexOf(r)===i);}
  ['#profileEditRole1','#profileEditRole2','#profileEditRole3'].forEach(id=>$(id)?.addEventListener('change',()=>{const allNatural=[...new Set([...currentEditRoles(),...state.profilePreservedRoles])];$('#profileEditPlaystyle').innerHTML=playstyleOptions(allNatural,$('#profileEditPlaystyle').value);renderProfileRelated();}));
  $('#profileEditPlaystyle')?.addEventListener('change',e=>{const has=!!e.target.value;$('#profileEditPlaystyleLevel').disabled=!has;$('#profileEditPlaystyleLevel').value='';});
  $('#profileBackBtn')?.addEventListener('click',()=>{if(history.state?.teTopEleven&&history.length>1)history.back();else go('squad',{historyMode:'replace'});});$('#profileTrainBtn')?.addEventListener('click',()=>{if(state.playerKey){state.trainingKey=state.playerKey;go('training');}});$('#profileEditBtn')?.addEventListener('click',openProfileEdit);$('#profileCancelEditBtn')?.addEventListener('click',()=>{$('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-ability]');if(b){const a=b.dataset.profileAbility;state.profileAbilities=state.profileAbilities.includes(a)?state.profileAbilities.filter(x=>x!==a):[...state.profileAbilities,a];renderProfileAbilities();return;}const rr=e.target.closest('[data-profile-related]');if(rr){const r=rr.dataset.profileRelated;state.profileRelatedRoles=state.profileRelatedRoles.includes(r)?state.profileRelatedRoles.filter(x=>x!==r):[...state.profileRelatedRoles,r];renderProfileRelated();}});
  $('#profileSaveBtn')?.addEventListener('click',async()=>{
    const existing=await P.get(state.playerKey);if(!existing)return;
    const name=$('#profileEditName').value.trim(),age=Number($('#profileEditAge').value),ovr=Number($('#profileEditOvr').value),primary=$('#profileEditRole1').value;
    if(!name||!primary){toast('Name and primary role are required','err');return;}if(!Number.isFinite(age)||age<15||age>60){toast('Age must be between 15 and 60','err');return;}if(!Number.isFinite(ovr)||ovr<1||ovr>520){toast('OVR must be between 1 and 520','err');return;}
    const duplicate=(await P.all()).find(x=>x.key!==state.playerKey&&String(x.name||'').trim().toLowerCase()===name.toLowerCase());if(duplicate){toast('Another player already uses that name','err');return;}
    const roles=P.mergeVisibleNaturalRoles(P.normaliseRoles(existing),currentEditRoles(),3),related=state.profileRelatedRoles.filter(r=>!roles.includes(r));
    let playstyle=P.mergePlaystyleState(existing.playstyle,$('#profileEditPlaystyle').value);const profileLevel=Number($('#profileEditPlaystyleLevel').value)||0;if($('#profileEditPlaystyle').value&&profileLevel>=1)playstyle={...playstyle,level:profileLevel};
    await P.save({...existing,name,age,ovr,position:roles[0]||primary,roles,relatedRoles:related,playstyle,specialAbilities:[...state.profileAbilities]},state.playerKey);
    toast('Player updated');await renderDashboard();await renderPlayerProfile();
  });
  $('#profileDeleteBtn')?.addEventListener('click',async()=>{const b=$('#profileDeleteBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to delete';$('#profileEditNote').textContent='This permanently removes the player and their saved training session.';setTimeout(()=>{delete b.dataset.armed;b.textContent='Delete Player';},3500);return;}const p=await P.get(state.playerKey);await P.remove(state.playerKey);state.playerKey='';state.trainingKey='';delete b.dataset.armed;b.textContent='Delete Player';toast(`${p?.name||'Player'} deleted`);await renderDashboard();go('squad',{historyMode:'replace'});});

  // ---------- Refresh-safe scanner queue persistence ----------
  function openQueueDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return;}const req=indexedDB.open(QUEUE_DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(QUEUE_STORE))req.result.createObjectStore(QUEUE_STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async function queueImagePut(id,dataUrl){try{const db=await openQueueDb();if(!db)return false;await new Promise((resolve,reject)=>{const tx=db.transaction(QUEUE_STORE,'readwrite');tx.objectStore(QUEUE_STORE).put(dataUrl,String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return true;}catch(_){return false;}}
  async function queueImageGet(id){try{const db=await openQueueDb();if(!db)return null;const value=await new Promise((resolve,reject)=>{const tx=db.transaction(QUEUE_STORE,'readonly'),req=tx.objectStore(QUEUE_STORE).get(String(id));req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();return value;}catch(_){return null;}}
  async function queueImageDelete(id){try{const db=await openQueueDb();if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction(QUEUE_STORE,'readwrite');tx.objectStore(QUEUE_STORE).delete(String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}catch(_){/* best effort */}}
  function serialiseQueueItem(item){const {dataUrl,...rest}=item;return{...rest,imageStored:!!item.imageStored};}
  async function persistScanQueueState(){try{const current=currentQueueItem?.();await S.setJSON(SCAN_QUEUE_META_KEY,{version:1,seq:state.scanQueueSeq,reviewId:current?.id||null,items:state.scanQueue.map(serialiseQueueItem),savedAt:Date.now()});}catch(_){/* queue persistence is best effort */}}
  function schedulePersistScanQueue(){clearTimeout(schedulePersistScanQueue.t);schedulePersistScanQueue.t=setTimeout(()=>persistScanQueueState(),40);}
  async function restoreScanQueueState(){const saved=await S.getJSON(SCAN_QUEUE_META_KEY,null);if(!saved?.items?.length)return;const rows=[];for(const raw of saved.items){const item={...raw,dataUrl:null,nextRetryAt:0};if(item.imageStored)item.dataUrl=await queueImageGet(item.id);if(['scanning','fallback','waiting'].includes(item.status)&&item.dataUrl){item.status='error';item.error='A previous scan was interrupted. Tap Retry Scan when you want to try again.';item.statusText='NEEDS RETRY · previous request stopped';}if(!item.manual&&!item.dataUrl&&item.status!=='saved'){item.status='error';item.statusText='NEEDS RETRY · screenshot could not be restored';item.error='The queued screenshot could not be restored. Remove it and add the screenshot again.';}rows.push(item);}state.scanQueue=rows;state.scanQueueSeq=Math.max(Number(saved.seq)||0,...rows.map(x=>Number(x.id)||0),0);const reviewIndex=rows.findIndex(x=>x.id===saved.reviewId&&['ready','saved'].includes(x.status));state.scanQueueReviewIndex=reviewIndex;renderScanQueue();if(reviewIndex>=0)loadQueueReview(reviewIndex);if(rows.some(x=>x.status==='queued'))runScanQueue();}

  // ---------- Scanner v4 · Gemini 3.1 Flash Live · batch review queue ----------
  function resetScanner(){state.scan=null;state.scanAbilities=[];state.scanRelatedRoles=[];state.scanDuplicateKey='';state.scanPreservedRoles=[];state.scanManualVerified=false;state.scanQueueReviewIndex=-1;if($('#scanReview'))$('#scanReview').style.display='none';if($('#scanPreview'))$('#scanPreview').removeAttribute('src');$('#scanWindow')?.classList.remove('has-image','scanning');if($('#scanProgressBar'))$('#scanProgressBar').style.width='0%';if($('#scanProgressText'))$('#scanProgressText').textContent='Choose one or more player screenshots';if($('#scanPercent'))$('#scanPercent').textContent='0%';}
  function clearScannerReview(){state.scan=null;state.scanAbilities=[];state.scanRelatedRoles=[];state.scanPreservedRoles=[];state.scanDuplicateKey='';state.scanManualVerified=false;state.scanQueueReviewIndex=-1;$('#scanReview').style.display='none';$('#scanSaveNote').textContent='';if($('#scanManualVerified'))$('#scanManualVerified').checked=false;if($('#scanManualVerify'))$('#scanManualVerify').style.display='none';updateQueueReviewButtons();renderScanQueue();schedulePersistScanQueue();}
  function progress(p){const pct=Math.round((p.progress||0)*100);$('#scanProgressBar').style.width=pct+'%';$('#scanProgressText').textContent=p.label||'Scanning';$('#scanPercent').textContent=pct+'%';}
  const fileToDataUrl=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});
  function playstyleTierValue(){return Number($('#scanPlaystyleLevel')?.value)||0;}
  function currentQueueItem(){return state.scanQueueReviewIndex>=0?state.scanQueue[state.scanQueueReviewIndex]||null:null;}
  function queueStatusLabel(item){const labels={queued:'QUEUED',scanning:'SCANNING',fallback:'NEEDS RETRY',waiting:'NEEDS RETRY',ready:'READY TO REVIEW',saved:'SAVED',error:'NEEDS RETRY',failed:'SCAN FAILED'};return labels[item.status]||String(item.status||'').toUpperCase();}
  function renderScanQueue(){
    const el=$('#scanQueue');if(!el)return;
    if(!state.scanQueue.length){el.innerHTML='';return;}
    const counts={queued:0,scanning:0,ready:0,saved:0,error:0,failed:0};state.scanQueue.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);
    const retryCount=(counts.error||0)+(counts.failed||0)+(counts.waiting||0)+(counts.fallback||0);
    el.innerHTML=`<div class="scan-queue-summary"><span>${state.scanQueue.length} player${state.scanQueue.length===1?'':'s'} in queue</span><span>${counts.ready} ready · ${counts.saved} saved${retryCount?` · ${retryCount} retry`:''}</span></div>`+state.scanQueue.map((item,i)=>{const detail=item.statusText||item.error||queueStatusLabel(item);const canOpen=item.status==='ready'||item.status==='saved';const canRetry=['error','failed','waiting','fallback'].includes(item.status);return `<div class="scan-queue-row ${esc(item.status)} ${i===state.scanQueueReviewIndex?'reviewing':''}" ${canOpen?`data-queue-open="${i}" role="button" tabindex="0"`:''}><span class="queue-no">${i+1}</span><span class="queue-copy"><b>${esc(item.scan?.name||item.fileName||'Manual player')}</b><small>${esc(detail)}</small></span><span><span class="queue-state">${esc(queueStatusLabel(item))}</span>${canRetry?`<button type="button" class="scan-queue-retry" data-queue-retry="${i}">Retry Scan</button>`:''}<button type="button" class="scan-queue-remove" data-queue-remove="${i}" aria-label="Remove from queue">×</button></span></div>`}).join('');
  }
  function reviewableIndices(){return state.scanQueue.map((x,i)=>x.status==='ready'?i:-1).filter(i=>i>=0);}
  function persistCurrentQueueDraft(){
    const item=currentQueueItem();if(!item||!state.scan||item.status==='saved')return;
    item.reviewState={name:$('#scanName')?.value??'',age:$('#scanAge')?.value??'',ovr:$('#scanOvr')?.value??'',roles:[$('#scanRole')?.value,$('#scanRole2')?.value,$('#scanRole3')?.value].filter(Boolean),relatedRoles:[...state.scanRelatedRoles],playstyleName:$('#scanPlaystyle')?.value||'',playstyleLevel:playstyleTierValue(),abilities:[...state.scanAbilities],manualVerified:!!state.scanManualVerified};schedulePersistScanQueue();
  }
  function updateQueueReviewButtons(){
    const item=currentQueueItem(),ready=reviewableIndices(),hasOther=ready.some(i=>i!==state.scanQueueReviewIndex);
    const save=$('#saveScannedPlayer'),next=$('#nextQueuedPlayerBtn'),rescan=$('#rescanBtn');
    if(save)save.textContent=hasOther?'Save & Next':'Save Player';
    if(next){next.style.display=hasOther?'inline-flex':'none';next.disabled=!hasOther;}
    if(rescan){rescan.style.display=item&&!item.manual&&item.status==='ready'?'inline-flex':'none';rescan.disabled=!item||item.manual||item.status!=='ready';}
  }
  function scanRequiredSkills(scan=state.scan){return scan?.layout==='gk'?[...D.GK_SKILLS,...D.GK_PHYSICAL]:[...D.OUTFIELD_SKILLS];}
  function scanDataComplete(){if(!state.scan)return false;const req=scanRequiredSkills(),skills=state.scan.skills||{};return !!($('#scanName')?.value.trim()&&$('#scanRole')?.value&&Number.isFinite(Number($('#scanAge')?.value))&&Number.isFinite(Number($('#scanOvr')?.value))&&req.every(s=>Number.isFinite(Number(skills[s]))));}
  function renderScanConfidence(){
    const el=$('#scanConfidence');if(!el||!state.scan)return;
    if(state.scan.manualEntry){el.innerHTML='<span class="chip manual-mode-badge">Manual entry</span>';return;}
    const checks=Object.values(state.scan.checks||{}),all=checks.length>0&&checks.every(c=>c.ok),n=Math.round((state.scan.confidence?.overall||0)*100);
    if(state.scanManualVerified){el.innerHTML=`<span class="chip verified-badge">✓ Manually verified</span><span class="confidence-secondary">Gemini read score ${n}%</span>`;return;}
    if(all&&scanDataComplete()){el.innerHTML=`<span class="chip verified-badge">✓ Arithmetic checks passed</span><span class="confidence-secondary">Gemini read score ${n}%</span>`;return;}
    el.innerHTML=`<span class="chip active">Gemini read score ${n}%</span>`;
  }
  function renderAbilityPicker(){$('#abilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button type="button" class="chip ${state.scanAbilities.includes(a)?'active':''}" data-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  function renderScanRelated(){const natural=new Set([$('#scanRole')?.value,$('#scanRole2')?.value,$('#scanRole3')?.value].filter(Boolean));state.scanRelatedRoles=state.scanRelatedRoles.filter(r=>!natural.has(r));$('#scanRelatedPicker').innerHTML=D.ALL_POSITIONS.filter(r=>!natural.has(r)).map(r=>`<button type="button" class="chip ${state.scanRelatedRoles.includes(r)?'active':''}" data-scan-related="${r}">${r}</button>`).join('');}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-ability]');if(b){const a=b.dataset.ability;if(state.scanAbilities.includes(a))state.scanAbilities=state.scanAbilities.filter(x=>x!==a);else state.scanAbilities.push(a);renderAbilityPicker();return;}const rr=e.target.closest('[data-scan-related]');if(rr){const r=rr.dataset.scanRelated;state.scanRelatedRoles=state.scanRelatedRoles.includes(r)?state.scanRelatedRoles.filter(x=>x!==r):[...state.scanRelatedRoles,r];renderScanRelated();}});
  function currentScanChecks(ovrValue){
    if(!state.scan)return{};const skills=state.scan.skills||{},totals=state.scan.raw?.totals||{},checks={};
    if(!state.scan.manualEntry){if(state.scan.layout==='gk'){checks.goalkeeping=SC.checkAggregate(D.GK_SKILLS.map(s=>Number(skills[s])),totals.att);checks.physical=SC.checkAggregate(D.GK_PHYSICAL.map(s=>Number(skills[s])),totals.phys);}else{checks.defence=SC.checkAggregate(D.GROUPS_OUTFIELD.Defence.map(s=>Number(skills[s])),totals.def);checks.attack=SC.checkAggregate(D.GROUPS_OUTFIELD.Attack.map(s=>Number(skills[s])),totals.att);checks.physical=SC.checkAggregate(D.GROUPS_OUTFIELD.Physical.map(s=>Number(skills[s])),totals.phys);}}
    const vals=Object.values(skills).map(Number).filter(Number.isFinite),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,ovr=Number(ovrValue);checks.ovr={average:avg,error:Number.isFinite(ovr)&&vals.length?Math.abs(avg-ovr):null,ok:Number.isFinite(ovr)&&vals.length===scanRequiredSkills().length&&Math.abs(avg-ovr)<=1.5};return checks;
  }
  function scanUnresolved(checks){return Object.entries(checks||{}).filter(([,c])=>!c.ok);}
  function refreshScanVerification(){
    if(!state.scan)return true;const checks=currentScanChecks($('#scanOvr').value);state.scan.checks=checks;const unresolved=scanUnresolved(checks);state.scan.validation={resolved:unresolved.length===0,unresolvedChecks:unresolved.map(([name,c])=>({name,error:c.error,average:c.average}))};
    $('#scanChecks').innerHTML=Object.entries(checks).map(([name,c])=>`<div class="verify ${c.ok?'ok':'warn'}"><strong>${c.ok?'✓':'!'} ${esc(name)}</strong><span>${c.error==null?'Not enough data to verify':c.ok?`within display rounding · ${Number(c.error).toFixed(1)}`:`outside tolerance · ${Number(c.error).toFixed(1)}`}</span></div>`).join('');
    const manual=!!state.scanManualVerified,manualBox=$('#scanManualVerify');if(manualBox)manualBox.style.display=!state.scan.manualEntry&&unresolved.length?'block':'none';const save=$('#saveScannedPlayer');if(save)save.disabled=false;
    if(state.scan.manualEntry){const missing=scanRequiredSkills().filter(s=>!Number.isFinite(Number(state.scan.skills?.[s])));$('#scanSaveNote').innerHTML=missing.length?`<b>Manual entry.</b> Enter every visible skill value before saving. ${missing.length} skill${missing.length===1?'':'s'} remaining.`:'<b>Manual entry complete.</b> Review playstyle tier and every special ability, then save.';}
    else if(unresolved.length){const detail=unresolved.map(([name,c])=>`${name}${c.error==null?'':` (${Number(c.error).toFixed(1)} out)`}`).join(', ');$('#scanSaveNote').innerHTML=manual?`<b>Manual verification accepted.</b> Remaining scanner mismatch: ${esc(detail)}. Your reviewed values will be saved and marked as manually verified.`:`<b>Verification required.</b> Cross-check sees: ${esc(detail)}. Correct any wrong values. If the visible values match Top Eleven, tick <b>I checked the screenshot manually</b>.`;}
    else{$('#scanSaveNote').textContent='Arithmetic checks pass within Top Eleven whole-number display rounding. Review the scanned core data, playstyle level and Special Abilities before saving.';}
    renderScanConfidence();persistCurrentQueueDraft();return unresolved.length===0;
  }
  function renderScanSkills(scan){const groups=scan.layout==='gk'?D.GROUPS_GK:D.GROUPS_OUTFIELD;$('#scanSkills').innerHTML=Object.entries(groups).map(([g,names])=>`<div class="skill-group"><h3>${esc(g)}</h3><div class="skill-grid">${names.map(s=>`<label class="skill scan-skill"><span>${esc(s)}</span><input class="scan-skill-input" type="number" min="0" max="520" inputmode="numeric" data-scan-skill="${esc(s)}" value="${esc(scan.skills[s]??'')}"></label>`).join('')}</div></div>`).join('');}
  function populateScanReview(scan,review={}){
    state.scan=scan;state.scanDuplicateKey='';state.scanPreservedRoles=[];state.scanRelatedRoles=[...(review.relatedRoles||[])];state.scanAbilities=[...(review.abilities||scan.specialAbilities||[])];state.scanManualVerified=!!review.manualVerified;$('#scanReview').style.display='block';
    $('#scanName').value=review.name??scan.name??'';$('#scanAge').value=review.age??scan.age??'';$('#scanOvr').value=review.ovr??scan.ovr??'';const reviewRoles=review.roles||scan.roles||[];const allowed=scan.manualEntry?D.ALL_POSITIONS:(scan.layout==='gk'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK'));const fill=(id,value,label)=>{$(id).innerHTML=`<option value="">${label}</option>`+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');};fill('#scanRole',reviewRoles[0]||scan.position,'Choose role');fill('#scanRole2',reviewRoles[1]||'','None');fill('#scanRole3',reviewRoles[2]||'','None');const primary=$('#scanRole').value;$('#scanRole2').disabled=primary==='GK';$('#scanRole3').disabled=primary==='GK';
    $('#detectedRoles').innerHTML=scan.manualEntry?'<span class="chip manual-mode-badge">Manual player</span>':((scan.roles||[]).map((r,i)=>`<span class="chip ${i===0?'active':''}">${esc(r)}${i===0?' · primary':''}</span>`).join('')||'<span class="mini-note">Role needs review.</span>');
    const detectedPs=scan.playstyle?.name||'',selectedPs=review.playstyleName??detectedPs;$('#scanPlaystyle').innerHTML=playstyleOptions(reviewRoles.length?reviewRoles:(scan.roles||[scan.position]),selectedPs);const level=review.playstyleLevel??scan.playstyle?.level??0;$('#scanPlaystyleLevel').innerHTML=playstyleLevelOptions(level,!!selectedPs);$('#scanPlaystyleLevel').disabled=!selectedPs;
    const visual=$('#scanDetectedVisuals');if(visual){const bits=[];if(detectedPs)bits.push(`<b>Playstyle:</b> ${esc(detectedPs)}${scan.playstyle?.levelName?` · ${esc(scan.playstyle.levelName)}`:''}`);if((scan.specialAbilities||[]).length)bits.push(`<b>Abilities:</b> ${esc(scan.specialAbilities.join(', '))}`);visual.innerHTML=(bits.length?bits.join('<br>'):'No playstyle or Special Ability was confidently detected.')+'<br><span>Review and correct any field before saving.</span>';}
    if($('#scanManualVerified'))$('#scanManualVerified').checked=state.scanManualVerified;renderScanRelated();renderAbilityPicker();renderScanSkills(scan);refreshScanVerification();updateQueueReviewButtons();renderScanQueue();
  }
  function loadQueueReview(index){
    if(index<0||index>=state.scanQueue.length)return;persistCurrentQueueDraft();const item=state.scanQueue[index];if(!['ready','saved'].includes(item.status))return;state.scanQueueReviewIndex=index;if(item.dataUrl){$('#scanPreview').src=item.dataUrl;$('#scanWindow').classList.add('has-image');}else{$('#scanPreview').removeAttribute('src');$('#scanWindow').classList.remove('has-image');}populateScanReview(item.scan,item.reviewState||{});$('#scanProgressText').textContent=item.status==='saved'?'Saved player':`Reviewing ${item.scan?.name||item.fileName||`player ${index+1}`}`;$('#scanPercent').textContent='100%';$('#scanProgressBar').style.width='100%';}
  function nextReadyIndex(from=state.scanQueueReviewIndex){const ready=reviewableIndices();if(!ready.length)return-1;const after=ready.find(i=>i>from);return after??ready[0];}
  function cancelScanForItem(itemId){
    const controller=scanControllers.get(Number(itemId));if(controller){controller.abort();scanControllers.delete(Number(itemId));}
  }
  async function runScanQueue(){
    if(state.scanQueueScanning)return;state.scanQueueScanning=true;renderScanQueue();schedulePersistScanQueue();
    try{
      while(true){
        const idx=state.scanQueue.findIndex(x=>x.status==='queued');if(idx<0)break;const item=state.scanQueue[idx];
        if(!item.dataUrl&&item.imageStored)item.dataUrl=await queueImageGet(item.id);
        if(!item.dataUrl){item.status='failed';item.error='Queued screenshot is unavailable. Remove it and add the screenshot again.';item.statusText='SCAN FAILED · screenshot unavailable';renderScanQueue();schedulePersistScanQueue();continue;}
        item.status='scanning';item.error='';item.statusText='SCANNING · core + playstyle + abilities';item.autoAttempts=Math.max(0,Number(item.autoAttempts||0))+1;item.lastAttemptAt=Date.now();item.nextRetryAt=0;renderScanQueue();schedulePersistScanQueue();
        $('#scanPreview').src=item.dataUrl;$('#scanWindow').classList.add('has-image','scanning');
        const controller=new AbortController();scanControllers.set(Number(item.id),controller);
        try{
          const scan=await SC.scan(item.dataUrl,p=>{
            item.status='scanning';item.statusText=p.label||'SCANNING';
            progress({progress:p.progress||0,label:`Player ${idx+1}/${state.scanQueue.length} · ${p.label||'Scanning'}`});renderScanQueue();schedulePersistScanQueue();
          },{signal:controller.signal});
          if(controller.signal.aborted)continue;
          item.scan=scan;item.status='ready';item.statusText=`READY TO REVIEW · ${String(scan.raw?.model||scan.model||'Gemini').replace(/^gemini-/,'')} · visuals detected`;item.fileName=scan.name||item.fileName;item.nextRetryAt=0;item.error='';renderScanQueue();schedulePersistScanQueue();
        }catch(err){
          if(err?.code==='SCAN_CANCELLED'){item.status='error';item.error='Scan cancelled. Tap Retry Scan when you want to run it again.';item.statusText='NEEDS RETRY · scan cancelled';}
          else{item.status='failed';item.nextRetryAt=0;item.error=err?.message||'Scan failed';item.statusText=err?.kind==='quota_daily'?'SCAN FAILED · free quota exhausted':'SCAN FAILED · tap Retry Scan';}
          renderScanQueue();schedulePersistScanQueue();
        }finally{
          if(scanControllers.get(Number(item.id))===controller)scanControllers.delete(Number(item.id));
          $('#scanWindow').classList.remove('scanning');
        }
        // Process the next queued player. Failed scans stay stopped until the user explicitly retries them.
      }
    }finally{
      state.scanQueueScanning=false;renderScanQueue();schedulePersistScanQueue();
      if(state.scanQueueReviewIndex<0){const first=reviewableIndices()[0];if(first!=null)loadQueueReview(first);}
      const ready=reviewableIndices().length,pending=state.scanQueue.filter(x=>x.status==='queued'||x.status==='scanning').length,failed=state.scanQueue.filter(x=>['error','failed'].includes(x.status)).length;
      if(ready)progress({progress:1,label:`Queue ready · ${ready} player${ready===1?'':'s'} to review${failed?` · ${failed} need retry`:''}`});
      else if(!pending&&failed)progress({progress:1,label:`Queue stopped · ${failed} scan${failed===1?'':'s'} need Retry Scan`});
      else if(!pending)progress({progress:1,label:'Queue finished'});
    }
  }
  async function addFilesToQueue(files){
    const list=[...files].filter(f=>f.type?.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(f.name));if(!list.length)return;
    for(const file of list){const dataUrl=await fileToDataUrl(file),id=++state.scanQueueSeq;const imageStored=await queueImagePut(id,dataUrl);state.scanQueue.push({id,fileName:file.name,dataUrl,status:'queued',statusText:'QUEUED',scan:null,error:'',manual:false,reviewState:null,imageStored,autoAttempts:0,nextRetryAt:0});}
    $('#scanFile').value='';renderScanQueue();schedulePersistScanQueue();toast(`${list.length} screenshot${list.length===1?'':'s'} added to scan queue`);runScanQueue();
  }
  $('#scanFile')?.addEventListener('change',e=>addFilesToQueue(e.target.files||[]));
  function blankManualScan(){return{version:4,provider:'manual-entry',model:null,manualEntry:true,name:'',age:null,ovr:null,roles:[],position:null,layout:'outfield',skills:{},playstyle:null,specialAbilities:[],confidence:{overall:0,text:0,numbers:0,roles:0,playstyle:0,specialAbilities:0},raw:{totals:{def:null,att:null,phys:null},model:null,warnings:[],providerResponseVersion:3},repairNotes:[],validation:{resolved:false,unresolvedChecks:[]}};}
  $('#manualAddPlayerBtn')?.addEventListener('click',()=>{persistCurrentQueueDraft();const scan=blankManualScan();state.scanQueue.push({id:++state.scanQueueSeq,fileName:'Manual player',dataUrl:null,status:'ready',statusText:'READY TO REVIEW · manual entry',scan,error:'',manual:true,reviewState:null,imageStored:false,autoAttempts:0,nextRetryAt:0});schedulePersistScanQueue();loadQueueReview(state.scanQueue.length-1);toast('Manual player added to review queue');});
  document.addEventListener('click',async e=>{const open=e.target.closest('[data-queue-open]');if(open&&!e.target.closest('[data-queue-remove]')){const i=Number(open.dataset.queueOpen);if(Number.isInteger(i))loadQueueReview(i);return;}const retry=e.target.closest('[data-queue-retry]');if(retry){e.stopPropagation();const i=Number(retry.dataset.queueRetry),item=state.scanQueue[i];if(item){cancelScanForItem(item.id);item.status='queued';item.statusText='QUEUED · Retry Scan requested';item.error='';item.scan=null;item.reviewState=null;item.autoAttempts=0;item.nextRetryAt=0;renderScanQueue();schedulePersistScanQueue();runScanQueue();}return;}const remove=e.target.closest('[data-queue-remove]');if(remove){e.stopPropagation();const i=Number(remove.dataset.queueRemove);if(!Number.isInteger(i)||!state.scanQueue[i])return;const removed=state.scanQueue[i],wasCurrent=i===state.scanQueueReviewIndex;cancelScanForItem(removed.id);state.scanQueue.splice(i,1);await queueImageDelete(removed.id);if(state.scanQueueReviewIndex>i)state.scanQueueReviewIndex--;else if(wasCurrent)clearScannerReview();renderScanQueue();schedulePersistScanQueue();if(wasCurrent){const n=reviewableIndices()[0];if(n!=null)loadQueueReview(n);}return;}});
  $('#nextQueuedPlayerBtn')?.addEventListener('click',()=>{persistCurrentQueueDraft();const n=nextReadyIndex();if(n>=0&&n!==state.scanQueueReviewIndex)loadQueueReview(n);});
  $('#rescanBtn')?.addEventListener('click',()=>{const item=currentQueueItem();if(!item||item.manual)return;persistCurrentQueueDraft();cancelScanForItem(item.id);item.status='queued';item.statusText='QUEUED · fresh rescan requested';item.scan=null;item.error='';item.reviewState=null;item.autoAttempts=0;item.nextRetryAt=0;state.scanQueueReviewIndex=-1;$('#scanReview').style.display='none';renderScanQueue();schedulePersistScanQueue();runScanQueue();});
  function scanFormData(){const name=$('#scanName').value.trim(),age=Number($('#scanAge').value),ovr=Number($('#scanOvr').value),position=$('#scanRole').value,roles=[position,$('#scanRole2').value,$('#scanRole3').value].filter((r,i,a)=>r&&a.indexOf(r)===i),relatedRoles=state.scanRelatedRoles.filter(r=>!roles.includes(r));return{name,age,ovr,position,roles,relatedRoles};}
  function validateScanForm(x){if(!state.scan)return'No player loaded';if(!x.name||!x.position)return'Check the name and primary role before saving';if(!Number.isFinite(x.age)||x.age<15||x.age>60)return'Check the player age before saving';if(!Number.isFinite(x.ovr)||x.ovr<1||x.ovr>520)return'Check the OVR before saving';if(!state.scan.manualEntry&&state.scan.layout==='gk'&&x.roles.some(r=>r!=='GK'))return'GK scans can only be saved as GK';if(!state.scan.manualEntry&&state.scan.layout!=='gk'&&x.roles.includes('GK'))return'Outfield scans cannot be saved as GK';const missing=scanRequiredSkills().filter(s=>!Number.isFinite(Number(state.scan.skills?.[s])));if(missing.length)return`Enter all ${scanRequiredSkills().length} skill values before saving (${missing.length} missing)`;refreshScanVerification();return'';}
  async function saveScanToKey(key=null){
    const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return false;}const unresolved=scanUnresolved(state.scan?.checks||{});if(unresolved.length&&!state.scan.manualEntry&&!state.scanManualVerified){const detail=unresolved.map(([name,c])=>`${name}${c.error==null?'':` (${Number(c.error).toFixed(1)} out)`}`).join(', ');const accepted=window.confirm(`Scanner verification still reports: ${detail}.\n\nIf you checked the screenshot and the visible values are correct, press OK to save them as manually verified.`);if(!accepted)return false;state.scanManualVerified=true;if($('#scanManualVerified'))$('#scanManualVerified').checked=true;refreshScanVerification();}
    const existing=key?await P.get(key):null;let roles=x.roles;if(existing)roles=P.mergeVisibleNaturalRoles(P.normaliseRoles(existing),x.roles,3);const relatedRoles=state.scanRelatedRoles.length?[...x.relatedRoles]:(existing?.relatedRoles||x.relatedRoles);const selectedPlaystyle=$('#scanPlaystyle').value,selectedLevel=playstyleTierValue();let playstyle=existing?P.mergePlaystyleState(existing.playstyle,selectedPlaystyle||P.playstyleName(existing)):P.mergePlaystyleState(null,selectedPlaystyle);if(selectedPlaystyle&&selectedLevel>=1)playstyle={...playstyle,level:selectedLevel};
    await P.save({...existing,...x,position:roles[0]||x.position,roles,relatedRoles,skills:state.scan.skills,playstyle,specialAbilities:[...state.scanAbilities],scanner:{version:SC.VERSION,provider:state.scan.provider||'manual-entry',model:state.scan.raw?.model||null,confidence:state.scan.confidence,checks:state.scan.checks,validation:{...state.scan.validation,manualVerified:!!state.scanManualVerified||!!state.scan.manualEntry,manualEntry:!!state.scan.manualEntry}}},key);return true;
  }
  async function completeQueueSave(name){const item=currentQueueItem();if(item){item.status='saved';item.statusText='SAVED';item.reviewState=null;item.nextRetryAt=0;if(item.imageStored){await queueImageDelete(item.id);item.imageStored=false;item.dataUrl=null;}}await renderDashboard();renderScanQueue();schedulePersistScanQueue();const n=nextReadyIndex(state.scanQueueReviewIndex);if(n>=0&&state.scanQueue[n]?.status==='ready'){loadQueueReview(n);toast(`${name} saved · next player ready`);}else{const queued=state.scanQueue.filter(x=>['queued','scanning','fallback','waiting'].includes(x.status)).length,failed=state.scanQueue.filter(x=>x.status==='error'||x.status==='failed').length;clearScannerReview();$('#scanProgressBar').style.width='100%';$('#scanPercent').textContent='100%';if(queued){$('#scanProgressText').textContent=`${name} saved · ${queued} scan${queued===1?'':'s'} still queued/retrying`;toast(`${name} saved · scanner queue continues`);}else if(failed){$('#scanProgressText').textContent=`${name} saved · ${failed} player${failed===1?'':'s'} need retry`;toast(`${name} saved · ${failed} need retry`,'err');}else{$('#scanProgressText').textContent='Review queue complete';toast(`${name} saved · queue complete`);}}}
  $('#saveScannedPlayer')?.addEventListener('click',async()=>{const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return;}const duplicate=(await P.all()).find(p=>String(p.name||'').trim().toLowerCase()===x.name.toLowerCase());if(duplicate){state.scanDuplicateKey=duplicate.key;state.scanPreservedRoles=P.normaliseRoles(duplicate).slice(3);if(!state.scanRelatedRoles.length)state.scanRelatedRoles=[...P.normaliseRelatedRoles(duplicate)];renderScanRelated();$('#scanSaveNote').innerHTML=`<b>${esc(x.name)}</b> already exists. <button class="inline-action-btn" id="updateExistingScanBtn">Update existing player</button>${state.scanPreservedRoles.length?`<br>Additional imported natural roles will be preserved: ${esc(state.scanPreservedRoles.join(', '))}.`:''}`;toast('Existing player found','err');return;}try{if(await saveScanToKey())await completeQueueSave(x.name);}catch(e){toast(e.message||'Save failed','err');}});
  document.addEventListener('click',async e=>{if(!e.target.closest('#updateExistingScanBtn'))return;if(!state.scanDuplicateKey)return;try{const name=$('#scanName').value.trim();if(await saveScanToKey(state.scanDuplicateKey)){state.playerKey=state.scanDuplicateKey;await completeQueueSave(name);}}catch(err){toast(err.message||'Update failed','err');}});
  $('#scanManualVerified')?.addEventListener('change',e=>{state.scanManualVerified=!!e.target.checked;refreshScanVerification();});
  $('#scanOvr')?.addEventListener('input',refreshScanVerification);
  $('#scanPlaystyle')?.addEventListener('change',e=>{const has=!!e.target.value;$('#scanPlaystyleLevel').disabled=!has;if(!has)$('#scanPlaystyleLevel').value='';persistCurrentQueueDraft();});
  $('#scanPlaystyleLevel')?.addEventListener('change',persistCurrentQueueDraft);
  ['#scanName','#scanAge'].forEach(id=>$(id)?.addEventListener('input',persistCurrentQueueDraft));
  ['#scanRole','#scanRole2','#scanRole3'].forEach(id=>$(id)?.addEventListener('change',e=>{if(state.scan?.manualEntry&&id==='#scanRole'){const isGk=e.target.value==='GK',newLayout=isGk?'gk':'outfield';if(state.scan.layout!==newLayout){state.scan.layout=newLayout;state.scan.skills={};renderScanSkills(state.scan);}$('#scanRole2').disabled=isGk;$('#scanRole3').disabled=isGk;if(isGk){$('#scanRole2').value='';$('#scanRole3').value='';}}const roles=[$('#scanRole').value,$('#scanRole2').value,$('#scanRole3').value].filter(Boolean);$('#scanPlaystyle').innerHTML=playstyleOptions(roles,$('#scanPlaystyle').value);state.scanRelatedRoles=state.scanRelatedRoles.filter(r=>!roles.includes(r));renderScanRelated();persistCurrentQueueDraft();refreshScanVerification();}));
  document.addEventListener('input',e=>{if(!e.target.matches('[data-scan-skill]')||!state.scan)return;const skill=e.target.dataset.scanSkill,value=Number(e.target.value);if(e.target.value===''||!Number.isFinite(value))delete state.scan.skills[skill];else state.scan.skills[skill]=value;refreshScanVerification();});


  // ---------- Gemini Scanner settings ----------
  async function renderGeminiScannerSettings(){const el=$('#geminiScannerApiKey');if(!el)return;const key=await SC.getApiKey();el.value=key;const status=$('#geminiScannerStatus');if(status)status.textContent=key?`API key saved on this device · Gemini 3.1 Flash Live scanner · HIGH thinking · core + playstyle + abilities. Test the connection before scanning.`:'Not configured yet. Create a Gemini API key in Google AI Studio, then test the Flash Live connection.';}
  $('#saveGeminiScannerKey')?.addEventListener('click',async()=>{const key=await SC.setApiKey($('#geminiScannerApiKey').value);$('#geminiScannerApiKey').value=key;$('#geminiScannerStatus').textContent=key?`API key saved on this device · Gemini 3.1 Flash Live · HIGH thinking.`:'API key cleared.';toast(key?'Gemini scanner key saved':'Gemini scanner key cleared');});
  $('#clearGeminiScannerKey')?.addEventListener('click',async()=>{await SC.clearApiKey();$('#geminiScannerApiKey').value='';$('#geminiScannerStatus').textContent='API key cleared. Scanner is disabled until a free Gemini key is added.';toast('Gemini scanner key cleared');});
  $('#testGeminiScannerKey')?.addEventListener('click',async()=>{const input=$('#geminiScannerApiKey').value.trim();if(input)await SC.setApiKey(input);const status=$('#geminiScannerStatus');status.textContent='Testing Gemini 3.1 Flash Live connection and loading visual indexes…';try{const h=await SC.health();status.textContent=`Connected · ${h.provider} · HIGH thinking · ${h.visualReferences} visual indexes · core + playstyle + level + Special Abilities`;toast('Gemini Flash Live scanner connected');}catch(err){status.textContent=err.message||'Connection failed';toast(err.message||'Connection failed','err');}});

  // ---------- Drill profile ----------
  async function renderMyDrills(){const {normal,master}=await DP.ensure();$('#normalDrillConfig').innerHTML=D.NORMAL_DRILLS.map(d=>{const s=normal.drills[d.drillId]||{unlocked:false,level:0};return `<div class="drill-config-row" data-drill-id="${esc(d.drillId)}"><div class="drill-config-main"><img src="${drillAsset(d.name,d.cat)}"><div><b>${esc(d.name)}</b><span>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</span></div></div><label class="unlock-control"><input type="checkbox" data-normal-unlock="${esc(d.drillId)}" ${s.unlocked?'checked':''}><i></i></label><select class="level-select" data-normal-level="${esc(d.drillId)}" ${s.unlocked?'':'disabled'}><option value="1" ${Number(s.level)===1?'selected':''}>Semi-pro +10%</option><option value="2" ${Number(s.level)===2?'selected':''}>Pro +20%</option><option value="3" ${Number(s.level)===3?'selected':''}>World-class +30%</option></select></div>`;}).join('');$('#masterStockConfig').innerHTML=D.MASTER_CAMPUS_DRILLS.map(d=>`<div class="master-card"><img src="${drillAsset(d.name,d.cat)}"><div class="master-card-copy"><span class="master-badge">MASTER +${esc(d.additionalTrainingEffectPercent)}%</span><b>${esc(d.name)}</b><small>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small><small>${esc(d.skills.join(' · '))}</small></div><label><span>CARDS OWNED</span><input type="number" min="0" step="1" inputmode="numeric" data-master-stock="${esc(d.drillId)}" value="${Math.max(0,Number(master.stock[d.drillId]||0))}"></label></div>`).join('');}
  document.addEventListener('change',async e=>{if(e.target.matches('[data-normal-unlock]')){const id=e.target.dataset.normalUnlock,row=e.target.closest('.drill-config-row'),sel=row.querySelector('[data-normal-level]'),unlocked=e.target.checked;sel.disabled=!unlocked;const level=unlocked?(Number(sel.value)||1):(Number(sel.value)||0);await DP.setNormal(id,{unlocked,level});clearTrainingSessionView();toast(`${row.querySelector('b').textContent} ${unlocked?'enabled':'locked'} · saved sessions cleared`);await updateTrainingIntel();}else if(e.target.matches('[data-normal-level]')){const id=e.target.dataset.normalLevel,row=e.target.closest('.drill-config-row'),unlock=row.querySelector('[data-normal-unlock]');await DP.setNormal(id,{unlocked:unlock.checked,level:Number(e.target.value)});clearTrainingSessionView();toast('Drill level saved · sessions cleared');}else if(e.target.matches('[data-master-stock]')){const q=await DP.setMasterStock(e.target.dataset.masterStock,e.target.value);e.target.value=q;clearTrainingSessionView();toast('Master stock saved · sessions cleared');await updateTrainingIntel();}});
  $('#resetDrillsBtn')?.addEventListener('click',async()=>{const b=$('#resetDrillsBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again';setTimeout(()=>{delete b.dataset.armed;b.textContent='Reset snapshot';},3000);return;}await DP.resetToCapturedSnapshot();clearTrainingSessionView();delete b.dataset.armed;b.textContent='Reset snapshot';toast('Captured drill snapshot restored · sessions cleared');await renderMyDrills();await updateTrainingIntel();});

  // ---------- Individual training ----------
  function clearTrainingSessionView(message=''){state.session=null;if($('#trainingResults'))$('#trainingResults').style.display='none';if(message&&$('#trainingStatus'))$('#trainingStatus').textContent=message;}
  function trainingSourceSnapshot(player,normal,master){return {playerUpdatedAt:String(player?.updatedAt||''),normalUpdatedAt:String(normal?.updatedAt||''),masterUpdatedAt:String(master?.updatedAt||'')};}
  function sameTrainingSource(a,b){return !!a&&a.playerUpdatedAt===b.playerUpdatedAt&&a.normalUpdatedAt===b.normalUpdatedAt&&a.masterUpdatedAt===b.masterUpdatedAt;}
  async function updateTrainingIntel(){const {normal,master}=await DP.ensure();const unlocked=Object.values(normal.drills).filter(x=>x.unlocked).length,totalMaster=Object.values(master.stock).reduce((a,b)=>a+Math.max(0,Number(b)||0),0);if($('#intelNormalCount'))$('#intelNormalCount').textContent=unlocked;if($('#intelMasterCount'))$('#intelMasterCount').textContent=totalMaster;}
  async function renderTrainingPicker(){await updateTrainingIntel();const players=await P.all();$('#trainingPlayer').innerHTML='<option value="">Select a player</option>'+players.map(p=>`<option value="${esc(p.key)}" ${p.key===state.trainingKey?'selected':''}>${esc(p.name)} · ${esc(rolesLabel(p))} · ${esc(p.ovr||'—')} OVR</option>`).join('');clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey&&!players.some(p=>p.key===state.trainingKey)){state.trainingKey='';return;}if(state.trainingKey)await restoreTrainingSession();}
  async function persistTraining(){if(!state.trainingKey||!state.session)return;await S.set(`training:session:${state.trainingKey}`,JSON.stringify({gameDataVersion:D.GAME_DATA_VERSION,session:state.session,savedAt:new Date().toISOString()}));}
  async function restoreTrainingSession(){clearTrainingSessionView();const key=`training:session:${state.trainingKey}`,raw=await S.get(key);if(!raw)return false;try{const x=JSON.parse(raw);if(x.gameDataVersion!==D.GAME_DATA_VERSION||x.session?.meta?.model!==T.MODEL_VERSION){await S.del(key);$('#trainingStatus').textContent='A previous recommendation used older training data. Build a fresh session.';return false;}const player=await P.get(state.trainingKey);if(!player){await S.del(key);return false;}const {normal,master}=await DP.ensure(),current=trainingSourceSnapshot(player,normal,master);if(!sameTrainingSource(x.session?.sourceSnapshot,current)){await S.del(key);$('#trainingStatus').textContent='Saved recommendation expired because the player or My Drills changed. Build a fresh session.';return false;}state.session=x.session;renderSession();$('#trainingStatus').textContent=state.session.completed?'Completed session restored.':'Saved recommendation restored.';return true;}catch(_){await S.del(key);$('#trainingStatus').textContent='Saved recommendation could not be restored. Build a fresh session.';return false;}}
  $('#trainingPlayer')?.addEventListener('change',async e=>{state.trainingKey=e.target.value;persistUiState();clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey)await restoreTrainingSession();});
  async function buildTraining(){if(!state.trainingKey){toast('Select a player first','err');return;}const player=await P.get(state.trainingKey);if(!player){toast('Player could not be loaded','err');return;}const {normal,master}=await DP.ensure();const result=T.buildIndividualSession({player,normalProfile:normal,masterStock:master,slots:6,mode:$('#trainingMode')?.value||'maxGrowth'});if(result.error==='missing-white-attributes'){$('#trainingStatus').textContent=`Cannot optimise reliably: ${result.missingAttributes.join(', ')} are missing from this player profile. Rescan or update the player first.`;$('#trainingResults').style.display='none';toast('Player profile is incomplete','err');return;}state.session={...result,playerKey:state.trainingKey,playerName:player.name,completed:false,stockDeducted:false,createdAt:new Date().toISOString(),sourceSnapshot:trainingSourceSnapshot(player,normal,master)};renderSession();await persistTraining();$('#trainingStatus').textContent=result.drills.length===6?`Built 6 slots from ${result.meta.normalCandidateCount} unlocked normal drills and ${result.meta.masterCandidateCount} owned Master drill types. Ranking favours the strongest drills that hit the player's weakest white/key attributes, with multi-white coverage rewarded; no exact gain is predicted.`:`Only ${result.drills.length}/6 legal slots could be built from your saved drill library.`;}
  $('#buildSessionBtn')?.addEventListener('click',buildTraining);$('#rebuildBtn')?.addEventListener('click',buildTraining);
  function masterProjectionHtml(r){const usage=Object.entries(r.meta?.masterUsage||{}).filter(([,n])=>Number(n)>0);if(!usage.length)return'';return `<div class="master-projection wide"><span>Master stock ${r.completed?'remaining':'projection'}</span><div>${usage.map(([id,n])=>{const name=D.MASTER_CAMPUS_DRILLS.find(d=>d.drillId===id)?.name||id,used=Number(n)||0,remaining=Number(r.meta?.remainingMasterStock?.[id]??0),owned=remaining+used;return `<section><b>${esc(name)}</b><small>${owned} owned at build</small><strong>${used} used</strong><em>${remaining} ${r.completed?'remaining now':'projected remaining'}</em></section>`;}).join('')}</div></div>`;}
  function renderSession(){const r=state.session;if(!r)return;$('#trainingResults').style.display='block';const priority=(r.meta?.priorityAttributes||[]);$('#priorityAttributes').innerHTML=priority.map((x,i)=>`<div class="priority-pill"><span>${i+1}</span><b>${esc(x.attribute)}</b><small>${esc(x.value)}</small></div>`).join('');const masterSeen={};$('#sessionList').innerHTML=r.drills?.length?r.drills.map((d,i)=>{let stockLine='';if(d.isMaster){masterSeen[d.drillId]=(masterSeen[d.drillId]||0)+1;const used=Number(r.meta?.masterUsage?.[d.drillId]||0),remaining=Number(r.meta?.remainingMasterStock?.[d.drillId]??0),owned=remaining+used;stockLine=`<div class="master-use-line">Card ${masterSeen[d.drillId]}/${used} · ${owned} owned · ${remaining} ${r.completed?'remaining':'left after this session'}</div>`;}const grey=(d.greyApplicableAttributes||[]);const greyLine=grey.length?`<div class="grey-info"><span>Grey / information only · zero score</span>${grey.map(a=>`<i>${esc(a)}</i>`).join('')}</div>`:'';return `<div class="drill-row ${d.isMaster?'master':''}"><div class="slot-no">${String(i+1).padStart(2,'0')}</div><img src="${drillAsset(d.name,d.cat)}"><div class="drill-copy"><div class="drill-title-line"><b>${esc(d.name)}</b>${d.isMaster?'<span class="master-badge small">MASTER</span>':''}</div><small>${d.isMaster?`+${d.effectPct}% Training Effect`:`${esc(d.levelName)} · +${d.effectPct}%`} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small>${stockLine}<div class="target-line"><span>Targets · ${d.targetedWhiteAttributes.length} white</span>${d.targetedWhiteAttributes.map(a=>`<i>${esc(a)}</i>`).join('')}</div>${greyLine}</div><span class="diff ${diffClass(d.diff)}">${esc(d.diff)}</span></div>`;}).join(''):'<div class="empty"><b>No legal session</b>Check My Drills and the selected player profile.</div>';$('#sessionSummary').innerHTML=`<div><span>Total condition</span><b>${fmt(r.meta?.totalCondition,2)}%</b></div><div><span>Total XP</span><b>${fmt(r.meta?.totalXp,0)}</b></div><div><span>Recommendation score</span><b>${fmt(r.meta?.totalUsefulScore,1)}</b></div>${masterProjectionHtml(r)}<p><strong>Top Eleven Tool calculation.</strong> The recommendation score rewards real drill strength and coverage of current white/key needs. Grey attributes have zero utility. It is not an exact predicted +X% gain.</p>`;$('#completeSessionBtn').disabled=!!r.completed;$('#completeSessionBtn').textContent=r.completed?'Session Completed ✓':'Mark Session Completed';$('#sessionCompleteNote').textContent=r.completed?(r.stockDeducted?'Master card stock has been deducted once; the remaining figures above are current.':'Completed. No Master cards were used.'):'Master figures above are projected only. Stock changes when you complete the whole session.';}
  $('#completeSessionBtn')?.addEventListener('click',async()=>{if(!state.session||state.session.completed)return;const usage=state.session.meta?.masterUsage||{};if(Object.values(usage).some(n=>Number(n)>0)&&!state.session.stockDeducted){const updatedMaster=await DP.deductMasterUsage(usage);state.session.stockDeducted=true;if(state.session.sourceSnapshot)state.session.sourceSnapshot.masterUpdatedAt=String(updatedMaster.updatedAt||'');}state.session.completed=true;state.session.completedAt=new Date().toISOString();await persistTraining();renderSession();await updateTrainingIntel();toast('Training session completed');});

  // ---------- Team normal-drill group planner ----------
  async function renderTeamTraining(){const normal=await DP.getNormal(),players=await P.all();$('#teamTrainingCards').innerHTML=Object.entries(D.TEAM_GROUPS).map(([key,g])=>{const r=TT.buildTeamSession(key,{normalProfile:normal,players});return `<div class="team-card"><div class="team-card-top"><img src="assets/icons/team.svg"><div><span>TOP ELEVEN TOOL CALCULATION</span><b>${esc(g.title)}</b></div></div>${r.error?`<div class="mini-note spaced">${r.error==='no-complete-players'?'No complete player profiles in this group.':esc(r.error)}</div>`:`<div class="team-mini-list">${r.drills.map(d=>`<div><b>${esc(d.name)}</b><span>${esc(d.diff)} · +${d.effectPct}% · ${d.usefulHits} useful player/skill hits</span></div>`).join('')}</div><small>${r.meta.selectedPlayerCount} actual players · ${fmt(r.meta.totalCondition,2)}% condition · score ${fmt(r.meta.totalUsefulScore,1)}</small>`}</div>`;}).join('');}
  function setTrainingTab(tab){state.trainingTab=tab;persistUiState();$$('[data-training-tab]').forEach(b=>b.classList.toggle('active',b.dataset.trainingTab===tab));$('#individualTrainingPanel').style.display=tab==='individual'?'block':'none';$('#teamTrainingPanel').style.display=tab==='team'?'block':'none';if(tab==='team')renderTeamTraining();}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-training-tab]');if(b)setTrainingTab(b.dataset.trainingTab);});

  // ---------- Team Plan ----------
  function clearPitch(){$('#formationPitch')?.querySelectorAll('.pitch-player').forEach(e=>e.remove());}
  function benchCard(p){return `<button class="bench-card" data-player-key="${esc(p.key)}"><b>${esc(p.name||'Player')}</b><span>${esc(rolesLabel(p))} · OVR ${esc(p.ovr||'—')}</span></button>`;}
  async function showTeamPlanEmpty(players){const count=players.length,needed=Math.max(0,11-count),empty=$('#formationEmpty');clearPitch();$('#formationName').textContent=count?'Squad incomplete':'No squad yet';$('#formationSummary').textContent=count?`Add ${needed} more player${needed===1?'':'s'} with complete role attributes.`:'Add players to unlock Team Plan.';$('#formationXIList').innerHTML='<div class="empty formation-list-empty">Build a complete XI to see assigned-role details.</div>';$('#formationBench').innerHTML=count?players.map(benchCard).join(''):'<div class="empty formation-list-empty"><b>No players added</b>Use Add Player to scan your first profile.</div>';if(empty){empty.style.display='grid';empty.innerHTML=`<img src="assets/icons/squad.svg" alt=""><b>${count}/11 PLAYERS</b><span>${count?`${needed} more required for a full XI.`:'Build your squad before choosing a team plan.'}</span><button class="btn primary compact" data-go="add-player">+ Add Player</button>`;}$('#tacticPlan').innerHTML='';$('#mentorStrip').innerHTML='';$('#mentorAlternatives').innerHTML='';$('#mentorReason').textContent='';}
  async function renderFormationFromPlan(plan){const players=await P.all();if(!plan||plan.error){await showTeamPlanEmpty(players);if(plan?.error)$('#formationSummary').textContent=plan.error;return;}const empty=$('#formationEmpty');if(empty)empty.style.display='none';$('#formationName').textContent=plan.formationName;const naturalCount=plan.starters.filter(x=>x.suitability==='NATURAL').length;$('#formationSummary').textContent=`${naturalCount}/11 natural assignments · global maximum role-score assignment · exact Build 30527 role geometry.`;clearPitch();const detailed=[];for(const s0 of plan.starters){const p=await P.get(s0.playerKey);if(!p)continue;const el=document.createElement('button');el.className='pitch-player';el.style.left=(s0.y/10)+'%';el.style.top=((1-s0.x/1000)*100)+'%';el.dataset.playerKey=p.key;el.dataset.assignedRole=s0.assignedRole;el.dataset.x=String(s0.x);el.dataset.y=String(s0.y);const last=String(p.name||'Player').trim().split(/\s+/).pop();el.innerHTML=`<span class="pitch-player-ring"><img src="${roleAsset(s0.assignedRole)}"></span><b>${esc(last)}</b><small>${esc(s0.assignedRole)} · ${fmt(s0.roleMean,1)}</small>`;$('#formationPitch').appendChild(el);const ps=P.normalisePlaystyle(p.playstyle),psName=P.playstyleName(p),psLevel=playstyleLevelLabel(ps);const abilities=(p.specialAbilities||[]);const weak=(s0.weakest||F.roleStats(p,s0.assignedRole)?.weakest||[]).slice(0,3);detailed.push(`<button class="xi-detail-card" data-player-key="${esc(p.key)}"><div class="xi-main"><img src="${roleAsset(s0.assignedRole)}"><div><b>${esc(p.name||'Player')}</b><span><strong>${esc(s0.assignedRole)}</strong> <i class="suitability ${String(s0.suitability).toLowerCase()}">${esc(s0.suitability)}</i> · X ${esc(s0.x)} / Y ${esc(s0.y)}</span></div><div class="role-score"><small>ROLE SCORE</small><strong>${fmt(s0.roleMean,1)}</strong></div></div><div class="xi-weak"><span>Weakest 3 role-key skills</span>${weak.map(x=>`<i>${esc(x.attribute)} ${esc(x.value)}</i>`).join('')}</div><div class="xi-tags">${psName?`<span class="${s0.playstyleFit?'fit':'no-fit'}">${esc(psName)} · ${esc(psLevel)} · ${s0.playstyleFit?'Role fit':'No role fit'}</span>`:'<span>No playstyle</span>'}${abilities.map(a=>`<span class="ability">${esc(a)}</span>`).join('')}</div></button>`);}$('#formationXIList').innerHTML=detailed.join('');const bench=[];for(const k of plan.bench||[]){const p=await P.get(k);if(p)bench.push(p);}$('#formationBenchTitle').textContent=`Bench · ${bench.length}`;$('#formationBench').innerHTML=bench.length?bench.map(benchCard).join(''):'<div class="empty formation-list-empty"><b>No substitutes</b>Every saved player is in the selected XI.</div>';}
  function renderTacticsFromPlan(plan){const t=plan?.tactics;if(!t){$('#tacticPlan').innerHTML='<div class="empty">Build the XI first.</div>';return;}const labels={passing:'Passing',shooting:'Shooting',focus:'Focus Passing',cross:'Cross Tendency',lost:'Possession Lost',won:'Possession Won',mentality:'Mentality',marking:'Marking',pressing:'Pressing',backLine:'Back Line',tackling:'Tackling'};$('#tacticPlan').innerHTML=TAC.DIMENSIONS.map(dim=>{const o=TAC.option(dim,t.values[dim]);return `<div class="plan-item"><span>${labels[dim]}</span><b>${esc(o?.label||t.values[dim])}</b><small>${esc(t.reasons?.[dim]||'')}</small></div>`;}).join('');$('#planDrainBadge').textContent=`${t.drainClass} drain · ${t.rawScore}/100`;$('#planDrainBadge').classList.add('active');$('#tacticFitNote').textContent=`Exact Build 30527 drain · ${esc(t.evaluatedCandidates??19440)} candidates evaluated for the locked mentality · Top Eleven Tool tactic fit ${(t.tacticFit*100).toFixed(1)}%. Drain is game/native arithmetic; fit is transparent companion logic.`;}
  function mentorRawText(row){const m=row.mentor;return `${m.tactic.id} ${JSON.stringify(m.tactic.current)} · ${m.attribute.id} ${JSON.stringify(m.attribute.current)} · ${m.signature.id} ${JSON.stringify(m.signature.current)}`;}function renderMentorFromPlan(plan){const r=plan?.mentor;if(!r?.best){$('#mentorStrip').innerHTML='';$('#mentorReason').textContent='';$('#mentorAlternatives').innerHTML='';return;}$('#mentorStrip').innerHTML=B.MENTORS.map(m=>{const row=r.all.find(x=>x.mentor.id===m.id);return `<div class="mentor ${m.id===r.best.mentor.id?'active':''}"><img src="assets/mentors/${m.asset}"><div class="mentor-copy"><b>${esc(m.displayName)}</b><span>${esc(m.title)} · L${m.level}${row?` · direct ${row.directTacticMatch}/3 · ${row.attributeCoverage} useful key hits`:''}</span></div></div>`;}).join('');const bm=r.best.mentor;$('#mentorReason').textContent=`${bm.displayName}: ${r.best.reason} LIVE raw effects — ${mentorRawText(r.best)}. Raw arrays are preserved and not reinterpreted.`;$('#mentorAlternatives').innerHTML=(r.alternatives||[]).slice(0,2).map((a,i)=>`<div class="mentor-alt"><span>Alternative ${i+1}</span><b>${esc(a.mentor.displayName)}</b><small>${esc(a.whyNot||a.reason||'Ranks below the selected mentor by the documented synergy tuple.')}</small><em>Direct ${a.directTacticMatch}/3 · ${a.attributeCoverage} useful key hits · L${a.mentor.level}</em><code>${esc(mentorRawText(a))}</code></div>`).join('');}
  async function renderTeamPlan(){const players=await P.all();if(players.length<11){await showTeamPlanEmpty(players);return;}let plan=await TP.getOrBuild({templateId:$('#planTemplate')?.value||null,mode:$('#planMode')?.value||'bestXI',minCondition:Number($('#planMinCondition')?.value||60)});if(plan.error){await showTeamPlanEmpty(players);return;}$('#planApproach').value=plan.approach||state.approach;$('#planDrain').value=plan.drainLimit||state.drainLimit;$('#planMode').value=plan.mode||'bestXI';$('#planTemplate').value=plan.formationTemplateId||'';$('#planMinCondition').value=plan.minCondition??60;if(!plan.tactics)plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value});await renderFormationFromPlan(plan);renderTacticsFromPlan(plan);renderMentorFromPlan(plan);}
  $('#buildTeamPlanBtn')?.addEventListener('click',async()=>{const r=await TP.buildFormation({templateId:$('#planTemplate').value||null,mode:$('#planMode').value,minCondition:Number($('#planMinCondition').value||60)});if(r.error){await showTeamPlanEmpty(await P.all());toast(r.error,'err');return;}const plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value});await renderFormationFromPlan(plan);renderTacticsFromPlan(plan);renderMentorFromPlan(plan);toast(`${plan.formationName} Team Plan built`);});
  async function updatePlanOnly(){const existing=await TP.load();if(!existing){toast('Build the XI first','err');return;}const before=existing.starters.map(x=>x.playerKey+'@'+x.assignedRole).join('|'),plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value}),after=plan.starters.map(x=>x.playerKey+'@'+x.assignedRole).join('|');renderTacticsFromPlan(plan);renderMentorFromPlan(plan);$('#teamPlanNote').textContent=before===after?'Tactics updated without reshuffling the XI.':'Squad changed, so the XI was rebuilt before tactics.';}
  $('#refreshPlanTacticsBtn')?.addEventListener('click',updatePlanOnly);$('#planApproach')?.addEventListener('change',updatePlanOnly);$('#planDrain')?.addEventListener('change',updatePlanOnly);

  // ---------- Specialists ----------
  function rankRow(x,i,label=''){const p=x.player;return `<div class="rank-card"><div class="rank-num">${label||i+1}</div><img src="${roleAsset(p.position)}"><div><div class="rank-name">${esc(p.name)}</div><div class="rank-meta">${esc(rolesLabel(p))} · Top Eleven Tool calculation${x.specialist?` · specialist ${x.specialist}`:''}</div></div><div class="rank-score">${fmt(x.score,0)}</div></div>`;}
  async function renderPlaymakers(){const players=await P.all();if(!players.length){$('#penaltyRank').innerHTML='<div class="empty"><b>No squad yet</b>Add players to rank specialists.</div>';$('#specialistRank').innerHTML='';return;}const r=R.rankPlaymakers(players);$('#penaltyRank').innerHTML=r.penalties.map((x,i)=>rankRow(x,i)).join('');const specs=[['C',r.corner],['FK',r.freeKick]].filter(x=>x[1]);$('#specialistRank').innerHTML=specs.map(x=>rankRow(x[1],0,x[0])).join('')+`<div class="mini-note">${esc(r.captainNote)}</div>`;}

  // ---------- Settings / startup ----------
  $('#clearDataBtn')?.addEventListener('click',async()=>{const b=$('#clearDataBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to confirm';setTimeout(()=>{delete b.dataset.armed;b.textContent='Clear all squad data';},3500);return;}for(const k of await S.list('player:'))await P.remove(k);for(const k of await S.list('training:session:'))await S.del(k);delete b.dataset.armed;b.textContent='Clear all squad data';toast('Squad data cleared');renderDashboard();});
  async function init(){
    restoreUiState();await P.migrate();await DP.ensure();resetScanner();await renderGeminiScannerSettings();setTrainingTab(state.trainingTab||'individual');await updateTrainingIntel();await restoreScanQueueState();
    let target=state.page||'dashboard';const existing=history.state;
    if(existing?.teTopEleven){target=existing.page||target;if(existing.playerKey!=null)state.playerKey=existing.playerKey;if(existing.trainingKey!=null)state.trainingKey=existing.trainingKey;if(existing.trainingTab)state.trainingTab=existing.trainingTab;history.replaceState(routeState(target),'');}
    else{history.replaceState(routeState('dashboard'),'');if(target!=='dashboard')history.pushState(routeState(target),'');}
    await applyPage(target,{scroll:false});if(target==='training')setTrainingTab(state.trainingTab||'individual');buildDrawer();
    const nav=performance.getEntriesByType?.('navigation')?.[0];if(nav?.type==='reload')setTimeout(()=>toast('✓ Successfully refreshed'),180);
  }
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.warn));
  init().catch(err=>{console.error(err);toast('App initialisation failed','err');});
})();
