(() => {
  const TE=window.TE5;const D=TE.Data,P=TE.Players,S=TE.Storage,DP=TE.DrillProfile,T=TE.Training,TT=TE.TeamTraining,SC=TE.Scanner,R=TE.Recommendations,F=TE.Formation,TP=TE.TeamPlan,TAC=TE.Tactics,M=TE.Mentor,B=TE.BibleData;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state={page:'dashboard',squadFilter:'ALL',search:'',squadRole:'',squadAgeMin:'',squadAgeMax:'',squadOvrMin:'',squadOvrMax:'',squadPlaystyle:'',squadAvailability:'',scan:null,scanAbilities:[],scanRelatedRoles:[],scanDuplicateKey:'',scanPreservedRoles:[],playerKey:'',profileAbilities:[],profileRelatedRoles:[],profilePreservedRoles:[],trainingKey:'',trainingTab:'individual',session:null,approach:'balanced',drainLimit:'Medium'};

  function toast(msg,type='ok'){const el=$('#toast');if(!el)return;el.textContent=msg;el.className='toast show'+(type==='err'?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800);}
  function roleAsset(pos){return `assets/roles/${P.roleGroup(pos)}.webp`;}
  function drillAsset(name='',cat=''){const n=String(name).toLowerCase(),c=String(cat).toLowerCase();if(/one[- ]?on[- ]?one|1v1|attacker|defender/.test(n))return'assets/drills/one-v-one.webp';if(/shoot|finish|free kick|penalt|set[- ]?piece|attack.*master/.test(n))return'assets/drills/shoot.webp';if(/pass|possession|piggy|video analysis|midfield.*master/.test(n))return'assets/drills/pass.webp';if(/head|aerial|cross|corner|press the play|defend.*master/.test(n))return'assets/drills/aerial.webp';if(/sprint|agility|fitness|stretch|warm|condition|shuttle|gym|fast|physical.*master/.test(n)||c.includes('physical'))return'assets/drills/agility.webp';return'assets/drills/dribble.webp';}
  function diffClass(d){return String(d||'').replace(/\s+/g,'');}
  function fmt(n,d=1){return Number.isFinite(Number(n))?Number(n).toFixed(d):'—';}
  function rolesLabel(p){return P.normaliseRoles(p).join(' / ');}

  async function go(page){if(!document.getElementById('page-'+page))page='dashboard';state.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));$$('.nav-btn[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===page));$('#moreBackdrop')?.classList.remove('open');window.scrollTo({top:0,behavior:'instant'});
    if(page==='dashboard')await renderDashboard();else if(page==='squad')await renderSquad();else if(page==='player')await renderPlayerProfile();else if(page==='training')await renderTrainingPicker();else if(page==='my-drills')await renderMyDrills();else if(page==='team-plan')await renderTeamPlan();else if(page==='playmakers')await renderPlaymakers();}
  document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){go(g.dataset.go);}});
  $('#moreBtn')?.addEventListener('click',()=>$('#moreBackdrop')?.classList.toggle('open'));
  $('#moreBackdrop')?.addEventListener('click',e=>{if(e.target===$('#moreBackdrop'))$('#moreBackdrop').classList.remove('open');});

  // ---------- Dashboard / Squad ----------
  async function renderDashboard(){const players=await P.all(),avg=players.length?players.reduce((a,p)=>a+Number(p.ovr||0),0)/players.length:0,high=players.length?Math.max(...players.map(p=>Number(p.ovr||0))):0;$('#dashboardStats').innerHTML=`<div class="stat lime"><b>${players.length}</b><span>Players</span></div><div class="stat"><b>${players.length?Math.round(avg):'—'}</b><span>Avg OVR</span></div><div class="stat"><b>${players.length?high:'—'}</b><span>Highest</span></div>`;$('#dashboardSquadLabel').textContent=players.length?`${players.length} saved player${players.length===1?'':'s'}`:'Add your first player';}
  function category(pos){if(pos==='GK')return'GK';if(['DL','DC','DR','DMC'].includes(pos))return'DEF';if(['ML','MC','MR'].includes(pos))return'MID';return'ATT';}
  async function renderSquad(){
    const players=await P.all(),counts={ALL:players.length,GK:0,DEF:0,MID:0,ATT:0};players.forEach(p=>counts[category(p.position)]++);
    $('#squadFilters').innerHTML=['ALL','GK','DEF','MID','ATT'].map(x=>`<button class="chip ${state.squadFilter===x?'active':''}" data-squad-filter="${x}">${x}<small>${counts[x]}</small></button>`).join('');
    $('#squadRoleFilter').innerHTML='<option value="">Any role</option>'+D.ALL_POSITIONS.map(r=>`<option value="${r}" ${state.squadRole===r?'selected':''}>${r}</option>`).join('');
    const knownPlaystyles=[...new Set(players.map(P.playstyleName).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    $('#squadPlaystyleFilter').innerHTML='<option value="">Any playstyle</option>'+knownPlaystyles.map(x=>`<option value="${esc(x)}" ${state.squadPlaystyle===x?'selected':''}>${esc(x)}</option>`).join('');
    const knownAvailability=[...new Set(players.map(p=>String(p.availability??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    $('#squadAvailabilityFilter').innerHTML='<option value="">Any availability</option><option value="__unknown" '+(state.squadAvailability==='__unknown'?'selected':'')+'>Not stored</option>'+knownAvailability.map(x=>`<option value="${esc(x)}" ${state.squadAvailability===x?'selected':''}>${esc(x)}</option>`).join('');
    $('#squadAgeMin').value=state.squadAgeMin;$('#squadAgeMax').value=state.squadAgeMax;$('#squadOvrMin').value=state.squadOvrMin;$('#squadOvrMax').value=state.squadOvrMax;
    const q=state.search.trim().toLowerCase(),minAge=Number(state.squadAgeMin),maxAge=Number(state.squadAgeMax),minOvr=Number(state.squadOvrMin),maxOvr=Number(state.squadOvrMax);
    const filtered=players.filter(p=>{
      const roles=P.normaliseRoles(p),ps=P.playstyleName(p),availability=String(p.availability??'').trim(),age=Number(p.age),ovr=Number(p.ovr);
      if(state.squadFilter!=='ALL'&&category(p.position)!==state.squadFilter)return false;
      if(state.squadRole&&!roles.includes(state.squadRole))return false;
      if(state.squadPlaystyle&&ps!==state.squadPlaystyle)return false;
      if(state.squadAvailability==='__unknown'&&availability)return false;
      if(state.squadAvailability&&state.squadAvailability!=='__unknown'&&availability!==state.squadAvailability)return false;
      if(state.squadAgeMin!==''&&(!Number.isFinite(age)||age<minAge))return false;
      if(state.squadAgeMax!==''&&(!Number.isFinite(age)||age>maxAge))return false;
      if(state.squadOvrMin!==''&&(!Number.isFinite(ovr)||ovr<minOvr))return false;
      if(state.squadOvrMax!==''&&(!Number.isFinite(ovr)||ovr>maxOvr))return false;
      if(q&&!String(p.name||'').toLowerCase().includes(q)&&!rolesLabel(p).toLowerCase().includes(q)&&!ps.toLowerCase().includes(q))return false;
      return true;
    });
    $('#squadList').innerHTML=filtered.length?filtered.map((p,i)=>`<button class="player-row" data-player-key="${esc(p.key)}"><div class="squad-rank">${i+1}</div><img class="player-art" src="${roleAsset(p.position)}"><div class="player-copy"><div class="player-name">${esc(p.name||'Unnamed Player')}</div><div class="player-meta"><span class="pos-tag">${esc(p.position||'?')}</span>${esc(P.normaliseRoles(p).slice(1).join(' · '))}${p.age?` · Age ${esc(p.age)}`:''}${psLabel(p)?` · ${esc(psLabel(p))}`:''}</div></div><div class="ovr"><span>OVR</span><b>${esc(p.ovr||'—')}</b></div><div class="row-arrow">›</div></button>`).join(''):`<div class="empty"><b>No players here</b>${players.length?'Change the search or filters.':'Add your first player with Scanner v2.'}</div>`;
  }
  function psLabel(p){return P.playstyleName(p)||'';}
  $('#squadSearch')?.addEventListener('input',e=>{state.search=e.target.value;renderSquad();});
  $('#clearSearchBtn')?.addEventListener('click',()=>{$('#squadSearch').value='';state.search='';renderSquad();});
  $('#squadRoleFilter')?.addEventListener('change',e=>{state.squadRole=e.target.value;renderSquad();});
  $('#squadPlaystyleFilter')?.addEventListener('change',e=>{state.squadPlaystyle=e.target.value;renderSquad();});
  $('#squadAvailabilityFilter')?.addEventListener('change',e=>{state.squadAvailability=e.target.value;renderSquad();});
  for(const [id,key] of [['#squadAgeMin','squadAgeMin'],['#squadAgeMax','squadAgeMax'],['#squadOvrMin','squadOvrMin'],['#squadOvrMax','squadOvrMax']])$(id)?.addEventListener('input',e=>{state[key]=e.target.value;renderSquad();});
  $('#clearSquadFiltersBtn')?.addEventListener('click',()=>{Object.assign(state,{squadFilter:'ALL',search:'',squadRole:'',squadAgeMin:'',squadAgeMax:'',squadOvrMin:'',squadOvrMax:'',squadPlaystyle:'',squadAvailability:''});$('#squadSearch').value='';renderSquad();});
  $('#refreshSquadBtn')?.addEventListener('click',renderSquad);
  document.addEventListener('click',e=>{const f=e.target.closest('[data-squad-filter]');if(f){state.squadFilter=f.dataset.squadFilter;renderSquad();}const row=e.target.closest('[data-player-key]');if(row){state.playerKey=row.dataset.playerKey;go('player');}});

  // ---------- Player profile ----------
  function profileGroups(player){return player.position==='GK'?D.GROUPS_GK:D.GROUPS_OUTFIELD;}
  function weakestKeySkills(player,limit=6){const white=new Set(D.whiteSkillsForRoles(P.normaliseRoles(player)));return Object.entries(player.skills||{}).filter(([name,v])=>white.has(name)&&Number.isFinite(Number(v))).sort((a,b)=>Number(a[1])-Number(b[1])||a[0].localeCompare(b[0])).slice(0,limit);}
  function renderProfileAbilities(){$('#profileAbilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button type="button" class="chip profile-ability-chip ${state.profileAbilities.includes(a)?'active':''}" data-profile-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  function renderProfileRelated(){const natural=new Set([...currentEditRoles(),...state.profilePreservedRoles]);state.profileRelatedRoles=state.profileRelatedRoles.filter(r=>!natural.has(r));$('#profileRelatedPicker').innerHTML=D.ALL_POSITIONS.filter(a=>!natural.has(a)).map(a=>`<button type="button" class="chip ${state.profileRelatedRoles.includes(a)?'active':''}" data-profile-related="${a}">${a}</button>`).join('');}
  function fillRoleSelect(id,value,allowBlank=false,allowed=D.ALL_POSITIONS){$(id).innerHTML=(allowBlank?'<option value="">None</option>':'')+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');}
  function playstyleOptions(roles,current){const allowed=D.playstylesForRoles(roles),currentName=typeof current==='object'?P.playstyleName({playstyle:current}):String(current||'');const legacy=currentName&&!allowed.includes(currentName)?`<option value="${esc(currentName)}" selected>${esc(currentName)} (preserved)</option>`:'';return '<option value="">No playstyle</option>'+legacy+allowed.map(x=>`<option value="${esc(x)}" ${x===currentName?'selected':''}>${esc(x)}</option>`).join('');}
  function playstyleLevelLabel(ps){
    if(!ps?.type)return 'No playstyle';
    const level=Number(ps.level)||0;
    if(level===0)return 'Level not captured';
    return B.PLAYSTYLE_LEVELS.find(x=>x.id===level)?.name||`Level ${level}`;
  }
  function renderPlaystyleState(p){
    const ps=P.normalisePlaystyle(p.playstyle),name=P.playstyleName(p);
    const rows=[];
    rows.push(['Playstyle',name||'None']);
    rows.push(['Level',playstyleLevelLabel(ps)]);
    if(ps.points!=null)rows.push(['Points',ps.points]);
    if(ps.nextLevelProgress!=null)rows.push(['Next-level progress',ps.nextLevelProgress]);
    if(ps.nextLevelPrice!=null)rows.push(['Next-level price',ps.nextLevelPrice]);
    if(ps.isTrainingNextLevel!=null)rows.push(['Training next level',ps.isTrainingNextLevel?'Yes':'No']);
    if(ps.isNextLevelAvailable!=null)rows.push(['Next level available',ps.isNextLevelAvailable?'Yes':'No']);
    if(ps.boost!=null)rows.push(['Captured boost',Array.isArray(ps.boost)?JSON.stringify(ps.boost):ps.boost]);
    $('#profilePlaystyleState').innerHTML=rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');
    $('#profilePlaystyleCard').style.display=name||rows.length>2?'block':'none';
  }
  async function renderPlayerProfile(){
    if(!state.playerKey){go('squad');return;}
    const p=await P.get(state.playerKey);if(!p){toast('Player could not be loaded','err');state.playerKey='';go('squad');return;}
    const roles=P.normaliseRoles(p),related=P.normaliseRelatedRoles(p),white=new Set(D.whiteSkillsForRoles(roles));
    $('#profileRoleArt').src=roleAsset(p.position);$('#profileRoleArt').alt=`${P.roleGroup(p.position).toUpperCase()} role artwork`;
    $('#profileName').textContent=p.name||'Player';$('#profileOvr').textContent=p.ovr||'—';$('#profileEyebrow').textContent=`${p.position} · Player Profile`;
    $('#profileMeta').innerHTML=`${roles.map(r=>`<span>${esc(r)}</span>`).join('')}${related.length?`<span>Related ${esc(related.join('/'))}</span>`:''}${p.age?`<span>Age ${esc(p.age)}</span>`:''}`;
    const badges=[],ps=P.playstyleName(p);if(ps)badges.push(`<div class="profile-badge"><strong>PLAYSTYLE</strong> · ${esc(ps)} · ${esc(playstyleLevelLabel(p.playstyle))}</div>`);for(const a of p.specialAbilities||[])badges.push(`<div class="profile-badge gold"><strong>ABILITY</strong> · ${esc(a)}</div>`);if(p.scanner?.version)badges.push(`<div class="profile-badge"><strong>SCAN</strong> · v${esc(p.scanner.version)}${p.scanner.confidence?.overall?' · '+Math.round(p.scanner.confidence.overall*100)+'%':''}</div>`);$('#profileBadges').innerHTML=badges.join('')||'<div class="profile-badge">No playstyle or special ability selected</div>';
    const facts=[];if(p.condition!=null&&p.condition!=='')facts.push(['Condition',`${esc(p.condition)}%`]);if(p.availability!=null&&p.availability!=='')facts.push(['Availability',esc(p.availability)]);if(p.morale!=null&&p.morale!=='')facts.push(['Morale',esc(p.morale)]);$('#profileFacts').innerHTML=facts.map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('');$('#profileFacts').style.display=facts.length?'grid':'none';
    renderPlaystyleState(p);
    const weak=weakestKeySkills(p);$('#profileKeySkills').innerHTML=weak.length?weak.map(([name,v])=>`<div class="profile-key"><span>${esc(name)}</span><div class="track"><i style="width:${Math.max(3,Math.min(100,Number(v)/2.5))}%"></i></div><b>${esc(v)}</b></div>`).join(''):'<div class="empty"><b>No skill data</b>Update this player from a scan to populate attributes.</div>';
    $('#profileRoleScores').innerHTML=roles.map(role=>{const rs=F.roleStats(p,role);return rs?`<div class="profile-key"><span>${role} · Top Eleven Tool Role Score</span><div class="track"><i style="width:${Math.min(100,rs.roleMean/2.5)}%"></i></div><b>${fmt(rs.roleMean,1)}</b><small>Weakest 3: ${esc(rs.weakest.map(x=>`${x.attribute} ${x.value}`).join(' · '))}</small></div>`:'';}).join('')||'<div class="empty">Role score needs complete visible attributes.</div>';
    $('#profileSkills').innerHTML=Object.entries(profileGroups(p)).map(([group,names])=>`<div class="skill-group"><h3>${esc(group)}</h3><div class="skill-grid">${names.map(name=>`<div class="skill ${white.has(name)?'white':'grey'}"><span>${esc(name)}</span><b>${esc(p.skills?.[name]??'—')}</b></div>`).join('')}</div></div>`).join('');
    $('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';$('#profileEditNote').textContent=p.legacyRoles?.length?`Legacy roles preserved but not selectable: ${p.legacyRoles.join(', ')}`:'';
  }
  async function openProfileEdit(){
    const p=await P.get(state.playerKey);if(!p)return;const roles=P.normaliseRoles(p);
    state.profileAbilities=[...(p.specialAbilities||[])];state.profileRelatedRoles=[...P.normaliseRelatedRoles(p)];state.profilePreservedRoles=roles.slice(3);
    $('#profileEditName').value=p.name||'';$('#profileEditAge').value=p.age??'';$('#profileEditOvr').value=p.ovr??'';
    const allowed=p.position==='GK'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK');
    fillRoleSelect('#profileEditRole1',roles[0]||p.position,false,allowed);fillRoleSelect('#profileEditRole2',roles[1]||'',true,p.position==='GK'?[]:allowed);fillRoleSelect('#profileEditRole3',roles[2]||'',true,p.position==='GK'?[]:allowed);
    $('#profileEditRole2').disabled=p.position==='GK';$('#profileEditRole3').disabled=p.position==='GK';$('#profileEditPlaystyle').innerHTML=playstyleOptions(roles,p.playstyle);
    $('#profilePreservedRolesNote').textContent=state.profilePreservedRoles.length?`Additional imported natural roles preserved: ${state.profilePreservedRoles.join(', ')}. This three-role editor will not delete them.`:'';
    renderProfileAbilities();renderProfileRelated();$('#profileEditCard').style.display='block';$('#profileEditBtn').textContent='Editing';$('#profileEditCard').scrollIntoView({behavior:'smooth',block:'start'});
  }
  function currentEditRoles(){return [$('#profileEditRole1')?.value,$('#profileEditRole2')?.value,$('#profileEditRole3')?.value].filter((r,i,a)=>r&&a.indexOf(r)===i);}
  ['#profileEditRole1','#profileEditRole2','#profileEditRole3'].forEach(id=>$(id)?.addEventListener('change',()=>{const allNatural=[...new Set([...currentEditRoles(),...state.profilePreservedRoles])];$('#profileEditPlaystyle').innerHTML=playstyleOptions(allNatural,$('#profileEditPlaystyle').value);renderProfileRelated();}));
  $('#profileBackBtn')?.addEventListener('click',()=>go('squad'));$('#profileTrainBtn')?.addEventListener('click',()=>{if(state.playerKey){state.trainingKey=state.playerKey;go('training');}});$('#profileEditBtn')?.addEventListener('click',openProfileEdit);$('#profileCancelEditBtn')?.addEventListener('click',()=>{$('#profileEditCard').style.display='none';$('#profileEditBtn').textContent='Edit Player';});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-ability]');if(b){const a=b.dataset.profileAbility;state.profileAbilities=state.profileAbilities.includes(a)?state.profileAbilities.filter(x=>x!==a):[...state.profileAbilities,a];renderProfileAbilities();return;}const rr=e.target.closest('[data-profile-related]');if(rr){const r=rr.dataset.profileRelated;state.profileRelatedRoles=state.profileRelatedRoles.includes(r)?state.profileRelatedRoles.filter(x=>x!==r):[...state.profileRelatedRoles,r];renderProfileRelated();}});
  $('#profileSaveBtn')?.addEventListener('click',async()=>{
    const existing=await P.get(state.playerKey);if(!existing)return;
    const name=$('#profileEditName').value.trim(),age=Number($('#profileEditAge').value),ovr=Number($('#profileEditOvr').value),primary=$('#profileEditRole1').value;
    if(!name||!primary){toast('Name and primary role are required','err');return;}if(!Number.isFinite(age)||age<15||age>60){toast('Age must be between 15 and 60','err');return;}if(!Number.isFinite(ovr)||ovr<1||ovr>520){toast('OVR must be between 1 and 520','err');return;}
    const duplicate=(await P.all()).find(x=>x.key!==state.playerKey&&String(x.name||'').trim().toLowerCase()===name.toLowerCase());if(duplicate){toast('Another player already uses that name','err');return;}
    const roles=P.mergeVisibleNaturalRoles(P.normaliseRoles(existing),currentEditRoles(),3),related=state.profileRelatedRoles.filter(r=>!roles.includes(r));
    const playstyle=P.mergePlaystyleState(existing.playstyle,$('#profileEditPlaystyle').value);
    await P.save({...existing,name,age,ovr,position:roles[0]||primary,roles,relatedRoles:related,playstyle,specialAbilities:[...state.profileAbilities]},state.playerKey);
    toast('Player updated');await renderDashboard();await renderPlayerProfile();
  });
  $('#profileDeleteBtn')?.addEventListener('click',async()=>{const b=$('#profileDeleteBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to delete';$('#profileEditNote').textContent='This permanently removes the player and their saved training session.';setTimeout(()=>{delete b.dataset.armed;b.textContent='Delete Player';},3500);return;}const p=await P.get(state.playerKey);await P.remove(state.playerKey);state.playerKey='';state.trainingKey='';delete b.dataset.armed;b.textContent='Delete Player';toast(`${p?.name||'Player'} deleted`);await renderDashboard();go('squad');});

  // ---------- Scanner v2 ----------
  function resetScanner(){state.scan=null;state.scanAbilities=[];state.scanRelatedRoles=[];state.scanPreservedRoles=[];state.scanDuplicateKey='';state.scanManualVerified=false;$('#scanFile').value='';$('#scanWindow').className='scan-window';$('#scanPreview').removeAttribute('src');$('#scanReview').style.display='none';$('#scanProgressBar').style.width='0%';$('#scanProgressText').textContent='Waiting for screenshot';$('#scanPercent').textContent='0%';$('#scanSaveNote').textContent='';if($('#scanManualVerified'))$('#scanManualVerified').checked=false;if($('#scanManualVerify'))$('#scanManualVerify').style.display='none';}
  $('#rescanBtn')?.addEventListener('click',resetScanner);
  function progress(p){const pct=Math.round((p.progress||0)*100);$('#scanProgressBar').style.width=pct+'%';$('#scanProgressText').textContent=p.label||'Scanning';$('#scanPercent').textContent=pct+'%';}
  function confidenceBadge(v){const n=Math.round((v||0)*100);return `<span class="chip active">${n}% confidence</span>`;}
  function renderAbilityPicker(){$('#abilityPicker').innerHTML=D.SPECIAL_ABILITIES.map(a=>`<button class="chip ${state.scanAbilities.includes(a)?'active':''}" data-ability="${esc(a)}">${esc(a)}</button>`).join('');}
  function renderScanRelated(){const natural=new Set([$('#scanRole')?.value,$('#scanRole2')?.value,$('#scanRole3')?.value].filter(Boolean));$('#scanRelatedPicker').innerHTML=D.ALL_POSITIONS.filter(r=>!natural.has(r)).map(r=>`<button type="button" class="chip ${state.scanRelatedRoles.includes(r)?'active':''}" data-scan-related="${r}">${r}</button>`).join('');}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-ability]');if(b){const a=b.dataset.ability;if(state.scanAbilities.includes(a))state.scanAbilities=state.scanAbilities.filter(x=>x!==a);else state.scanAbilities.push(a);renderAbilityPicker();return;}const rr=e.target.closest('[data-scan-related]');if(rr){const r=rr.dataset.scanRelated;state.scanRelatedRoles=state.scanRelatedRoles.includes(r)?state.scanRelatedRoles.filter(x=>x!==r):[...state.scanRelatedRoles,r];renderScanRelated();}});
  function currentScanChecks(ovrValue){
    if(!state.scan)return{};
    const skills=state.scan.skills||{},totals=state.scan.raw?.totals||{},checks={};
    if(state.scan.layout==='gk'){
      checks.goalkeeping=SC.checkAggregate(D.GK_SKILLS.map(s=>Number(skills[s])),totals.att);
      checks.physical=SC.checkAggregate(D.GK_PHYSICAL.map(s=>Number(skills[s])),totals.phys);
    }else{
      checks.defence=SC.checkAggregate(D.GROUPS_OUTFIELD.Defence.map(s=>Number(skills[s])),totals.def);
      checks.attack=SC.checkAggregate(D.GROUPS_OUTFIELD.Attack.map(s=>Number(skills[s])),totals.att);
      checks.physical=SC.checkAggregate(D.GROUPS_OUTFIELD.Physical.map(s=>Number(skills[s])),totals.phys);
    }
    const vals=Object.values(skills).map(Number).filter(Number.isFinite),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,ovr=Number(ovrValue);
    checks.ovr={average:avg,error:Number.isFinite(ovr)?Math.abs(avg-ovr):null,ok:Number.isFinite(ovr)&&Math.abs(avg-ovr)<=1.5};
    return checks;
  }
  function scanUnresolved(checks){return Object.entries(checks||{}).filter(([,c])=>!c.ok);}
  function refreshScanVerification(){
    if(!state.scan)return true;
    const checks=currentScanChecks($('#scanOvr').value);state.scan.checks=checks;
    const unresolved=scanUnresolved(checks);state.scan.validation={resolved:unresolved.length===0,unresolvedChecks:unresolved.map(([name,c])=>({name,error:c.error,average:c.average}))};
    $('#scanChecks').innerHTML=Object.entries(checks).map(([name,c])=>`<div class="verify ${c.ok?'ok':'warn'}"><strong>${c.ok?'✓':'!'} ${esc(name)}</strong><span>${c.error==null?'No aggregate available':`difference ${Number(c.error).toFixed(1)}`}</span></div>`).join('');
    const manual=!!state.scanManualVerified;
    const manualBox=$('#scanManualVerify');if(manualBox)manualBox.style.display=unresolved.length?'block':'none';
    const save=$('#saveScannedPlayer');if(save)save.disabled=false;
    if(unresolved.length){
      const detail=unresolved.map(([name,c])=>`${name}${c.error==null?'':` (${Number(c.error).toFixed(1)} out)`}`).join(', ');
      $('#scanSaveNote').innerHTML=manual
        ?`<b>Manual verification accepted.</b> Remaining scanner mismatch: ${esc(detail)}. Your reviewed values will be saved and marked as manually verified.`
        :`<b>Verification required.</b> Scanner v2 still sees: ${esc(detail)}. Correct any wrong values. If the values on screen now exactly match the Top Eleven screenshot, tick <b>I checked the screenshot manually</b> to save your corrected values.`;
    }else{
      const notes=(state.scan.repairNotes||[]).join(' · ');
      $('#scanSaveNote').textContent=notes||'All numerical cross-checks pass. Review the player details, then save.';
    }
    return unresolved.length===0;
  }
  function renderScanSkills(scan){const groups=scan.layout==='gk'?D.GROUPS_GK:D.GROUPS_OUTFIELD;$('#scanSkills').innerHTML=Object.entries(groups).map(([g,names])=>`<div class="skill-group"><h3>${esc(g)}</h3><div class="skill-grid">${names.map(s=>`<label class="skill scan-skill"><span>${esc(s)}</span><input class="scan-skill-input" type="number" min="0" max="520" inputmode="numeric" data-scan-skill="${esc(s)}" value="${esc(scan.skills[s]??'')}"></label>`).join('')}</div></div>`).join('');}
  function populateScanReview(scan){state.scan=scan;state.scanDuplicateKey='';state.scanRelatedRoles=[];state.scanPreservedRoles=[];$('#scanReview').style.display='block';$('#scanConfidence').innerHTML=confidenceBadge(scan.confidence.overall);$('#scanName').value=scan.name||'';$('#scanAge').value=scan.age??'';$('#scanOvr').value=scan.ovr??'';const allowed=scan.layout==='gk'?['GK']:D.ALL_POSITIONS.filter(r=>r!=='GK');const fill=(id,value,label)=>{$(id).innerHTML=`<option value="">${label}</option>`+allowed.map(r=>`<option value="${r}" ${r===value?'selected':''}>${r}</option>`).join('');};fill('#scanRole',scan.roles?.[0]||scan.position,'Choose role');fill('#scanRole2',scan.roles?.[1]||'','None');fill('#scanRole3',scan.roles?.[2]||'','None');$('#scanRole2').disabled=scan.layout==='gk';$('#scanRole3').disabled=scan.layout==='gk';$('#detectedRoles').innerHTML=(scan.roles||[]).map((r,i)=>`<span class="chip ${i===0?'active':''}">${esc(r)}${i===0?' · primary':''}</span>`).join('')||( '<span class="mini-note">Role needs review.</span>');$('#scanPlaystyle').innerHTML=playstyleOptions(scan.roles||[scan.position],'');renderScanRelated();renderAbilityPicker();renderScanSkills(scan);refreshScanVerification();}
  $('#scanFile')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const url=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});$('#scanPreview').src=url;$('#scanWindow').classList.add('has-image','scanning');$('#scanReview').style.display='none';progress({progress:.02,label:'Preparing scanner'});try{const scan=await SC.scan(url,progress);$('#scanWindow').classList.remove('scanning');populateScanReview(scan);toast(`Scan complete · ${Math.round(scan.confidence.overall*100)}% confidence`);}catch(err){$('#scanWindow').classList.remove('scanning');$('#scanProgressText').textContent='Scan failed';toast(err.message||'Scanner failed','err');console.error(err);}});
  function scanFormData(){const name=$('#scanName').value.trim(),age=Number($('#scanAge').value),ovr=Number($('#scanOvr').value),position=$('#scanRole').value,roles=[position,$('#scanRole2').value,$('#scanRole3').value].filter((r,i,a)=>r&&a.indexOf(r)===i);const relatedRoles=state.scanRelatedRoles.filter(r=>!roles.includes(r));return{name,age,ovr,position,roles,relatedRoles};}
  function validateScanForm(x){if(!state.scan)return'No scan loaded';if(!x.name||!x.position)return'Check the name and primary role before saving';if(!Number.isFinite(x.age)||x.age<15||x.age>60)return'Check the player age before saving';if(!Number.isFinite(x.ovr)||x.ovr<1||x.ovr>520)return'Check the OVR before saving';if(state.scan.layout==='gk'&&x.roles.some(r=>r!=='GK'))return'GK scans can only be saved as GK';if(state.scan.layout!=='gk'&&x.roles.includes('GK'))return'Outfield scans cannot be saved as GK';refreshScanVerification();return'';}
  async function saveScanToKey(key=null){const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return false;}const unresolved=scanUnresolved(state.scan?.checks||{});if(unresolved.length&&!state.scanManualVerified){const detail=unresolved.map(([name,c])=>`${name}${c.error==null?'':` (${Number(c.error).toFixed(1)} out)`}`).join(', ');const accepted=window.confirm(`Scanner reconciliation still reports: ${detail}.\n\nIf you have checked the player screenshot and the visible OVR/skills are correct, press OK to save these values as manually verified.`);if(!accepted)return false;state.scanManualVerified=true;if($('#scanManualVerified'))$('#scanManualVerified').checked=true;refreshScanVerification();}const existing=key?await P.get(key):null;let roles=x.roles;if(existing)roles=P.mergeVisibleNaturalRoles(P.normaliseRoles(existing),x.roles,3);const relatedRoles=state.scanRelatedRoles.length?[...x.relatedRoles]:(existing?.relatedRoles||x.relatedRoles);const selectedPlaystyle=$('#scanPlaystyle').value;const playstyle=existing?P.mergePlaystyleState(existing.playstyle,selectedPlaystyle||P.playstyleName(existing)):P.mergePlaystyleState(null,selectedPlaystyle);await P.save({...existing,...x,position:roles[0]||x.position,roles,relatedRoles,skills:state.scan.skills,playstyle,specialAbilities:state.scanAbilities.length?[...state.scanAbilities]:(existing?.specialAbilities||[]),scanner:{version:2,confidence:state.scan.confidence,checks:state.scan.checks,validation:{...state.scan.validation,manualVerified:!!state.scanManualVerified}}},key);return true;}
  $('#saveScannedPlayer')?.addEventListener('click',async()=>{const x=scanFormData(),err=validateScanForm(x);if(err){toast(err,'err');return;}const duplicate=(await P.all()).find(p=>String(p.name||'').trim().toLowerCase()===x.name.toLowerCase());if(duplicate){state.scanDuplicateKey=duplicate.key;state.scanPreservedRoles=P.normaliseRoles(duplicate).slice(3);if(!state.scanRelatedRoles.length)state.scanRelatedRoles=[...P.normaliseRelatedRoles(duplicate)];renderScanRelated();$('#scanSaveNote').innerHTML=`<b>${esc(x.name)}</b> already exists. <button class="inline-action-btn" id="updateExistingScanBtn">Update existing player</button>${state.scanPreservedRoles.length?`<br>Additional imported natural roles will be preserved: ${esc(state.scanPreservedRoles.join(', '))}.`:''}`;toast('Existing player found','err');return;}try{if(await saveScanToKey()){toast(`${x.name} saved to My Squad`);resetScanner();await renderDashboard();go('squad');}}catch(e){toast(e.message||'Save failed','err');}});
  document.addEventListener('click',async e=>{if(!e.target.closest('#updateExistingScanBtn'))return;if(!state.scanDuplicateKey)return;try{const name=$('#scanName').value.trim();if(await saveScanToKey(state.scanDuplicateKey)){toast(`${name} updated from scan`);state.playerKey=state.scanDuplicateKey;resetScanner();await renderDashboard();go('player');}}catch(err){toast(err.message||'Update failed','err');}});
  $('#scanManualVerified')?.addEventListener('change',e=>{state.scanManualVerified=!!e.target.checked;refreshScanVerification();});
  $('#scanOvr')?.addEventListener('input',refreshScanVerification);
  ['#scanRole','#scanRole2','#scanRole3'].forEach(id=>$(id)?.addEventListener('change',()=>{const roles=[$('#scanRole').value,$('#scanRole2').value,$('#scanRole3').value].filter(Boolean);$('#scanPlaystyle').innerHTML=playstyleOptions(roles,$('#scanPlaystyle').value);state.scanRelatedRoles=state.scanRelatedRoles.filter(r=>!roles.includes(r));renderScanRelated();}));
  document.addEventListener('input',e=>{if(!e.target.matches('[data-scan-skill]')||!state.scan)return;const skill=e.target.dataset.scanSkill,value=Number(e.target.value);if(Number.isFinite(value))state.scan.skills[skill]=value;refreshScanVerification();});

  // ---------- Drill profile ----------
  async function renderMyDrills(){const {normal,master}=await DP.ensure();$('#normalDrillConfig').innerHTML=D.NORMAL_DRILLS.map(d=>{const s=normal.drills[d.drillId]||{unlocked:false,level:0};return `<div class="drill-config-row" data-drill-id="${esc(d.drillId)}"><div class="drill-config-main"><img src="${drillAsset(d.name,d.cat)}"><div><b>${esc(d.name)}</b><span>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</span></div></div><label class="unlock-control"><input type="checkbox" data-normal-unlock="${esc(d.drillId)}" ${s.unlocked?'checked':''}><i></i></label><select class="level-select" data-normal-level="${esc(d.drillId)}" ${s.unlocked?'':'disabled'}><option value="1" ${Number(s.level)===1?'selected':''}>Semi-pro +10%</option><option value="2" ${Number(s.level)===2?'selected':''}>Pro +20%</option><option value="3" ${Number(s.level)===3?'selected':''}>World-class +30%</option></select></div>`;}).join('');$('#masterStockConfig').innerHTML=D.MASTER_CAMPUS_DRILLS.map(d=>`<div class="master-card"><img src="${drillAsset(d.name,d.cat)}"><div class="master-card-copy"><span class="master-badge">MASTER +${esc(d.additionalTrainingEffectPercent)}%</span><b>${esc(d.name)}</b><small>${esc(d.diff)} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small><small>${esc(d.skills.join(' · '))}</small></div><label><span>CARDS OWNED</span><input type="number" min="0" step="1" inputmode="numeric" data-master-stock="${esc(d.drillId)}" value="${Math.max(0,Number(master.stock[d.drillId]||0))}"></label></div>`).join('');}
  document.addEventListener('change',async e=>{if(e.target.matches('[data-normal-unlock]')){const id=e.target.dataset.normalUnlock,row=e.target.closest('.drill-config-row'),sel=row.querySelector('[data-normal-level]'),unlocked=e.target.checked;sel.disabled=!unlocked;const level=unlocked?(Number(sel.value)||1):(Number(sel.value)||0);await DP.setNormal(id,{unlocked,level});clearTrainingSessionView();toast(`${row.querySelector('b').textContent} ${unlocked?'enabled':'locked'} · saved sessions cleared`);await updateTrainingIntel();}else if(e.target.matches('[data-normal-level]')){const id=e.target.dataset.normalLevel,row=e.target.closest('.drill-config-row'),unlock=row.querySelector('[data-normal-unlock]');await DP.setNormal(id,{unlocked:unlock.checked,level:Number(e.target.value)});clearTrainingSessionView();toast('Drill level saved · sessions cleared');}else if(e.target.matches('[data-master-stock]')){const q=await DP.setMasterStock(e.target.dataset.masterStock,e.target.value);e.target.value=q;clearTrainingSessionView();toast('Master stock saved · sessions cleared');await updateTrainingIntel();}});
  $('#resetDrillsBtn')?.addEventListener('click',async()=>{const b=$('#resetDrillsBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again';setTimeout(()=>{delete b.dataset.armed;b.textContent='Reset snapshot';},3000);return;}await DP.resetToCapturedSnapshot();clearTrainingSessionView();delete b.dataset.armed;b.textContent='Reset snapshot';toast('Captured drill snapshot restored · sessions cleared');await renderMyDrills();await updateTrainingIntel();});

  // ---------- Individual training ----------
  function clearTrainingSessionView(message=''){state.session=null;if($('#trainingResults'))$('#trainingResults').style.display='none';if(message&&$('#trainingStatus'))$('#trainingStatus').textContent=message;}
  function trainingSourceSnapshot(player,normal,master){return {playerUpdatedAt:String(player?.updatedAt||''),normalUpdatedAt:String(normal?.updatedAt||''),masterUpdatedAt:String(master?.updatedAt||'')};}
  function sameTrainingSource(a,b){return !!a&&a.playerUpdatedAt===b.playerUpdatedAt&&a.normalUpdatedAt===b.normalUpdatedAt&&a.masterUpdatedAt===b.masterUpdatedAt;}
  async function updateTrainingIntel(){const {normal,master}=await DP.ensure();const unlocked=Object.values(normal.drills).filter(x=>x.unlocked).length,totalMaster=Object.values(master.stock).reduce((a,b)=>a+Math.max(0,Number(b)||0),0);if($('#intelNormalCount'))$('#intelNormalCount').textContent=unlocked;if($('#intelMasterCount'))$('#intelMasterCount').textContent=totalMaster;}
  async function renderTrainingPicker(){await updateTrainingIntel();const players=await P.all();$('#trainingPlayer').innerHTML='<option value="">Select a player</option>'+players.map(p=>`<option value="${esc(p.key)}" ${p.key===state.trainingKey?'selected':''}>${esc(p.name)} · ${esc(rolesLabel(p))} · ${esc(p.ovr||'—')} OVR</option>`).join('');clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey&&!players.some(p=>p.key===state.trainingKey)){state.trainingKey='';return;}if(state.trainingKey)await restoreTrainingSession();}
  async function persistTraining(){if(!state.trainingKey||!state.session)return;await S.set(`training:session:${state.trainingKey}`,JSON.stringify({gameDataVersion:D.GAME_DATA_VERSION,session:state.session,savedAt:new Date().toISOString()}));}
  async function restoreTrainingSession(){clearTrainingSessionView();const key=`training:session:${state.trainingKey}`,raw=await S.get(key);if(!raw)return false;try{const x=JSON.parse(raw);if(x.gameDataVersion!==D.GAME_DATA_VERSION||x.session?.meta?.model!==T.MODEL_VERSION){await S.del(key);$('#trainingStatus').textContent='A previous recommendation used older training data. Build a fresh session.';return false;}const player=await P.get(state.trainingKey);if(!player){await S.del(key);return false;}const {normal,master}=await DP.ensure(),current=trainingSourceSnapshot(player,normal,master);if(!sameTrainingSource(x.session?.sourceSnapshot,current)){await S.del(key);$('#trainingStatus').textContent='Saved recommendation expired because the player or My Drills changed. Build a fresh session.';return false;}state.session=x.session;renderSession();$('#trainingStatus').textContent=state.session.completed?'Completed session restored.':'Saved recommendation restored.';return true;}catch(_){await S.del(key);$('#trainingStatus').textContent='Saved recommendation could not be restored. Build a fresh session.';return false;}}
  $('#trainingPlayer')?.addEventListener('change',async e=>{state.trainingKey=e.target.value;clearTrainingSessionView();$('#trainingStatus').textContent='';if(state.trainingKey)await restoreTrainingSession();});
  async function buildTraining(){if(!state.trainingKey){toast('Select a player first','err');return;}const player=await P.get(state.trainingKey);if(!player){toast('Player could not be loaded','err');return;}const {normal,master}=await DP.ensure();const result=T.buildIndividualSession({player,normalProfile:normal,masterStock:master,slots:6,mode:$('#trainingMode')?.value||'maxGrowth'});if(result.error==='missing-white-attributes'){$('#trainingStatus').textContent=`Cannot optimise reliably: ${result.missingAttributes.join(', ')} are missing from this player profile. Rescan or update the player first.`;$('#trainingResults').style.display='none';toast('Player profile is incomplete','err');return;}state.session={...result,playerKey:state.trainingKey,playerName:player.name,completed:false,stockDeducted:false,createdAt:new Date().toISOString(),sourceSnapshot:trainingSourceSnapshot(player,normal,master)};renderSession();await persistTraining();$('#trainingStatus').textContent=result.drills.length===6?`Built 6 slots from ${result.meta.normalCandidateCount} unlocked normal drills and ${result.meta.masterCandidateCount} owned Master drill types. Ranking favours the strongest drills that hit the player's weakest white/key attributes, with multi-white coverage rewarded; no exact gain is predicted.`:`Only ${result.drills.length}/6 legal slots could be built from your saved drill library.`;}
  $('#buildSessionBtn')?.addEventListener('click',buildTraining);$('#rebuildBtn')?.addEventListener('click',buildTraining);
  function masterProjectionHtml(r){const usage=Object.entries(r.meta?.masterUsage||{}).filter(([,n])=>Number(n)>0);if(!usage.length)return'';return `<div class="master-projection wide"><span>Master stock ${r.completed?'remaining':'projection'}</span><div>${usage.map(([id,n])=>{const name=D.MASTER_CAMPUS_DRILLS.find(d=>d.drillId===id)?.name||id,used=Number(n)||0,remaining=Number(r.meta?.remainingMasterStock?.[id]??0),owned=remaining+used;return `<section><b>${esc(name)}</b><small>${owned} owned at build</small><strong>${used} used</strong><em>${remaining} ${r.completed?'remaining now':'projected remaining'}</em></section>`;}).join('')}</div></div>`;}
  function renderSession(){const r=state.session;if(!r)return;$('#trainingResults').style.display='block';const priority=(r.meta?.priorityAttributes||[]);$('#priorityAttributes').innerHTML=priority.map((x,i)=>`<div class="priority-pill"><span>${i+1}</span><b>${esc(x.attribute)}</b><small>${esc(x.value)}</small></div>`).join('');const masterSeen={};$('#sessionList').innerHTML=r.drills?.length?r.drills.map((d,i)=>{let stockLine='';if(d.isMaster){masterSeen[d.drillId]=(masterSeen[d.drillId]||0)+1;const used=Number(r.meta?.masterUsage?.[d.drillId]||0),remaining=Number(r.meta?.remainingMasterStock?.[d.drillId]??0),owned=remaining+used;stockLine=`<div class="master-use-line">Card ${masterSeen[d.drillId]}/${used} · ${owned} owned · ${remaining} ${r.completed?'remaining':'left after this session'}</div>`;}const grey=(d.greyApplicableAttributes||[]);const greyLine=grey.length?`<div class="grey-info"><span>Grey / information only · zero score</span>${grey.map(a=>`<i>${esc(a)}</i>`).join('')}</div>`:'';return `<div class="drill-row ${d.isMaster?'master':''}"><div class="slot-no">${String(i+1).padStart(2,'0')}</div><img src="${drillAsset(d.name,d.cat)}"><div class="drill-copy"><div class="drill-title-line"><b>${esc(d.name)}</b>${d.isMaster?'<span class="master-badge small">MASTER</span>':''}</div><small>${d.isMaster?`+${d.effectPct}% Training Effect`:`${esc(d.levelName)} · +${d.effectPct}%`} · ${fmt(d.conditionDrop,2)}% condition · +${esc(d.xpPerPlayer)} XP</small>${stockLine}<div class="target-line"><span>Targets · ${d.targetedWhiteAttributes.length} white</span>${d.targetedWhiteAttributes.map(a=>`<i>${esc(a)}</i>`).join('')}</div>${greyLine}</div><span class="diff ${diffClass(d.diff)}">${esc(d.diff)}</span></div>`;}).join(''):'<div class="empty"><b>No legal session</b>Check My Drills and the selected player profile.</div>';$('#sessionSummary').innerHTML=`<div><span>Total condition</span><b>${fmt(r.meta?.totalCondition,2)}%</b></div><div><span>Total XP</span><b>${fmt(r.meta?.totalXp,0)}</b></div><div><span>Recommendation score</span><b>${fmt(r.meta?.totalUsefulScore,1)}</b></div>${masterProjectionHtml(r)}<p><strong>Top Eleven Tool calculation.</strong> The recommendation score rewards real drill strength and coverage of current white/key needs. Grey attributes have zero utility. It is not an exact predicted +X% gain.</p>`;$('#completeSessionBtn').disabled=!!r.completed;$('#completeSessionBtn').textContent=r.completed?'Session Completed ✓':'Mark Session Completed';$('#sessionCompleteNote').textContent=r.completed?(r.stockDeducted?'Master card stock has been deducted once; the remaining figures above are current.':'Completed. No Master cards were used.'):'Master figures above are projected only. Stock changes when you complete the whole session.';}
  $('#completeSessionBtn')?.addEventListener('click',async()=>{if(!state.session||state.session.completed)return;const usage=state.session.meta?.masterUsage||{};if(Object.values(usage).some(n=>Number(n)>0)&&!state.session.stockDeducted){const updatedMaster=await DP.deductMasterUsage(usage);state.session.stockDeducted=true;if(state.session.sourceSnapshot)state.session.sourceSnapshot.masterUpdatedAt=String(updatedMaster.updatedAt||'');}state.session.completed=true;state.session.completedAt=new Date().toISOString();await persistTraining();renderSession();await updateTrainingIntel();toast('Training session completed');});

  // ---------- Team normal-drill group planner ----------
  async function renderTeamTraining(){const normal=await DP.getNormal(),players=await P.all();$('#teamTrainingCards').innerHTML=Object.entries(D.TEAM_GROUPS).map(([key,g])=>{const r=TT.buildTeamSession(key,{normalProfile:normal,players});return `<div class="team-card"><div class="team-card-top"><img src="assets/icons/team.svg"><div><span>TOP ELEVEN TOOL CALCULATION</span><b>${esc(g.title)}</b></div></div>${r.error?`<div class="mini-note spaced">${r.error==='no-complete-players'?'No complete player profiles in this group.':esc(r.error)}</div>`:`<div class="team-mini-list">${r.drills.map(d=>`<div><b>${esc(d.name)}</b><span>${esc(d.diff)} · +${d.effectPct}% · ${d.usefulHits} useful player/skill hits</span></div>`).join('')}</div><small>${r.meta.selectedPlayerCount} actual players · ${fmt(r.meta.totalCondition,2)}% condition · score ${fmt(r.meta.totalUsefulScore,1)}</small>`}</div>`;}).join('');}
  function setTrainingTab(tab){state.trainingTab=tab;$$('[data-training-tab]').forEach(b=>b.classList.toggle('active',b.dataset.trainingTab===tab));$('#individualTrainingPanel').style.display=tab==='individual'?'block':'none';$('#teamTrainingPanel').style.display=tab==='team'?'block':'none';if(tab==='team')renderTeamTraining();}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-training-tab]');if(b)setTrainingTab(b.dataset.trainingTab);});

  // ---------- Team Plan ----------
  function clearPitch(){$('#formationPitch')?.querySelectorAll('.pitch-player').forEach(e=>e.remove());}
  function benchCard(p){return `<button class="bench-card" data-player-key="${esc(p.key)}"><b>${esc(p.name||'Player')}</b><span>${esc(rolesLabel(p))} · OVR ${esc(p.ovr||'—')}</span></button>`;}
  async function showTeamPlanEmpty(players){const count=players.length,needed=Math.max(0,11-count),empty=$('#formationEmpty');clearPitch();$('#formationName').textContent=count?'Squad incomplete':'No squad yet';$('#formationSummary').textContent=count?`Add ${needed} more player${needed===1?'':'s'} with complete role attributes.`:'Add players to unlock Team Plan.';$('#formationXIList').innerHTML='<div class="empty formation-list-empty">Build a complete XI to see assigned-role details.</div>';$('#formationBench').innerHTML=count?players.map(benchCard).join(''):'<div class="empty formation-list-empty"><b>No players added</b>Use Add Player to scan your first profile.</div>';if(empty){empty.style.display='grid';empty.innerHTML=`<img src="assets/icons/squad.svg" alt=""><b>${count}/11 PLAYERS</b><span>${count?`${needed} more required for a full XI.`:'Build your squad before choosing a team plan.'}</span><button class="btn primary compact" data-go="add-player">+ Add Player</button>`;}$('#tacticPlan').innerHTML='';$('#mentorStrip').innerHTML='';$('#mentorAlternatives').innerHTML='';$('#mentorReason').textContent='';}
  async function renderFormationFromPlan(plan){const players=await P.all();if(!plan||plan.error){await showTeamPlanEmpty(players);if(plan?.error)$('#formationSummary').textContent=plan.error;return;}const empty=$('#formationEmpty');if(empty)empty.style.display='none';$('#formationName').textContent=plan.formationName;const naturalCount=plan.starters.filter(x=>x.suitability==='NATURAL').length;$('#formationSummary').textContent=`${naturalCount}/11 natural assignments · global maximum role-score assignment · exact Build 30527 role geometry.`;clearPitch();const detailed=[];for(const s0 of plan.starters){const p=await P.get(s0.playerKey);if(!p)continue;const el=document.createElement('button');el.className='pitch-player';el.style.left=(s0.y/10)+'%';el.style.top=((1-s0.x/1000)*100)+'%';el.dataset.playerKey=p.key;el.dataset.assignedRole=s0.assignedRole;el.dataset.x=String(s0.x);el.dataset.y=String(s0.y);const last=String(p.name||'Player').trim().split(/\s+/).pop();el.innerHTML=`<span class="pitch-player-ring"><img src="${roleAsset(s0.assignedRole)}"></span><b>${esc(last)}</b><small>${esc(s0.assignedRole)} · ${fmt(s0.roleMean,1)}</small>`;$('#formationPitch').appendChild(el);const ps=P.normalisePlaystyle(p.playstyle),psName=P.playstyleName(p),psLevel=playstyleLevelLabel(ps);const abilities=(p.specialAbilities||[]);const weak=(s0.weakest||F.roleStats(p,s0.assignedRole)?.weakest||[]).slice(0,3);detailed.push(`<button class="xi-detail-card" data-player-key="${esc(p.key)}"><div class="xi-main"><img src="${roleAsset(s0.assignedRole)}"><div><b>${esc(p.name||'Player')}</b><span><strong>${esc(s0.assignedRole)}</strong> <i class="suitability ${String(s0.suitability).toLowerCase()}">${esc(s0.suitability)}</i> · X ${esc(s0.x)} / Y ${esc(s0.y)}</span></div><div class="role-score"><small>ROLE SCORE</small><strong>${fmt(s0.roleMean,1)}</strong></div></div><div class="xi-weak"><span>Weakest 3 role-key skills</span>${weak.map(x=>`<i>${esc(x.attribute)} ${esc(x.value)}</i>`).join('')}</div><div class="xi-tags">${psName?`<span class="${s0.playstyleFit?'fit':'no-fit'}">${esc(psName)} · ${esc(psLevel)} · ${s0.playstyleFit?'Role fit':'No role fit'}</span>`:'<span>No playstyle</span>'}${abilities.map(a=>`<span class="ability">${esc(a)}</span>`).join('')}</div></button>`);}$('#formationXIList').innerHTML=detailed.join('');const bench=[];for(const k of plan.bench||[]){const p=await P.get(k);if(p)bench.push(p);}$('#formationBenchTitle').textContent=`Bench · ${bench.length}`;$('#formationBench').innerHTML=bench.length?bench.map(benchCard).join(''):'<div class="empty formation-list-empty"><b>No substitutes</b>Every saved player is in the selected XI.</div>';}
  function renderTacticsFromPlan(plan){const t=plan?.tactics;if(!t){$('#tacticPlan').innerHTML='<div class="empty">Build the XI first.</div>';return;}const labels={passing:'Passing',shooting:'Shooting',focus:'Focus Passing',cross:'Cross Tendency',lost:'Possession Lost',won:'Possession Won',mentality:'Mentality',marking:'Marking',pressing:'Pressing',backLine:'Back Line',tackling:'Tackling'};$('#tacticPlan').innerHTML=TAC.DIMENSIONS.map(dim=>{const o=TAC.option(dim,t.values[dim]);return `<div class="plan-item"><span>${labels[dim]}</span><b>${esc(o?.label||t.values[dim])}</b><small>${esc(t.reasons?.[dim]||'')}</small></div>`;}).join('');$('#planDrainBadge').textContent=`${t.drainClass} drain · ${t.rawScore}/100`;$('#planDrainBadge').classList.add('active');$('#tacticFitNote').textContent=`Exact Build 30527 drain · ${esc(t.evaluatedCandidates??19440)} candidates evaluated for the locked mentality · Top Eleven Tool tactic fit ${(t.tacticFit*100).toFixed(1)}%. Drain is game/native arithmetic; fit is transparent companion logic.`;}
  function mentorRawText(row){const m=row.mentor;return `${m.tactic.id} ${JSON.stringify(m.tactic.current)} · ${m.attribute.id} ${JSON.stringify(m.attribute.current)} · ${m.signature.id} ${JSON.stringify(m.signature.current)}`;}function renderMentorFromPlan(plan){const r=plan?.mentor;if(!r?.best){$('#mentorStrip').innerHTML='';$('#mentorReason').textContent='';$('#mentorAlternatives').innerHTML='';return;}$('#mentorStrip').innerHTML=B.MENTORS.map(m=>{const row=r.all.find(x=>x.mentor.id===m.id);return `<div class="mentor ${m.id===r.best.mentor.id?'active':''}"><img src="assets/mentors/${m.asset}"><div class="mentor-copy"><b>${esc(m.displayName)}</b><span>${esc(m.title)} · L${m.level}${row?` · direct ${row.directTacticMatch}/3 · ${row.attributeCoverage} useful key hits`:''}</span></div></div>`;}).join('');const bm=r.best.mentor;$('#mentorReason').textContent=`${bm.displayName}: ${r.best.reason} LIVE raw effects — ${mentorRawText(r.best)}. Raw arrays are preserved and not reinterpreted.`;$('#mentorAlternatives').innerHTML=(r.alternatives||[]).slice(0,2).map((a,i)=>`<div class="mentor-alt"><span>Alternative ${i+1}</span><b>${esc(a.mentor.displayName)}</b><small>${esc(a.whyNot||a.reason||'Ranks below the selected mentor by the documented synergy tuple.')}</small><em>Direct ${a.directTacticMatch}/3 · ${a.attributeCoverage} useful key hits · L${a.mentor.level}</em><code>${esc(mentorRawText(a))}</code></div>`).join('');}
  async function renderTeamPlan(){const players=await P.all();if(players.length<11){await showTeamPlanEmpty(players);return;}let plan=await TP.getOrBuild({templateId:$('#planTemplate')?.value||null,mode:$('#planMode')?.value||'bestXI',minCondition:Number($('#planMinCondition')?.value||60)});if(plan.error){await showTeamPlanEmpty(players);return;}$('#planApproach').value=plan.approach||state.approach;$('#planDrain').value=plan.drainLimit||state.drainLimit;$('#planMode').value=plan.mode||'bestXI';$('#planTemplate').value=plan.formationTemplateId||'';$('#planMinCondition').value=plan.minCondition??60;if(!plan.tactics)plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value});await renderFormationFromPlan(plan);renderTacticsFromPlan(plan);renderMentorFromPlan(plan);}
  $('#buildTeamPlanBtn')?.addEventListener('click',async()=>{const r=await TP.buildFormation({templateId:$('#planTemplate').value||null,mode:$('#planMode').value,minCondition:Number($('#planMinCondition').value||60)});if(r.error){await showTeamPlanEmpty(await P.all());toast(r.error,'err');return;}const plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value});await renderFormationFromPlan(plan);renderTacticsFromPlan(plan);renderMentorFromPlan(plan);toast(`${plan.formationName} Team Plan built`);});
  async function updatePlanOnly(){const existing=await TP.load();if(!existing){toast('Build the XI first','err');return;}const before=existing.starters.map(x=>x.playerKey+'@'+x.assignedRole).join('|'),plan=await TP.updateRecommendations({approach:$('#planApproach').value,drainLimit:$('#planDrain').value}),after=plan.starters.map(x=>x.playerKey+'@'+x.assignedRole).join('|');renderTacticsFromPlan(plan);renderMentorFromPlan(plan);$('#teamPlanNote').textContent=before===after?'Tactics updated without reshuffling the XI.':'Squad changed, so the XI was rebuilt before tactics.';}
  $('#refreshPlanTacticsBtn')?.addEventListener('click',updatePlanOnly);$('#planApproach')?.addEventListener('change',updatePlanOnly);$('#planDrain')?.addEventListener('change',updatePlanOnly);

  // ---------- Specialists ----------
  function rankRow(x,i,label=''){const p=x.player;return `<div class="rank-card"><div class="rank-num">${label||i+1}</div><img src="${roleAsset(p.position)}"><div><div class="rank-name">${esc(p.name)}</div><div class="rank-meta">${esc(rolesLabel(p))} · Top Eleven Tool calculation${x.specialist?` · specialist ${x.specialist}`:''}</div></div><div class="rank-score">${fmt(x.score,0)}</div></div>`;}
  async function renderPlaymakers(){const players=await P.all();if(!players.length){$('#penaltyRank').innerHTML='<div class="empty"><b>No squad yet</b>Add players to rank specialists.</div>';$('#specialistRank').innerHTML='';return;}const r=R.rankPlaymakers(players);$('#penaltyRank').innerHTML=r.penalties.map((x,i)=>rankRow(x,i)).join('');const specs=[['C',r.corner],['FK',r.freeKick]].filter(x=>x[1]);$('#specialistRank').innerHTML=specs.map(x=>rankRow(x[1],0,x[0])).join('')+`<div class="mini-note">${esc(r.captainNote)}</div>`;}

  // ---------- Settings / startup ----------
  $('#clearDataBtn')?.addEventListener('click',async()=>{const b=$('#clearDataBtn');if(!b.dataset.armed){b.dataset.armed='1';b.textContent='Tap again to confirm';setTimeout(()=>{delete b.dataset.armed;b.textContent='Clear all squad data';},3500);return;}for(const k of await S.list('player:'))await P.remove(k);for(const k of await S.list('training:session:'))await S.del(k);delete b.dataset.armed;b.textContent='Clear all squad data';toast('Squad data cleared');renderDashboard();});
  async function init(){await P.migrate();await DP.ensure();resetScanner();setTrainingTab('individual');await renderDashboard();await updateTrainingIntel();}
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.warn));
  init().catch(err=>{console.error(err);toast('App initialisation failed','err');});
})();
