(() => {
  const TE=window.TE5=window.TE5||{};const B=TE.BibleData,D=TE.Data,STRAT=TE.Strategy,CFG=TE.StrategyData;
  if(!B||!D||!STRAT||!CFG)throw new Error('bible-data.js, data.js, strategy-data.js and strategy-logic.js must load before mentor-engine.js');
  const MODEL_VERSION='mentor-synergy-v5-own-squad-v2',UNLOCK_LEVELS={tactic:1,attribute:5,signature:10};let STATE_OVERRIDES={};
  function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,v));}function clampLevel(v){return Math.max(1,Math.min(10,Math.round(Number(v)||1)));}
  function normaliseState(raw){return{unlocked:!!raw?.unlocked,level:clampLevel(raw?.level)};}function setStateOverrides(map={}){STATE_OVERRIDES=Object.fromEntries(Object.entries(map).map(([id,v])=>[id,normaliseState(v)]));}function getStateOverrides(){return JSON.parse(JSON.stringify(STATE_OVERRIDES));}function setLevelOverrides(map={}){setStateOverrides(map);}function getLevelOverrides(){return getStateOverrides();}
  function effectiveMentor(raw){const state=normaliseState(STATE_OVERRIDES[raw.id]);return{...raw,...state};}function activeFamilies(m){return{tactic:!!m.unlocked&&m.level>=UNLOCK_LEVELS.tactic,attribute:!!m.unlocked&&m.level>=UNLOCK_LEVELS.attribute,signature:!!m.unlocked&&m.level>=UNLOCK_LEVELS.signature};}
  function configFor(m){return CFG.mentors?.mentors?.[m.id]||null;}
  function context(starters,tactics){return STRAT.buildContext(starters,tactics?.values||tactics||{});}
  function tacticalPoints(m,starters,tactics){const active=activeFamilies(m);if(!active.tactic)return{points:0,active:false,reason:`Tactical locked until Level ${UNLOCK_LEVELS.tactic}`};const c=configFor(m)?.tactical;if(!c)return{points:0,active:false,reason:'No tactical contract'};if(c.scoring==='unavailable_in_prematch_own_squad_mode')return{points:0,active:false,reason:TE.StrategyStrings?.[c.message]||'Context unavailable in this pre-match mode'};const ctx=context(starters,tactics);let on=false,points=0;if(c.when){on=STRAT.conditionMatches(c.when,ctx);points=on?Number(c.max_points)||40:0;}else if(c.feature){const v=ctx.own?.[c.feature];if(typeof v==='boolean'){on=v;points=on?Number(c.max_points)||40:0;}else{points=v==='high'?40:v==='medium'?20:0;on=points>0;}}return{points,active:on,reason:TE.StrategyStrings?.[c.message]||c.id};}
  // Compatibility helper: old callers used a 0..3 semantic value. It now derives from the v2 0..40 contract.
  function direct(m,tactics){const starters=tactics?.starters||[];const r=tacticalPoints(m,starters,tactics);return r.points/40*3;}
  function attributeCoverage(m,starters,tactics=null){
    if(!activeFamilies(m).attribute)return{hits:0,coveragePercent:0,rawRelevance:0,score:0};const attrs=configFor(m)?.attribute?.attributes||m.attribute?.attributes||[];let hits=0,raw=0;
    for(const s of starters){const white=D.POSITION_WHITE[s.assignedRole]||[];let profile=null;for(const a of attrs){if(!white.includes(a))continue;hits++;if(!profile)profile=STRAT.trainingPriorityProfile(s.player,{roles:[s.assignedRole],developmentRole:s.assignedRole,tactics:null});const row=profile.priorities.find(x=>x.attribute===a),baseWeight=Number(STRAT.TIER_WEIGHT?.[row?.tier]||1),tacticAdd=Number(STRAT.tacticTrainingSignals(s.assignedRole,a,tactics).add)||0;raw+=baseWeight*(1+tacticAdd);}}
    return{hits,coveragePercent:attrs.length&&starters.length?hits/(starters.length*attrs.length)*100:0,rawRelevance:raw,score:25*Math.min(1,raw/24)};
  }
  function signatureContext(m,starters,tactics){const active=activeFamilies(m);if(!active.signature)return{points:0,score:0,active:false,reason:`Signature locked until Level ${UNLOCK_LEVELS.signature}`};const c=configFor(m)?.signature;if(!c)return{points:0,score:0,active:false,reason:'No signature contract'};if(c.scoring==='unavailable_in_prematch_own_squad_mode')return{points:0,score:0,active:false,reason:TE.StrategyStrings?.[c.message]||'Context unavailable in this pre-match mode'};const ctx=context(starters,tactics);let on=false;if(c.when)on=STRAT.conditionMatches(c.when,ctx);else if(c.feature)on=ctx.own?.[c.feature]==='high'||ctx.own?.[c.feature]===true;const points=on?(Number(c.max_points)||30):0;return{points,score:points/10,active:on,reason:TE.StrategyStrings?.[c.message]||c.id};}
  function tradeoffPoints(m,{tacticalActive=false,signatureActive=false,drainLimit='Medium'}={}){let penalty=0,reasons=[];for(const row of configFor(m)?.tradeoffs||[]){const applies=row.when==='tacticalActive'?tacticalActive:row.when==='signatureActive'?signatureActive:false;if(!applies)continue;let p=Number(row.severity_by_drain_limit?.[drainLimit]);if(!Number.isFinite(p))p=Number(row.penalty_max)||0;penalty-=Math.abs(p);reasons.push({points:-Math.abs(p),reason:TE.StrategyStrings?.[row.message]||row.message});}return{penalty,reasons};}
  function nextUnlock(m){const level=Number(m.level)||1;if(!m.unlocked)return{family:'mentor',level:1};if(level<UNLOCK_LEVELS.attribute)return{family:'attribute',level:UNLOCK_LEVELS.attribute};if(level<UNLOCK_LEVELS.signature)return{family:'signature',level:UNLOCK_LEVELS.signature};return null;}
  function rawEffects(m){const a=activeFamilies(m);return{tactic:{id:m.tactic.id,active:a.tactic,magnitude:'UNRESOLVED FOR SELECTED LEVEL'},attribute:{id:m.attribute.id,attributes:[...m.attribute.attributes],active:a.attribute,magnitude:'UNRESOLVED FOR SELECTED LEVEL'},signature:{id:m.signature.id,active:a.signature,magnitude:'UNRESOLVED FOR SELECTED LEVEL'}};}
  function compare(a,b){if(Math.abs(a.planAdjustment-b.planAdjustment)>1e-12)return b.planAdjustment-a.planAdjustment;if(Math.abs(a.rawScore-b.rawScore)>1e-12)return b.rawScore-a.rawScore;if(a.tacticalPoints!==b.tacticalPoints)return b.tacticalPoints-a.tacticalPoints;if(a.signaturePoints!==b.signaturePoints)return b.signaturePoints-a.signaturePoints;return a.stableOrder-b.stableOrder;}
  function tupleText(r){const f=r.activeFamilies,n=r.nextUnlock;return `${r.rawScore.toFixed(2)}/95 raw own-plan relevance; adjustment ${r.planAdjustment.toFixed(2)}/10; Tactical ${r.tacticalPoints}/40; Attribute ${r.attributeScore.toFixed(2)}/25; Signature ${r.signaturePoints}/30; tradeoffs ${r.tradeoffPoints.toFixed(2)}. Active families: ${[f.tactic&&'Tactical',f.attribute&&'Attribute',f.signature&&'Signature'].filter(Boolean).join(' + ')||'none'}${n?`; next unlock ${n.family} at Level ${n.level}`:''}.`;}
  function whyBelow(r,b){return `Own-plan adjustment ${r.planAdjustment.toFixed(2)} vs ${b.planAdjustment.toFixed(2)}; raw ${r.rawScore.toFixed(2)} vs ${b.rawScore.toFixed(2)}.`;}
  function recommend(starters,tactics,{drainLimit=tactics?.drainLimit||'Medium'}={}){
    if(!starters?.length||!tactics?.values)return{error:'missing-plan'};const rows=B.MENTORS.map((rawMentor,stableOrder)=>{const mentor=effectiveMentor(rawMentor),active=activeFamilies(mentor),tac=tacticalPoints(mentor,starters,tactics),coverage=attributeCoverage(mentor,starters,tactics),sig=signatureContext(mentor,starters,tactics),trade=tradeoffPoints(mentor,{tacticalActive:tac.active,signatureActive:sig.active,drainLimit}),rawScore=Math.max(0,tac.points+coverage.score+sig.points+trade.penalty),planAdjustment=10*clamp(rawScore/95,0,1);return{mentor,stableOrder,activeFamilies:active,tacticalPoints:tac.points,directTacticMatch:tac.points/40*3,tacticalReason:tac.reason,attributeCoverage:coverage.hits,coveragePercent:coverage.coveragePercent,attributeRawRelevance:coverage.rawRelevance,attributeScore:coverage.score,signatureAvailable:active.signature,signaturePoints:sig.points,signatureScore:sig.points/10,signatureReason:sig.reason,tradeoffPoints:trade.penalty,tradeoffReasons:trade.reasons,rawScore,totalScore:rawScore,planAdjustment,nextUnlock:nextUnlock(mentor),rawEffects:rawEffects(mentor)};}).filter(r=>r.mentor.unlocked).sort(compare);
    if(!rows.length)return{model:MODEL_VERSION,evidence:'TOP ELEVEN TOOL CALCULATION',error:'no-unlocked-mentors',best:null,alternatives:[],all:[]};const bestRow=rows[0],best={...bestRow,reason:tupleText(bestRow)},alternatives=rows.slice(1,3).map(r=>({...r,reason:whyBelow(r,bestRow)}));return{model:MODEL_VERSION,evidence:'TOP ELEVEN TOOL CALCULATION',evidencePolicy:'Mentor ranking uses own XI, selected tactic and saved unlock/level only. Unavailable contextual families score zero.',best,alternatives,all:rows};
  }
  TE.Mentor={MODEL_VERSION,UNLOCK_LEVELS,recommend,attributeCoverage,direct,tacticalPoints,signatureContext,tradeoffPoints,nextUnlock,rawEffects,activeFamilies,setStateOverrides,getStateOverrides,setLevelOverrides,getLevelOverrides,effectiveMentor,MENTORS:B.MENTORS};
})();
