const CACHE='te-v5-alpha1';
const ASSETS=["./assets/drills/aerial.webp", "./assets/drills/agility.webp", "./assets/drills/dribble.webp", "./assets/drills/one-v-one.webp", "./assets/drills/pass.webp", "./assets/drills/shoot.webp", "./assets/icons/add.svg", "./assets/icons/close.svg", "./assets/icons/home.svg", "./assets/icons/more.svg", "./assets/icons/playmakers.svg", "./assets/icons/settings.svg", "./assets/icons/squad.svg", "./assets/icons/tactics.svg", "./assets/icons/team.svg", "./assets/icons/training.svg", "./assets/mentors/alan-shearer.png", "./assets/mentors/cesc-fabregas.png", "./assets/mentors/claude-makelele.png", "./assets/mentors/jonas-brown.png", "./assets/mentors/lewis-green.png", "./assets/mentors/nemanja-vidic.png", "./assets/mentors/ruben-herrera.png", "./assets/roles/am.webp", "./assets/roles/d.webp", "./assets/roles/dm.webp", "./assets/roles/gk.webp", "./assets/roles/m.webp", "./assets/roles/st.webp", "./assets/scenes/add-player.webp", "./assets/scenes/dashboard.webp", "./assets/scenes/playmakers.webp", "./assets/scenes/settings.webp", "./assets/scenes/squad.webp", "./assets/scenes/tactics.webp", "./assets/scenes/team-training.webp", "./assets/scenes/training.webp", "./css/app.css", "./icon-192.png", "./icon-512.png", "./index.html", "./js/app.js", "./js/data.js", "./js/players.js", "./js/recommendations.js", "./js/scanner-engine.js", "./js/scanner-templates.json", "./js/storage.js", "./js/team-training-engine.js", "./js/training-engine.js", "./manifest.json"];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const url=new URL(e.request.url);
  if(url.origin!==self.location.origin){e.respondWith(fetch(e.request));return;}
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(resp=>{const copy=resp.clone();caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{});return resp;}).catch(()=>e.request.mode==='navigate'?caches.match('./index.html'):Response.error())));
});
