const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;const ROOT=path.join(__dirname,'..');
for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','best-in-slot-data.js','strategy-logic.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','best-in-slot-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {BestInSlot:BIS}=TE5;const goal=BIS.getGoal();let n=0;const failures=[];function ok(v,m){n++;if(!v)failures.push(m)}
function p(key,name,roles,ps=null,level='Master',sa=[]){const x={key,name,position:roles[0],roles:[...roles],relatedRoles:[],playstyle:ps?{name:ps,level}:null,specialAbilities:[...sa]};Object.defineProperty(x,'ovr',{get(){throw new Error('OVR must not be read by Best-in-Slot squad gap')}});Object.defineProperty(x,'skills',{get(){throw new Error('Skills must not be read by Best-in-Slot squad gap')}});return x;}
let gap=BIS.squadGap([],goal);ok(gap.model===BIS.SQUAD_GAP_MODEL,'gap model id');ok(gap.summary.total===11,'11 target slots');ok(gap.summary.naturalCovered===0&&gap.summary.missing===11,'empty squad has 11 recruit gaps');ok(gap.slots.every(x=>x.status==='missing-natural-role'),'empty squad status');
const perfect=goal.slots.map((s,i)=>p('p'+i,'Perfect '+s.role,[s.role],s.playstyle,'Master',s.specialAbilities));gap=BIS.squadGap(perfect,goal);ok(gap.summary.naturalCovered===11,'perfect squad naturally covers all 11');ok(gap.summary.identityComplete===11,'perfect squad identity complete');ok(gap.summary.masterReady===11,'perfect squad master ready');ok(gap.summary.missing===0,'perfect squad no recruit gaps');ok(gap.slots.every(x=>x.player&&x.masterReady),'every perfect slot assigned once');ok(new Set(gap.slots.map(x=>x.player.key)).size===11,'global assignment does not reuse players');
const related=p('rel','Related only',['DC'],null,'Master',[]);related.relatedRoles=['DL'];gap=BIS.squadGap([related],goal);const dl=gap.slots.find(x=>x.role==='DL');ok(!dl.player&&!dl.naturalRoleCovered,'related role does not count as natural Best-in-Slot coverage');
const dcGoal=goal.slots.filter(x=>x.role==='DC');ok(dcGoal.length===2,'fixture has two DC goal slots');gap=BIS.squadGap([p('one-dc','Only DC',['DC'],dcGoal[0].playstyle,'Master',dcGoal[0].specialAbilities)],goal);ok(gap.slots.filter(x=>x.role==='DC'&&x.player).length===1,'one DC cannot cover two goal slots');
const dmcSlots=goal.slots.map((s,i)=>({s,i})).filter(x=>x.s.role==='DMC');ok(dmcSlots.length===2,'fixture has two DMC goal slots');if(dmcSlots.length===2){const a=p('anchor','Anchor',['DMC'],dmcSlots[0].s.playstyle,'Master',dmcSlots[0].s.specialAbilities),b=p('regista','Regista',['DMC'],dmcSlots[1].s.playstyle,'Master',dmcSlots[1].s.specialAbilities);gap=BIS.squadGap([b,a],goal);ok(gap.slots[dmcSlots[0].i].player?.key==='anchor','global assignment gives first DMC its matching Playstyle');ok(gap.slots[dmcSlots[1].i].player?.key==='regista','global assignment gives second DMC its matching Playstyle');}
const stIndex=goal.slots.findIndex(x=>x.role==='ST'),stGoal=goal.slots[stIndex];const stNoSa=p('st','ST role',['ST'],stGoal.playstyle,'Master',[]);gap=BIS.squadGap([stNoSa],goal);const st=gap.slots[stIndex];ok(st.naturalRoleCovered,'natural ST counts as covered');ok(st.playstyle.exact,'ST Playstyle exact');ok(st.abilities.missing.length===stGoal.specialAbilities.length,'missing target SA reported');ok(!st.identityComplete&&!st.masterReady,'missing SA prevents complete goal match');
const locked=p('locked','Locked PS',[stGoal.role],stGoal.playstyle,'Locked',stGoal.specialAbilities);gap=BIS.squadGap([locked],goal);ok(!gap.slots[stIndex].playstyle.exact,'locked Playstyle is not an active exact match');
const extra=p('extra','Extra SA',[stGoal.role],stGoal.playstyle,'Master',[...stGoal.specialAbilities,'Free Kick Specialist']);gap=BIS.squadGap([extra],goal);ok(gap.slots[stIndex].masterReady,'extra non-target SA does not invalidate target match');
const noSaIndex=goal.slots.findIndex(x=>(x.specialAbilities||[]).length===0);if(noSaIndex>=0){const s=goal.slots[noSaIndex],x=p('nosa','No SA target',[s.role],s.playstyle,'Master',[]);gap=BIS.squadGap([x],goal);ok(gap.slots[noSaIndex].abilities.missing.length===0,'no-preference SA slot has no fabricated SA gap');ok(gap.slots[noSaIndex].masterReady,'no-preference SA slot can be master ready without an SA');}

const targetWithSaIndex=goal.slots.findIndex(x=>(x.specialAbilities||[]).length>0);if(targetWithSaIndex>=0){
  const s=goal.slots[targetWithSaIndex],alt=(TE5.Data.playstylesForRoles([s.role])||[]).find(x=>x!==s.playstyle),wrong=p('wrong-ps','Wrong Playstyle',[s.role],alt||s.playstyle,'Master',s.specialAbilities);gap=BIS.squadGap([wrong],goal);if(alt)ok(gap.slots[targetWithSaIndex].status==='playstyle-identity-gap','wrong existing Playstyle is classified as an identity gap, not normal development');
  const free=p('free-sa','Free SA slot',[s.role],s.playstyle,'Master',[]);gap=BIS.squadGap([free],goal);ok(gap.slots[targetWithSaIndex].status==='sa-development'&&gap.slots[targetWithSaIndex].abilities.slotsFree===2,'missing target SA with free capacity is a trainable SA-development gap');
  const blocked=p('blocked-sa','Full SA slots',[s.role],s.playstyle,'Master',['Unrelated A','Unrelated B']);gap=BIS.squadGap([blocked],goal);ok(gap.slots[targetWithSaIndex].status==='sa-capacity-gap'&&gap.slots[targetWithSaIndex].abilities.slotsFree===0,'missing target SA with two occupied slots is an SA-capacity identity gap');
}
const upgradeIndex=goal.slots.findIndex(x=>x.playstyle);if(upgradeIndex>=0){const s=goal.slots[upgradeIndex],up=p('upgrade','Upgrade PS',[s.role],s.playstyle,'Intermediate',s.specialAbilities);gap=BIS.squadGap([up],goal);ok(gap.slots[upgradeIndex].status==='playstyle-upgrade'&&gap.slots[upgradeIndex].trainableDevelopment,'exact active non-Master Playstyle is a trainable upgrade gap');}
if(failures.length){console.error(`Best-in-Slot squad-gap contract: FAIL — ${failures.length}/${n}`);for(const f of failures)console.error('-',f);process.exit(1)}console.log(`Best-in-Slot squad-gap contract: PASS — ${n} assertions`);
