const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;const ROOT=path.join(__dirname,'..');
for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','best-in-slot-data.js','strategy-logic.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','best-in-slot-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {BestInSlot:BIS,Data:D,Formation:F,Tactics:T,Mentor:M,Recommendations:R,Strategy:S,StrategyData:CFG}=TE5;
let n=0;const failures=[];function ok(v,m){n++;if(!v)failures.push(m);}const check=BIS.validate();ok(check.valid,`dataset validates: ${check.errors.join(', ')}`);const goal=BIS.getGoal();ok(!goal.error,'goal loads');ok(goal.model===BIS.MODEL_VERSION,'model matches');ok(goal.sourceModels.gameData===D.GAME_DATA_VERSION,'game data matches');ok(goal.sourceModels.strategy===S.MODEL_VERSION,'strategy matches');ok(goal.sourceModels.formation===F.MODEL_VERSION,'formation matches');ok(goal.sourceModels.tactics===T.MODEL_VERSION,'tactics matches');ok(goal.sourceModels.mentor===M.MODEL_VERSION,'mentor matches');ok(goal.sourceModels.setPieces===R.SET_PIECE_MODEL,'set pieces matches');
ok(goal.objective.playerStats==='Not used. Best-in-Slot compares role coverage, formation shape, role-eligible Playstyles/SAs, Tactics, Set Pieces and Mentor synergy only.','player stats explicitly unused');ok(/natural-role/i.test(goal.objective.coveragePolicy||''),'natural role coverage policy explicit');ok(/server-owned/i.test(goal.objective.squadBalancePolicy||''),'official Squad Balance boundary explicit');ok(goal.objective.opponentPolicy==='No opponent information is used.','no opponent input');
const form=F.formationById(goal.formation.id);ok(!!form,'current formation');ok(goal.slots.length===11,'11 slots');for(let i=0;i<goal.slots.length;i++){const s=goal.slots[i],role=D.normaliseRole(s.role);ok(F.options(form.slots[i]).includes(role),`slot ${i+1} legal formation role`);ok(D.playstylesForRoles([role]).includes(s.playstyle),`slot ${i+1} playstyle eligible`);ok(s.playstyleLevelTarget==='Master',`slot ${i+1} master target`);ok((s.specialAbilities||[]).length<=2,`slot ${i+1} max two SAs`);for(const sa of s.specialAbilities||[])ok(D.isSpecialAbilityEligibleForRoles(sa,[role]),`slot ${i+1} ${sa} eligible`);if(s.preferredTacticalSA){const aff=CFG.tactics?.special_ability_affinities?.[s.preferredTacticalSA];ok(!!aff?.active,`slot ${i+1} preferred SA has active affinity`);ok(s.specialAbilities.includes(s.preferredTacticalSA),`slot ${i+1} preferred SA targeted`);}else ok(s.saPreferenceStatus==='no-proven-open-play-preference',`slot ${i+1} no fake SA preference`);ok(!Object.prototype.hasOwnProperty.call(s,'attributeProfile'),`slot ${i+1} contains no invented attribute profile`);ok(Number.isFinite(Number(s.x))&&Number.isFinite(Number(s.y)),`slot ${i+1} coords`);}
const vals=goal.tactics?.values||{};for(const dim of T.SEARCH_DIMS)ok(!!T.option(dim,vals[dim]),`${dim} tactic valid`);ok(!!T.option('mentality',vals.mentality),'mentality valid');ok(['Low','Medium','High'].includes(goal.tactics.drainClass),'drain class valid');ok(Number.isFinite(goal.tactics.compatibilityScore),'tactic compatibility finite');ok(Number.isFinite(goal.score.totalScore),'package score finite');ok(goal.mentor&&Number.isFinite(goal.mentor.planAdjustment),'mentor comparison finite');ok(goal.setPieces.coverage>=3,'dedicated set piece duties covered');ok(BIS.tacticLabel('focus','center')==='Through the Middle','center label boundary correct');ok(Array.isArray(goal.alternatives)&&goal.alternatives.length>=2,'alternatives retained');
if(failures.length){console.error(`Best-in-Slot v2 contract: FAIL — ${failures.length}/${n}`);for(const f of failures)console.error('-',f);process.exit(1);}console.log(`Best-in-Slot v2 contract: PASS — ${n} assertions`);
