from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
cloud=(ROOT/'js/cloud.js').read_text()
storage=(ROOT/'js/storage.js').read_text()
app=(ROOT/'js/app.js').read_text()
html=(ROOT/'index.html').read_text()
css=(ROOT/'css/app.css').read_text()
sw=(ROOT/'sw.js').read_text()
errs=[]
if 'getDocsFromServer(col)' not in cloud: errs.append('initial cloud reconciliation is not server-confirmed')
if 'persistentLocalCache' in cloud or 'getDocsFromCache' in cloud: errs.append('Firestore persistent/cache fallback still exists alongside localStorage')
if 'state.db=m.getFirestore(state.app);' not in cloud: errs.append('Firestore is not using the safe default in-memory instance')
if 'initializeFirestore(state.app);' in cloud: errs.append('invalid initializeFirestore call without settings has returned')
if "snap.metadata?.fromCache||snap.metadata?.hasPendingWrites" not in cloud: errs.append('live sync does not reject cache/pending-write snapshots')
if 'includeMetadataChanges:true' in cloud: errs.append('metadata-only Firestore snapshots are still enabled')
if 'deleted:true' not in cloud or 'deleted:false' not in cloud: errs.append('cloud writes do not use explicit tombstones')
if 'queueSet' not in cloud or 'queueDelete' not in cloud or 'flushOutbox' not in cloud: errs.append('durable local cloud outbox is missing')
if "pendingOp(key)" not in cloud: errs.append('server snapshots can overwrite pending local edits')
if 'if(remote.has(key)||pendingOp(key))continue' not in cloud: errs.append('missing remote keys are not recovered safely from local data')
if "if(entry.deleted)localDelRaw(key)" not in cloud: errs.append('explicit tombstones are not applied locally')
if 'prepareLocalOwner()' not in cloud or 'state.ownerChangedOnBoot' not in cloud: errs.append('account switching does not isolate the local working copy')
if "typeof raw==='string'?raw" not in cloud or 'JSON.stringify(raw)' not in cloud: errs.append('legacy object-valued cloud records are not normalised')
if 'await syncSet' in storage or 'await syncDel' in storage: errs.append('local storage writes still block on Firestore network writes')
if 'queueSet?.(key,value)' not in storage or 'queueDelete?.(key)' not in storage: errs.append('storage is not queueing background cloud changes')
if "window.__TE_RUNTIME__='0.4.15-r1'" not in app: errs.append('runtime marker missing from app.js')
if 'data-runtime="0.4.15-r1"' not in html: errs.append('runtime marker missing from index.html')
if '?r=0415r1' not in html: errs.append('runtime assets are not cache-busted')
if "const CACHE='te-v0-4-15-r1'" not in sw: errs.append('service-worker cache is not v0.4.15-r1')
if '<body class="booting">' not in html or 'body.booting .app{visibility:hidden}' not in css: errs.append('refresh boot flash guard missing')
if 'te:post-auth:home' not in cloud or 'forceHome' not in app: errs.append('post-login Home landing guard missing')
if "toast('App initialisation failed','err')" in app: errs.append('generic startup failure toast returned')
if errs:
    print('FAIL cloud hydration/navigation contract')
    for e in errs: print('-',e)
    sys.exit(1)
print('PASS cloud hydration/navigation contract')
