const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;
global.localStorage={_m:new Map(),getItem(k){return this._m.has(k)?this._m.get(k):null},setItem(k,v){this._m.set(k,String(v))},removeItem(k){this._m.delete(k)},key(i){return [...this._m.keys()][i]||null},clear(){this._m.clear()},get length(){return this._m.size}};
const ROOT=path.join(__dirname,'..');
const files=['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','squad-coverage-engine.js','scanner-engine.js','storage.js','drill-profile.js','players.js','training-engine.js','team-training-engine.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','team-plan-engine.js'];
for(const f of files)vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {OptimizerData:OD,BibleData:B,Data:D,Strategy:STRAT,SquadCoverage:SCOV,Scanner:SC,Storage:S,DrillProfile:DP,Players:P,Training:T,TeamTraining:TT,Recommendations:R,Formation:F,Tactics:TAC,Mentor:M,TeamPlan:TP}=global.TE5;
let passed=0;
function ok(c,m){if(!c)throw new Error(m);passed++;}
function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),`${m}\n${JSON.stringify(a)} != ${JSON.stringify(b)}`)}
function near(a,b,e,m){ok(Math.abs(a-b)<=e,`${m}: ${a} vs ${b}`)}
const ALL_ATTRS=Object.keys(D.ATTRIBUTE_IDS);
function skills(v=100){return Object.fromEntries(ALL_ATTRS.map(a=>[a,v]));}
function player(key,name,roles,overrides={},relatedRoles=[],playstyle=null){return{key,name,age:22,ovr:100,position:roles[0],roles,relatedRoles,skills:{...skills(100),...overrides},specialAbilities:[],playstyle:playstyle||{type:null,level:0}};}
function greedyScore(players,formation){const remaining=[...players];let sum=0;for(const slot of formation.slots){let best=null,bi=-1;for(let i=0;i<remaining.length;i++)for(const role of F.options(slot)){const c=F.candidate(remaining[i],role);if(c&&(!best||c.roleMean>best.roleMean)){best=c;bi=i;}}if(!best)return-Infinity;sum+=best.roleMean;remaining.splice(bi,1);}return sum;}
function inside(role,x,y){const r=B.ROLE_RECTS[role];return x>=r.minX&&x<r.maxX&&y>=r.minY&&y<r.maxY;}
(async()=>{
  // ---------------------------------------------------------------------------
  // Build 30527 canonical roles / attributes / white maps.
  // ---------------------------------------------------------------------------
  const currentRoles=['GK','DL','DC','DR','DMC','ML','MC','MR','AML','AMC','AMR','ST'];
  eq(D.ALL_POSITIONS,currentRoles,'current role list exactly 12');
  ok(!D.ALL_POSITIONS.includes('DML')&&!D.ALL_POSITIONS.includes('DMR'),'DML/DMR are not selectable current roles');
  const expectedIds={Fitness:1,Strength:2,Aggression:3,Speed:4,Creativity:5,Passing:6,Dribbling:7,Crossing:8,Shooting:9,Finishing:10,Tackling:11,Marking:12,Positioning:13,Heading:14,Bravery:15,Reflexes:16,Agility:17,Anticipation:18,'Rushing Out':19,Communication:20,Throwing:21,Kicking:22,Punching:23,'Aerial Reach':24,Concentration:25};
  eq(D.ATTRIBUTE_IDS,expectedIds,'all 25 attribute IDs exact');
  eq(D.ATTRIBUTE_IDS,OD.whiteSkillMap.attribute_ids,'canonical attributes match captured build package');
  for(const r of currentRoles)eq(D.POSITION_WHITE[r],OD.whiteSkillMap.roles[r].key_attributes,`white map exact ${r}`);
  eq(D.whiteSkillsForRoles(['DC','DR']),['Tackling','Marking','Positioning','Heading','Bravery','Fitness','Strength','Aggression','Crossing','Speed'],'multi-natural-role white set is union');

  // ---------------------------------------------------------------------------
  // Non-destructive / idempotent v5.2.4 -> v5.2.x schema migration.
  // ---------------------------------------------------------------------------
  localStorage.clear();
  const oldKey='player:legacy_test';
  const fullPs={type:'BOX_TO_BOX',level:3,points:1234,isTrainingNextLevel:true,nextLevelPrice:17,isNextLevelAvailable:false,nextLevelProgress:0.42,boost:[11,4],opaqueServerField:'preserve-me'};
  const old={name:'Legacy Test',age:21,ovr:111,position:'MC',roles:['MC','AMC','DMC','ML','DML'],relatedRoles:['ST','DMR'],skills:{...skills(111)},playstyle:fullPs,specialAbilities:['Defensive Wall','Long Shots','Playmaker'],photo:'data:image/png;base64,abc',scanner:{version:2,confidence:{overall:.9}},sourceMeta:{scannerVersion:2,importedAt:'2026-09-09T00:00:00Z'}};
  localStorage.setItem('te:'+oldKey,JSON.stringify(old));
  const oldStringKey='player:legacy_string';localStorage.setItem('te:'+oldStringKey,JSON.stringify({name:'Old String',age:20,ovr:100,position:'ST',roles:['ST'],skills:skills(100),playstyle:'Poacher',specialAbilities:[]}));
  const customNormal={gameDataVersion:D.GAME_DATA_VERSION,updatedAt:'old-normal',drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:d.drillId!=='STAY_IN_LANE',level:d.drillId==='FAST_COUNTER_ATTACKS'?2:1}]))};
  const customMaster={gameDataVersion:D.GAME_DATA_VERSION,updatedAt:'old-master',stock:{ATTACKING_MASTERCLASS:7,MIDFIELD_MASTERCLASS:2,PHYSICAL_MASTERCLASS:0,DEFENDING_MASTERCLASS:1}};
  localStorage.setItem('te:training:normal-drills:build_30527',JSON.stringify(customNormal));localStorage.setItem('te:training:master-stock:build_30527',JSON.stringify(customMaster));
  ok(await P.migrate(),'migration runs once');ok(!(await P.migrate()),'migration is idempotent');
  const migrated=await P.get(oldKey);
  eq(migrated.roles,['MC','AMC','DMC','ML'],'all current imported natural roles survive; DML removed only from current set');
  eq(migrated.relatedRoles,['ST'],'all current related roles survive; DMR relegated to legacy metadata');
  ok(migrated.legacyRoles.includes('DML')&&migrated.legacyRoles.includes('DMR'),'legacy DML/DMR warning metadata retained');
  eq(migrated.specialAbilities,['Defensive Wall','Shadow Striker','Playmaker'],'legacy Long Shots migrates to current Shadow Striker display name without losing abilities');
  eq(migrated.playstyle.type,'BOX_TO_BOX','full playstyle type preserved');eq(migrated.playstyle.level,3,'full playstyle level preserved');eq(migrated.playstyle.points,1234,'full playstyle points preserved');eq(migrated.playstyle.boost,[11,4],'full playstyle boost preserved');ok(migrated.playstyle.opaqueServerField==='preserve-me','unknown playstyle fields preserved');
  ok(migrated.photo===old.photo&&migrated.scanner.version===2,'image/scanner metadata preserved');
  const migratedString=await P.get(oldStringKey);ok(P.playstyleName(migratedString)==='Poacher'&&migratedString.playstyle.level===0,'legacy playstyle string becomes object without invented level');
  ok((await DP.getNormal()).drills.FAST_COUNTER_ATTACKS.level===2,'drill level survives player migration');ok((await DP.getMaster()).stock.ATTACKING_MASTERCLASS===7,'Master stock survives player migration');
  const mergedRoles=P.mergeVisibleNaturalRoles(['MC','AMC','DMC','ML'],['MC','DMC','AMC'],3);eq(mergedRoles,['MC','DMC','AMC','ML'],'three-role editor preserves imported natural roles beyond visible editor');
  const keptPs=P.mergePlaystyleState(migrated.playstyle,'Box-to-Box');eq(keptPs.boost,[11,4],'same manual playstyle selection preserves full captured state');ok(keptPs.points===1234,'same playstyle preserves points/progress state');
  const changedPs=P.mergePlaystyleState(migrated.playstyle,'Mezzala');ok(changedPs.type==='MEZZALA'&&changedPs.level===0&&changedPs.points===null,'changed manual playstyle does not inherit old progress or invent new level');
  const stringLevel=P.normalisePlaystyle({type:'POACHER',level:'Intermediate',points:99});ok(stringLevel.level===3&&stringLevel.points===99,'known textual playstyle level maps to confirmed enum');

  // ---------------------------------------------------------------------------
  // Current playstyles and special abilities.
  // ---------------------------------------------------------------------------
  const psExpected={2:['ST'],3:['ST','AMC'],4:['ST'],5:['AMC'],6:['AML','AMR'],7:['AML','AMR','ML','MR'],8:['ML','MR'],9:['MC'],10:['MC'],11:['MC','DMC'],12:['DMC'],13:['DMC'],14:['DC'],15:['DC'],16:['DC'],17:['DL','DR'],18:['DL','DR'],19:[],20:['GK'],21:['GK']};
  ok(B.PLAYSTYLES.length===21,'current playstyle enum including No Playstyle contains IDs 1..21');
  B.PLAYSTYLES.forEach((ps,i)=>ok(ps.id===i+1,`playstyle enum id ${i+1} stable`));
  for(const [id,roles] of Object.entries(psExpected))eq(B.PLAYSTYLES.find(x=>x.id===Number(id)).roles,roles,`playstyle ${id} current eligibility exact`);
  ok(B.PLAYSTYLES.find(x=>x.id===19).offer===false,'Ball Playing GK enum remains recorded but not offered');
  ok(!D.PLAYSTYLES.includes('Ball Playing GK'),'Ball Playing GK not selectable');
  eq(D.playstylesForRoles(['MC']).sort(),['Box-to-Box','Mezzala','Regista'].sort(),'MC playstyle chooser exact');
  ok(D.playstylesForRoles(['DL','DC']).includes('Ball Playing DC'),'DL/DC player can select Ball Playing DC when DC is a natural role');
  ok(D.SPECIAL_ABILITIES.length===19,'19 current special abilities');eq(B.SPECIAL_ABILITIES.map(x=>x.id),Array.from({length:19},(_,i)=>i+1),'special ability IDs 1..19 exact');
  ok(D.SPECIAL_ABILITIES.includes('Shadow Striker'),'Shadow Striker present in current display list');ok(!D.SPECIAL_ABILITIES.includes('Long Shots'),'legacy Long Shots label hidden from current display list');ok(B.SPECIAL_ABILITIES.some(x=>x.name==='Long Shots'),'raw build enum retains Long Shots provenance');
  const abilityHeavy=P.cleanPlayer({name:'Abilities',position:'ST',roles:['ST'],skills:skills(),specialAbilities:D.SPECIAL_ABILITIES.slice(0,5)});ok(abilityHeavy.specialAbilities.length===5,'special ability storage is not capped at two');

  // ---------------------------------------------------------------------------
  // Scanner v12 Gemini 3.1 Flash Live boundary: compact renderer double-confirm + coloured SA refs.
  // ---------------------------------------------------------------------------
  ok(SC.VERSION===12,'Scanner v12 is the production scanner');
  const scannerSource=fs.readFileSync(path.join(ROOT,'js','scanner-engine.js'),'utf8');
  ok(/Gemini Scanner is not configured/.test(scannerSource),'scanner requires a configured Gemini API key');
  ok(/gemini-3\.1-flash-live-preview/.test(scannerSource),'scanner uses Gemini 3.1 Flash Live');
  ok(/thinkingLevel:'HIGH'/.test(scannerSource),'scanner uses HIGH thinking');
  ok(/compact-reference-manifest\.json/.test(scannerSource)&&/compactPlaystyleStateMedia/.test(scannerSource)&&/buildPlaystyleLevelEvidence/.test(scannerSource),'scanner uses compact renderer manifest, direct compact level PNGs and isolated level evidence');
  ok(/buildAbilityReference/.test(scannerSource)&&/NO gold\/boosted reference path/.test(scannerSource),'scanner uses coloured-only exact Special Ability references');
  ok(/submit_playstyle_identity/.test(scannerSource)&&/submit_playstyle_level/.test(scannerSource)&&/submit_playstyle_level_confirmation/.test(scannerSource)&&/submit_playstyle_overlay/.test(scannerSource),'playstyle identity, compact level, mandatory confirmation and overlays are separate Live passes');
  ok(/submit_ability_slot_scan/.test(scannerSource)&&/Ability slot/.test(scannerSource),'Special Abilities are classified per occupied slot');
  ok(SC.REQUEST_TIMEOUT_MS===90000,'scanner Live task timeout is 90 seconds');
  ok(SC._canonicalPlaystyle('Box To Box')==='Box-to-Box','scanner maps visual Box To Box to app canonical playstyle');
  for(const name of ['David Andrews','François Roelandt','Ariel Bravo','Richard Kilroy'])ok(!scannerSource.includes(name),'production scanner contains no benchmark player answers: '+name);
  ok(!/models\/[^`]*:generateContent/.test(scannerSource),'production scanner does not use generateContent transport');
  ok(!/scanner-templates|reconcileReadToTarget|classifyGlyph|function readNumber/.test(scannerSource),'legacy local digit-template/repair engine is absent');
  ok(!fs.existsSync(path.join(ROOT,'js','scanner-templates.json')),'legacy scanner template file is not packaged');

  // ---------------------------------------------------------------------------
  // Exact pitch geometry and target-role Role Score.
  // ---------------------------------------------------------------------------
  const expectedRects={GK:[0,143,250,750],DL:[179,393,0,250],DC:[143,286,250,750],DR:[179,393,750,1000],DMC:[286,429,250,750],ML:[393,607,0,250],MC:[429,572,250,750],MR:[393,607,750,1000],AML:[607,821,0,250],AMC:[572,715,250,750],AMR:[607,821,750,1000],ST:[715,858,250,750]};
  for(const [r,v] of Object.entries(expectedRects)){eq([B.ROLE_RECTS[r].minX,B.ROLE_RECTS[r].maxX,B.ROLE_RECTS[r].minY,B.ROLE_RECTS[r].maxY],v,`role rectangle ${r} exact`);const c=F.candidate(player('p'+r,r,[r]),r),placed=F.applyCoordinates([c])[0];ok(Number.isInteger(placed.x)&&Number.isInteger(placed.y)&&inside(r,placed.x,placed.y),`${r} generated coordinate stored inside half-open role rectangle`);}
  for(const role of currentRoles){for(const n of [2,3]){const cs=Array.from({length:n},(_,i)=>F.candidate(player(`${role}${i}`,`${role}${i}`,[role]),role));const placed=F.applyCoordinates(cs),rr=B.ROLE_RECTS[role],expected=Array.from({length:n},(_,i)=>Math.max(rr.minY,Math.min(rr.maxY-1,Math.round(rr.minY+(i+1)*(rr.maxY-rr.minY)/(n+1)))));eq(placed.map(x=>x.y),expected,`${role} ${n}-player repeated-role spacing exact/deterministic`);ok(placed.every(x=>inside(role,x.x,x.y)),`${role} repeated-role coords stay inside rectangle`);}}
  const rsA=player('r1','R1',['ST'],{Shooting:150,Finishing:140}),rsB={...player('r2','R2',['ST'],{Shooting:150,Finishing:140}),ovr:250};near(F.roleMean(rsA,'ST'),F.roleMean(rsB,'ST'),1e-12,'OVR never affects Role Score');near(F.roleMean(rsA,'ST'),D.POSITION_WHITE.ST.map(a=>rsA.skills[a]).reduce((a,b)=>a+b,0)/D.POSITION_WHITE.ST.length,1e-12,'Role Score is arithmetic mean of exact target-role key skills');
  ok(F.suitability(player('x','X',['MC'],{},['DMC']),'DMC')==='RELATED','related-role candidate comes only from player data');ok(F.suitability(player('x','X',['MC']),'DMC')==='WRONG','unlisted target role is WRONG and excluded');
  const formationSource=fs.readFileSync(path.join(ROOT,'js','formation.js'),'utf8');ok(!/ADJ|adjacen|0\.55|\.55\s*\+|0\.35/.test(formationSource),'old adjacency/OVR weighted formation model does not survive');

  // Global XI assignment beats or equals greedy on a crafted versatile-player case and never duplicates a player.
  const fixed=[player('gk','GK',['GK']),player('dl','DL',['DL']),player('dc1','DC1',['DC']),player('dc2','DC2',['DC']),player('dr','DR',['DR']),player('ml','ML',['ML']),player('mr','MR',['MR'])];
  const vBase=skills(100);for(const a of D.POSITION_WHITE.MC)vBase[a]=180;for(const a of ['Finishing','Heading','Strength'])vBase[a]=400;const versatile={...player('v','Versatile',['MC','ST']),skills:vBase};
  const m1=player('m1','M1',['MC'],Object.fromEntries(D.POSITION_WHITE.MC.map(a=>[a,179]))),m2=player('m2','M2',['MC'],Object.fromEntries(D.POSITION_WHITE.MC.map(a=>[a,178]))),s1=player('s1','S1',['ST'],Object.fromEntries(D.POSITION_WHITE.ST.map(a=>[a,100]))),s2=player('s2','S2',['ST'],Object.fromEntries(D.POSITION_WHITE.ST.map(a=>[a,90])));
  const crafted=[...fixed,versatile,m1,m2,s1,s2],form=F.FORMATIONS.find(x=>x.id==='442'),globalAssign=F.assign(crafted,form),greedy=greedyScore(crafted,form);ok(!globalAssign.error,'global assignment completes');ok(globalAssign.chosen.length===11&&new Set(globalAssign.chosen.map(x=>x.player.key)).size===11,'global assignment cannot assign one player twice');ok(globalAssign.sumMean>=greedy,'global assignment beats/equals greedy baseline');
  eq(B.FORMATION_TEMPLATES.map(x=>x.id),['442','433','4231','352','41212'],'internal proven baseline formation templates remain unchanged');
  eq(F.COMMUNITY_FORMATIONS.map(x=>x.id),['4141','31411','31213'],'v0.4.6 retains only the three provenance-labelled 2026 community candidate shapes');
  eq(F.FORMATIONS.map(x=>x.id),['41131','41311','4231','4123','433','4141','442','41212','31411','3142','352','31213'],'v0.5.12 formation optimiser consumes all 12 v2 candidate families from the authoritative contract');
  const coverageProbe=SCOV.analyse(crafted);ok(coverageProbe.model==='squad-coverage-v3-calibrated-v0515'&&coverageProbe.coveragePercent>0,'squad coverage engine returns deterministic blueprint coverage');ok(coverageProbe.roles.find(x=>x.role==='DMC').deficit>0,'coverage engine identifies missing natural DMC depth in crafted squad');
  ok(coverageProbe.availabilityDepthSlots.length===4,'squad blueprint implements all four v2 availability/rotation-depth slots');
  eq(coverageProbe.coverageBreakdown.weights,{core:.7,flexibility:.2,availabilityDepth:.1},'squad blueprint uses the contracted 70/20/10 core-flexibility-depth weights');
  near(coverageProbe.coveragePercent/100,coverageProbe.coverageBreakdown.core*.7+coverageProbe.coverageBreakdown.flexibility*.2+coverageProbe.coverageBreakdown.availabilityDepth*.1,1e-12,'squad blueprint overall coverage is the weighted three-layer score');
  const coreCoverageKeys=new Set(coverageProbe.coreSlots.map(x=>x.player?.playerKey).filter(Boolean));ok(coverageProbe.availabilityDepthSlots.filter(x=>x.player).every(x=>!coreCoverageKeys.has(x.player.playerKey)),'availability depth cannot reuse a player consumed by the core assignment');
  const strategicRank=F.rankStrategic(crafted);ok(strategicRank[0].strategic&&Number.isFinite(strategicRank[0].strategic.totalScore),'formation strategic ranking exposes transparent total/components');
  // v0.5.12 dynamic fallback contract: if the curated 12 cannot be fielded, enumerate exact build-30527 hard-legal natural-role shapes.
  ok(F.enumerateLegalFallbackFormations().length===2843,'dynamic formation fallback enumerates all 2,843 recovered hard-legal role-count shapes');
  const fallbackSquad=[player('fgk','FGK',['GK']),player('fdl','FDL',['DL']),player('fdc1','FDC1',['DC']),player('fdc2','FDC2',['DC']),player('fdr','FDR',['DR']),player('fdmc1','FDMC1',['DMC']),player('fdmc2','FDMC2',['DMC']),player('fmc','FMC',['MC']),player('famc','FAMC',['AMC']),player('fst1','FST1',['ST']),player('fst2','FST2',['ST'])];
  ok(F.FORMATIONS.every(x=>F.assign(fallbackSquad,x).error),'fallback fixture deliberately cannot field any of the 12 curated formation families');
  const fallbackRank=F.rankStrategic(fallbackSquad),fallbackBest=fallbackRank[0];ok(!fallbackBest.error&&fallbackBest.formation.dynamic&&fallbackBest.formation.naturalOnly,'automatic formation selection falls back to a hard-legal natural-role dynamic XI when curated families are unavailable');
  eq(fallbackBest.formation.roleCounts,{DL:1,DC:2,DR:1,DMC:2,ML:0,MC:1,MR:0,AML:0,AMC:1,AMR:0,ST:2},'dynamic fallback preserves the only fieldable recovered hard-legal role-count shape');
  const restoredFallback=F.rankStrategic(fallbackSquad,{templateId:fallbackBest.formation.id})[0];ok(!restoredFallback.error&&restoredFallback.formation.id===fallbackBest.formation.id,'saved dynamic fallback formation ID can be resolved and rebuilt deterministically');
  const tieBase={strategic:{totalScore:80,components:{weakLinkScore:12,lineupQualityScore:25,playstyleRoleFitScore:8,formationFlexibilityScore:6}}};
  ok(F.compareFormation({...tieBase,formation:{id:'b'}},{...tieBase,strategic:{...tieBase.strategic,components:{...tieBase.strategic.components,playstyleRoleFitScore:9}},formation:{id:'a'}})>0,'formation exact tie-break prefers higher Playstyle-role fit after weak-link and lineup quality');
  ok(F.compareFormation({...tieBase,formation:{id:'b'}},{...tieBase,strategic:{...tieBase.strategic,components:{...tieBase.strategic.components,formationFlexibilityScore:7}},formation:{id:'a'}})>0,'formation exact tie-break then prefers higher natural-role flexibility');
  ok(F.compareFormation({...tieBase,formation:{id:'z',source:'community-2026'}},{...tieBase,formation:{id:'y',source:'native-frontier-9'}})>0&&F.compareFormation({...tieBase,formation:{id:'z',source:'native-frontier-9'}},{...tieBase,formation:{id:'x',source:'native-frontier-7',baseline:true}})>0,'formation exact tie-break preserves baseline then native-frontier stability');
  ok(F.compareFormation({...tieBase,formation:{id:'b'}},{...tieBase,formation:{id:'a'}})>0,'formation final exact tie-break uses stable candidate id rather than incidental array order');
  const targetMan=player('tm','Target',['ST'],{},[],{type:'TARGET_MAN',level:3}),tmProfile=STRAT.trainingPriorityProfile(targetMan);ok(tmProfile.priorities.find(x=>x.attribute==='Heading').weight>tmProfile.priorities.find(x=>x.attribute==='Dribbling').weight,'Target Man hierarchy elevates aerial/hold-up white skills');
  const flatPoacher=player('flat-poacher','Flat Poacher',['ST'],Object.fromEntries(D.POSITION_WHITE.ST.map(a=>[a,150])),[],{type:'POACHER',level:3}),flatProfile=STRAT.trainingPriorityProfile(flatPoacher),flatNeeds=T.buildNeeds(D.POSITION_WHITE.ST,flatPoacher.skills,flatProfile.priorities,D.POSITION_WHITE.ST);ok(flatNeeds.targets.Finishing>flatNeeds.targets.Passing&&flatNeeds.targets.Shooting>flatNeeds.targets.Strength,'Role+Playstyle target shape deliberately tilts Poacher scoring skills above lower-value white skills');ok(flatNeeds.gaps.Finishing>30&&flatNeeds.gaps.Passing<1e-9,'flat Poacher creates strong catch-up pressure on S-tier scoring skills without equalising B-tier white skills');ok(flatNeeds.need.Passing<1&&flatNeeds.need.Finishing>50,'zero-gap lower-tier white skill falls to the small maintenance floor while an under-target signature skill dominates training need');const relatedRolePoacher=player('related-poacher','Related Poacher',['ST'],{},['AMC'],{type:'FALSE_NINE',level:3}),relatedRoleProfile=STRAT.trainingPriorityProfile(relatedRolePoacher,{roles:['ST'],developmentRole:'AMC'});ok(relatedRoleProfile.requestedDevelopmentRole==='AMC'&&relatedRoleProfile.developmentRole==='ST'&&relatedRoleProfile.developmentRoleFallbackReason==='assigned-role-not-natural','Training never pretends a related-only Team Plan assignment is a natural development role; it records the fallback explicitly');const shapedPoacher=player('shaped-poacher','Shaped Poacher',['ST'],{Shooting:195,Finishing:195,Positioning:190,Speed:185,Dribbling:160,Creativity:160,Passing:150,Heading:150,Strength:150},[],{type:'POACHER',level:3}),shapedProfile=STRAT.trainingPriorityProfile(shapedPoacher),shapedNeeds=T.buildNeeds(D.POSITION_WHITE.ST,shapedPoacher.skills,shapedProfile.priorities,D.POSITION_WHITE.ST);ok(shapedNeeds.gaps.Shooting<flatNeeds.gaps.Shooting&&shapedNeeds.need.Shooting<flatNeeds.need.Shooting,'signature skill catch-up pressure falls once the player already reaches the desired Poacher tilt');
  const falseNine=player('f9','False Nine',['ST'],{},[],{type:'FALSE_NINE',level:3}),f9Profile=STRAT.trainingPriorityProfile(falseNine);ok(f9Profile.priorities.find(x=>x.attribute==='Passing').weight>f9Profile.priorities.find(x=>x.attribute==='Heading').weight,'False Nine hierarchy elevates passing/creative white skills');

  // ---------------------------------------------------------------------------
  // Tactics exact recovered enums/drain arithmetic + exhaustive search checksums.
  // ---------------------------------------------------------------------------
  const tacticExpected={
    passing:[['short',0,7],['long',1,0],['mixed',2,5]],shooting:[['sight',0,0],['box',1,7],['balanced',2,5]],focus:[['left',0,0],['right',1,0],['both',2,7],['center',3,0],['balanced',4,5]],cross:[['low',0,0],['medium',1,0],['high',2,0]],lost:[['counterPress',0,7],['regroup',1,5]],won:[['buildup',0,5],['counter',1,7]],mentality:[['hardDefending',0,7],['defending',1,5],['normal',2,0],['attacking',3,5],['hardAttacking',4,7]],marking:[['man',0,7],['zonal',1,5]],pressing:[['low',0,0],['mid',1,5],['high',2,7]],backLine:[['track',0,5],['offside',1,0]],tackling:[['balanced',0,0],['stay',1,7],['aggressive',2,5]]
  };
  for(const [dim,rows] of Object.entries(tacticExpected))eq(B.TACTICS[dim].map(x=>[x.key,x.id,x.drain]),rows,`tactics ${dim} enum IDs/drain exact`);
  ok(TAC.DIMENSIONS.length===11,'tactics engine has all 11 settings');ok(TAC.option('tackling','stay').drain===7,'Stay On Feet recovered High drain contribution preserved');ok(B.TACTICS.cross.every(x=>x.drain===0),'all Cross Tendency choices recovered Low contribution preserved');
  const lowValues={passing:'long',shooting:'sight',focus:'left',cross:'low',lost:'regroup',won:'buildup',mentality:'normal',marking:'zonal',pressing:'low',backLine:'offside',tackling:'balanced'};const lowDrain=TAC.calculateDrain(lowValues);ok(lowDrain.rawScore===30&&lowDrain.normalized===.30&&lowDrain.drainClass==='Low','exact drain formula starts at 15 and sums 0/5/7 contributions');
  ok(TAC.minimumRawDrain()===30,'drain-efficiency floor is derived from the recovered build-30527 table and equals raw drain 30');
  ok(TAC.drainEfficiency(30,'Low')===10&&TAC.drainEfficiency(30,'Medium')===10&&TAC.drainEfficiency(30,'High')===10,'theoretical minimum raw drain earns the full 10-point efficiency component at every drain limit');
  ok(TAC.drainEfficiency(40,'Low')===0&&TAC.drainEfficiency(65,'Medium')===0&&TAC.drainEfficiency(100,'High')===0,'each selected drain ceiling maps to zero efficiency points');
  ok(TAC.drainEfficiency(35,'Low')>0&&TAC.drainEfficiency(35,'Low')<10,'drain efficiency interpolates strictly between the exact floor and selected ceiling');
  ok(TAC.resolveDrainContribution(0,'High')===7&&TAC.resolveDrainContribution(7,null)===7,'drain override architecture accepts known intensities without inventing overrides');
  const chk=TAC.drainChecksums();eq(chk.all,{Low:963,Medium:77823,High:18414},'full drain class checksum exact');ok(chk.total===97200,'full tactic grid contains 97,200 combinations');
  const perMentality={hardDefending:{Low:36,Medium:14388,High:5016},defending:{Low:111,Medium:15606,High:3723},normal:{Low:669,Medium:17835,High:936},attacking:{Low:111,Medium:15606,High:3723},hardAttacking:{Low:36,Medium:14388,High:5016}};
  for(const m of B.TACTICS.mentality){let n=0;TAC.enumerate(()=>n++,m.key);ok(n===19440,`${m.label}: fixed mentality search space is exactly 19,440`);eq(chk.perMentality[m.key],perMentality[m.key],`${m.label}: drain-class checksum exact`);}
  // v0.5.0 tactics evidence pass: exact drain stays untouched; recommendation heuristics stop pretending Approach is a hidden weight on every setting.
  const tacticStarters=[['GK',500],['DL',100],['DC',400],['DC',600],['DR',900],['ML',100],['MC',400],['MC',600],['MR',900],['ST',400],['ST',600]].map(([role,y],i)=>({assignedRole:role,x:500,y,player:player(`t${i}`,`T${i}`,[role])}));
  const balancedFits=TAC.optionFits(tacticStarters,'balanced'),attackingFits=TAC.optionFits(tacticStarters,'attacking');
  ok(!('approachFit' in balancedFits.fits.passing.short)&&balancedFits.fits.passing.short.optionFit===balancedFits.fits.passing.short.squadFit,'Approach no longer injects invented style weights into non-mentality tactics');
  near(balancedFits.fits.passing.short.optionFit,attackingFits.fits.passing.short.optionFit,1e-12,'same XI has same non-mentality squad fit across approaches');
  near(balancedFits.raw.marking.man,balancedFits.raw.marking.zonal,1e-12,'own XI keeps raw marking support neutral because matchup efficacy is outside this app input model');
  const symmetricPlan=TAC.recommend(tacticStarters,{approach:'balanced',drainLimit:'Medium'});ok(symmetricPlan.values.focus==='left'&&balancedFits.raw.focus.left===balancedFits.raw.focus.right&&balancedFits.raw.focus.right===balancedFits.raw.focus.center,'v0.5.12 total-score tie follows the contracted lower-drain then stable-order policy when all lane support is exactly equal');
  ok(symmetricPlan.values.marking==='zonal','marking uses the transparent lower-drain neutral fallback when no own-squad feasibility rule outweighs it');
  const autoPlan=TAC.recommendAuto(tacticStarters,{drainLimit:'Medium'});ok(autoPlan.autoSelected&&Number.isFinite(autoPlan.decisionScore),'automatic tactics evaluates approach + structure + drain as one decision');ok(autoPlan.contextFit&&Array.isArray(autoPlan.contextFit.reasons),'automatic tactics exposes community/structure context reasons');
  ok(TAC.MODEL_VERSION==='30527-drain-fit-v5-calibrated-v0515-affinity-dedup'&&/No external-team or live-state inputs/.test(symmetricPlan.evidencePolicy),'v0.5.15 calibrated tactics remains inside the own-squad runtime boundary');
  const activeDecisionSources=['strategy-logic.js','formation.js','tactics-engine.js','mentor-engine.js','team-plan-engine.js','app.js'].map(x=>fs.readFileSync(path.join(ROOT,'js',x),'utf8')).join('\n');ok(!/opponentSlots|opponentAttack|opponentPassing|relativeStrength|strength\.band|matchState|cardRisk|weakZoneKnown/.test(activeDecisionSources),'active v0.5.15 calibration runtime exposes no external-team/relative-strength/live-state input symbols');
  ok(STRAT.CONFIG.version==='v0.5.15-calibration'&&!('strength_bands' in STRAT.CONFIG)&&!('opponent_features' in STRAT.CONFIG.feature_model),'v2 contract is v0.5.15-calibration own-squad-only and contains no external feature model');
  const zeroIdentityContext=STRAT.buildContext(tacticStarters,symmetricPlan.values);ok(STRAT.conditionMatches('playstyles.TargetMan == 0 && abilities.CrossExpert == 0',zeroIdentityContext),'generic evaluator treats absent Playstyle/SA identities as zero counts');

  // ---------------------------------------------------------------------------
  // Team Plan dependency: formation -> tactics -> mentor; approach/drain never reshuffle XI.
  // ---------------------------------------------------------------------------
  for(const k of await S.list('player:'))await S.del(k);await S.del(P.MIGRATION_KEY);await S.del(TP.KEY);await P.migrate();
  await S.setJSON(TP.KEY,{version:5,formationModel:F.MODEL_VERSION,strategyModel:STRAT.MODEL_VERSION,coverageModel:SCOV.MODEL_VERSION,squadRevision:'old'});ok(await TP.load()===null,'v0.5.15 rejects persisted Team Plan schema v5 from the pre-calibration generation');
  const squad=[player(null,'GK',['GK']),player(null,'DL',['DL']),player(null,'DC A',['DC']),player(null,'DC B',['DC']),player(null,'DR',['DR']),player(null,'ML',['ML']),player(null,'MC A',['MC']),player(null,'MC B',['MC']),player(null,'MR',['MR']),player(null,'ST A',['ST']),player(null,'ST B',['ST']),player(null,'Bench AM',['AMC'])];
  squad[6].playstyle={type:'BOX_TO_BOX',level:3,points:2000};squad[9].specialAbilities=['Penalty Kick Specialist'];
  for(const sp of squad){const k=await P.save(sp);sp.key=k;}
  let plan=await TP.buildFormation({templateId:'442',mode:'bestXI'});ok(plan.starters.length===11,'Team Plan formation built');ok(plan.bench.length===1,'Team Plan bench stored');ok(plan.starters.every(s=>Number.isInteger(s.x)&&Number.isInteger(s.y)&&inside(s.assignedRole,s.x,s.y)),'Team Plan stores exact integer X/Y inside assigned role rectangles');
  const lineupBefore=plan.starters.map(x=>x.playerKey+'@'+x.assignedRole+'@'+x.x+','+x.y);
  M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:true,level:10}])));
  plan=await TP.updateRecommendations({approach:'balanced',drainLimit:'Medium'});eq(plan.starters.map(x=>x.playerKey+'@'+x.assignedRole+'@'+x.x+','+x.y),lineupBefore,'initial tactics/mentor recommendation leaves formation unchanged');ok(plan.tactics.evaluatedCandidates===19440,'chosen mentality actually enumerates all 19,440 tactic candidates');
  plan=await TP.updateRecommendations({approach:'attacking',drainLimit:'High'});eq(plan.starters.map(x=>x.playerKey+'@'+x.assignedRole+'@'+x.x+','+x.y),lineupBefore,'Approach/Drain change recalculates tactics/mentor without reshuffling formation');ok(plan.tactics.values.mentality==='attacking','Approach locks exact corresponding mentality');ok(['Low','Medium','High'].includes(plan.tactics.drainClass),'exact drain class stored in Team Plan');
  ok(plan.mentor.best&&plan.mentor.alternatives.length>=2,'mentor returns best plus at least two alternatives');ok(plan.mentor.alternatives.every(x=>typeof x.reason==='string'&&x.reason.length>0),'mentor alternatives include why-not reasons');
  ok(TP.VERSION===6,'v0.5.15 calibration Team Plan persistence schema is v6 so pre-calibration cached plans cannot leak forward');
  ok(SCOV.MODEL_VERSION==='squad-coverage-v3-calibrated-v0515','calibrated Squad Blueprint exports its model fingerprint for Team Plan cache validation');
  const currentFingerprint={version:TP.VERSION,gameDataVersion:D.GAME_DATA_VERSION,formationModel:F.MODEL_VERSION,strategyModel:STRAT.MODEL_VERSION,coverageModel:SCOV.MODEL_VERSION,tactics:{values:{}},tacticsModel:TAC.MODEL_VERSION,mentor:{},mentorModel:M.MODEL_VERSION,setPieces:{model:R.SET_PIECE_MODEL},setPieceModel:R.SET_PIECE_MODEL};ok(TP.modelsCurrent(currentFingerprint),'current complete Team Plan model fingerprint is accepted');ok(!TP.modelsCurrent({...currentFingerprint,tacticsModel:'old-tactics-model'}),'stale Tactics model invalidates an otherwise current Team Plan cache');ok(!TP.modelsCurrent({...currentFingerprint,strategyModel:'old-strategy-model'}),'stale Strategy model invalidates an otherwise current Team Plan cache');ok(!TP.modelsCurrent({...currentFingerprint,coverageModel:'old-coverage-model'}),'stale Blueprint model invalidates an otherwise current Team Plan cache');ok(!TP.modelsCurrent({...currentFingerprint,gameDataVersion:'old-game-data'}),'stale game-data version invalidates an otherwise current Team Plan cache');
  const optimal=await TP.buildOptimalPlan({drainLimit:'Medium'});ok(optimal.jointPlan&&Number.isFinite(optimal.jointPlan.totalScore),'joint planner scores Formation + Tactics + level-gated Mentor together');ok(optimal.squadCoverage&&Array.isArray(optimal.squadCoverage.recruitmentPriorities),'joint planner carries optimal-coverage/recruitment guidance');ok(optimal.setPieces?.assignments?.captain&&optimal.setPieces?.model==='set-piece-companion-v3-captain-neutral','joint planner carries a complete automatic set-piece package including Captain');ok(Array.isArray(optimal.development)&&optimal.development.length===11&&optimal.development.every(x=>x.assignedRole&&x.priorities?.length),'winning Team Plan carries per-starter Role+Playstyle development context');const fixedApproach=await TP.buildOptimalPlan({drainLimit:'Medium',approach:'attacking'});ok(fixedApproach.approach==='attacking'&&fixedApproach.tactics&&!fixedApproach.tactics.error,'fixed tactical Approach still jointly evaluates complete Formation/Tactics candidates');

  // Mentor v0.5.3 state model: account screenshots are research evidence, not runtime defaults.
  ok(B.MENTORS.length===7,'exactly seven documented mentors');
  ok(B.MENTORS.every(x=>x.level===undefined&&x.xp===undefined&&x.xpNext===undefined),'runtime Mentor definitions contain no captured account level/XP defaults');
  ok(B.MENTORS.every(x=>x.tactic.current===undefined&&x.attribute.current===undefined&&x.signature.current===undefined),'captured effect arrays are not reused as selected-level runtime magnitudes');
  const hydrated=await TP.hydrateStarters(plan),architect=B.MENTORS.find(x=>x.id==='architect'),analyst=B.MENTORS.find(x=>x.id==='analyst');
  M.setStateOverrides({architect:{unlocked:false,level:10}});ok(M.direct(M.effectiveMentor(architect),{values:{passing:'short'}},'Balanced',{})===0,'locked Mentor contributes no Tactical effect');
  M.setStateOverrides({architect:{unlocked:true,level:1}});let eff=M.effectiveMentor(architect);eq(M.activeFamilies(eff),{tactic:true,attribute:false,signature:false},'Level 1 unlocks Tactical family only');ok(M.direct(eff,{values:{passing:'short'}},'Balanced',{})===3,'unlocked Architect has Short Pass semantic synergy');ok(M.attributeCoverage(eff,hydrated).hits===0,'Attribute family is inactive below Level 5');
  M.setStateOverrides({architect:{unlocked:true,level:5}});eff=M.effectiveMentor(architect);eq(M.activeFamilies(eff),{tactic:true,attribute:true,signature:false},'Level 5 unlocks Attribute family');ok(M.attributeCoverage(eff,hydrated).hits>0,'Level 5 active Attribute family can contribute role-key coverage');
  const saNeutralMentorXI=hydrated.map(x=>({...x,player:{...x.player,specialAbilities:[...(x.player.specialAbilities||[])]}})),saMentorTarget=saNeutralMentorXI.find(x=>x.assignedRole==='ST');const mentorBaseCoverage=M.attributeCoverage(eff,saNeutralMentorXI,plan.tactics);saMentorTarget.player.specialAbilities=[...(saMentorTarget.player.specialAbilities||[]),'Shadow Striker'];const mentorSACoverage=M.attributeCoverage(eff,saNeutralMentorXI,plan.tactics);near(mentorSACoverage.rawRelevance,mentorBaseCoverage.rawRelevance,1e-12,'Special Ability training modifiers cannot leak into Mentor attribute relevance; only hierarchy plus tactic context is authorised');
  M.setStateOverrides({architect:{unlocked:true,level:10}});eff=M.effectiveMentor(architect);eq(M.activeFamilies(eff),{tactic:true,attribute:true,signature:true},'Level 10 unlocks Signature family');ok(M.rawEffects(eff).tactic.magnitude==='UNRESOLVED FOR SELECTED LEVEL','selected-level Mentor magnitude remains explicitly unresolved');
  M.setStateOverrides({saboteur:{unlocked:true,level:5}});let gated=M.recommend(hydrated,{...plan.tactics,values:{...plan.tactics.values,won:'counter'}});ok(gated.best&&gated.all.find(x=>x.mentor.id==='saboteur').signatureScore===0,'locked Level-10 Signature contributes exactly zero at Mentor Level 5');
  M.setStateOverrides({saboteur:{unlocked:true,level:10}});gated=M.recommend(hydrated,{...plan.tactics,values:{...plan.tactics.values,won:'counter'}});ok(gated.all.find(x=>x.mentor.id==='saboteur').signatureScore===3,'unlocked Blind Side contributes only in matching counter context');
  M.setStateOverrides({analyst:{unlocked:true,level:1}});ok(M.direct(M.effectiveMentor(analyst),{values:{passing:'long'}},'Balanced',{})===3,'Analyst exact Long Pass semantic synergy');
  const enforcer=B.MENTORS.find(x=>x.id==='enforcer');M.setStateOverrides({enforcer:{unlocked:true,level:10}});const enf=M.recommend(hydrated,plan.tactics);ok(enf.best&&enf.all[0].tacticalPoints===0&&enf.all[0].signaturePoints===0,'Makélélé contextual Tactical/Signature families receive zero speculative pre-match credit');
  const outsideBand=TP.jointScore({strategic:{totalScore:50}},{decisionScore:50},{best:{planAdjustment:10}},{bestCore:70}),insideBand=TP.jointScore({strategic:{totalScore:65}},{decisionScore:65},{best:{planAdjustment:10}},{bestCore:70});ok(!outsideBand.viable&&outsideBand.mentorAdjustment===0&&insideBand.viable&&insideBand.mentorAdjustment===10,'Mentor adjustment cannot rescue a core plan outside the 10-point viable band');
  M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:false,level:1}])));const none=M.recommend(hydrated,plan.tactics);ok(none.error==='no-unlocked-mentors'&&!none.best,'all-locked Mentor state produces no fabricated recommendation');
  M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:true,level:10}])));

  // ---------------------------------------------------------------------------
  // Individual Training Bible model.
  // ---------------------------------------------------------------------------
  await DP.resetToCapturedSnapshot();const normal=await DP.getNormal(),stock=await DP.getMaster();
  ok(D.NORMAL_DRILLS.length===29,'normal drill catalogue count = 29');ok(D.MASTER_CAMPUS_DRILLS.length===4,'Master/Campus catalogue count = 4');eq(D.DRILL_LEVELS.levels.map(x=>[x.level_id,x.training_effect_percent]),[[1,10],[2,20],[3,30]],'regular drill level effects exact');
  const intensityExpected=[[1,'Very Easy',1,.75],[2,'Easy',2,1.5],[3,'Medium',3,2.25],[4,'Hard',4,3],[5,'Very Hard',5,3.75]];eq((D.INTENSITY_SYSTEM.levels||D.INTENSITY_SYSTEM.intensities).map(x=>[x.id,x.ui_name,x.xp_per_player,x.condition_drop]),intensityExpected,'intensity XP/condition map exact');
  const fast=D.NORMAL_DRILLS.find(x=>x.drillId==='FAST_COUNTER_ATTACKS');ok(fast.xpPerPlayer===5&&fast.conditionDrop===3.75&&fast.diff==='Very Hard','Fast Counter-Attacks fixed catalogue exact');near(T.levelEffectPct(3),30,0,'World-class +30% exact');near(T.trainingStrength(1,30),1.3,1e-12,'Very Easy World-class effective training strength exact');near(T.trainingStrength(5,30),6.5,1e-12,'Very Hard World-class effective training strength exact');const sameNeed={Finishing:20,Shooting:20},easySame=T.scoreCandidate({whiteAttributes:['Finishing','Shooting'],strength:T.trainingStrength(2,30)},sameNeed,{}),hardSame=T.scoreCandidate({whiteAttributes:['Finishing','Shooting'],strength:T.trainingStrength(5,30)},sameNeed,{});ok(hardSame.score>easySame.score&&Math.abs(hardSame.score/easySame.score-2.5)<1e-12,'with identical useful white coverage and level effect, Very Hard strictly outranks Easy in Max Growth because verified base XP is 5 vs 2');
  const focusedEasy=T.scoreCandidate({whiteAttributes:['Finishing','Shooting'],strength:T.trainingStrength(2,30)},{Finishing:20,Shooting:20},{}),wastefulVeryHard=T.scoreCandidate({whiteAttributes:['Passing'],strength:T.trainingStrength(5,30)},{Passing:.2},{});ok(focusedEasy.score>wastefulVeryHard.score,'verified intensity is a gain-strength factor, not a blanket hardest-drill rule: precise high-need white coverage can outrank a harder low-need drill');
  const attMaster=D.MASTER_CAMPUS_DRILLS.find(x=>x.drillId==='ATTACKING_MASTERCLASS');ok(attMaster.xpPerPlayer===5&&attMaster.conditionDrop===3.75&&attMaster.additionalTrainingEffectPercent===80,'Master fixed catalogue exact');
  const stanek={name:'Jiri Stanek',age:23,ovr:115,position:'GK',roles:['GK'],skills:{Reflexes:127,Agility:159,Anticipation:136,'Rushing Out':128,Communication:141,Throwing:133,Kicking:135,Punching:137,'Aerial Reach':149,Concentration:132,Fitness:168,Strength:34,Aggression:42,Speed:54,Creativity:56}};
  const needs=T.buildNeeds(D.POSITION_WHITE.GK,stanek.skills);near(needs.target,136,1e-12,'training fallback target anchor uses the median normalized non-signature development whites, resisting outliers and signature self-chasing');const before=JSON.stringify(stanek.skills),session=T.buildIndividualSession({player:stanek,normalProfile:normal,masterStock:stock});ok(session.drills.length===6&&!session.error,'individual beam search returns exactly six legal slots');ok(session.meta.beamWidth===250&&session.meta.model==='30527-white-beam-v5-mode-depth','individual training target-shape/intensity-gain model and beam width exact');const efficient=T.buildIndividualSession({player:stanek,normalProfile:normal,masterStock:stock,mode:'conditionEfficient'});ok(efficient.meta.beamWidth===1000&&efficient.meta.mode==='conditionEfficient','Condition Efficient uses deeper beam width 1000 while Max Growth remains 250');ok(JSON.stringify(stanek.skills)===before,'individual training does not mutate player');ok(session.meta.greyAttributesAffectScore===false,'grey attributes have zero Individual Training utility');
  ok(session.meta.hierarchy&&session.meta.hierarchy.priorities.length===D.POSITION_WHITE.GK.length,'individual training stores full role/Playstyle hierarchy evidence');
  const tmSkills=Object.fromEntries(D.POSITION_WHITE.ST.map(a=>[a,100])),tmSessionPlayer=player('tmtrain','TM Train',['ST'],tmSkills,[],{type:'TARGET_MAN',level:3}),tmTrain=T.buildIndividualSession({player:tmSessionPlayer,normalProfile:normal,masterStock:stock});ok(tmTrain.meta.hierarchy.playstyle==='Target Man','training engine applies current player Playstyle hierarchy');
  const stackedTrainingTactic={passing:'short',shooting:'sight',focus:'left',cross:'low',lost:'counterPress',won:'buildup',mentality:'normal',marking:'man',pressing:'high',backLine:'offside',tackling:'stay'},stackedSignal=STRAT.tacticTrainingSignals('DL','Speed',stackedTrainingTactic);ok(stackedSignal.rawAdd>.20&&Math.abs(stackedSignal.add-.20)<=1e-12&&stackedSignal.capped,'training tactic-context stacking is capped at the contracted +20% even when raw matching modifiers exceed it');
  const session2=T.buildIndividualSession({player:stanek,normalProfile:normal,masterStock:stock});eq(session.drills.map(x=>x.drillId),session2.drills.map(x=>x.drillId),'individual beam search deterministic');
  const cat=T.evaluateCatalogue({player:stanek,normalProfile:normal,masterStock:stock});const gkRow=cat.rows.find(x=>x.candidate.drillId==='GOALKEEPER_TRAINING'),fcRow=cat.rows.find(x=>x.candidate.drillId==='FAST_COUNTER_ATTACKS');ok(gkRow.metric.whiteCoverageCount===5&&fcRow.metric.whiteCoverageCount===1&&gkRow.metric.score>fcRow.metric.score,'intense multi-white GK drill outranks one-white drill when useful utility is greater');
  const one=T.scoreCandidate({whiteAttributes:['A'],strength:5},{A:10},{}),multi=T.scoreCandidate({whiteAttributes:['A','B'],strength:5},{A:10,B:10},{});ok(multi.score>one.score,'multi-white coverage accumulates useful need rather than averaging it away');
  const allLocked={gameDataVersion:D.GAME_DATA_VERSION,drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:false,level:0}]))},masterTwo={stock:{ATTACKING_MASTERCLASS:2,MIDFIELD_MASTERCLASS:0,PHYSICAL_MASTERCLASS:0,DEFENDING_MASTERCLASS:0}},st=player('st','ST',['ST'],Object.fromEntries(D.POSITION_WHITE.ST.map(a=>[a,100])));const ms=T.buildIndividualSession({player:st,normalProfile:allLocked,masterStock:masterTwo});ok(ms.drills.length===2&&ms.meta.masterUsage.ATTACKING_MASTERCLASS===2&&ms.meta.remainingMasterStock.ATTACKING_MASTERCLASS===0,'Master duplicates cannot exceed owned stock');
  const oneNormal={gameDataVersion:D.GAME_DATA_VERSION,drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:d.drillId==='SLALOM_DRIBBLE',level:d.drillId==='SLALOM_DRIBBLE'?3:0}]))};const reps=T.buildIndividualSession({player:st,normalProfile:oneNormal,masterStock:{stock:{}}});ok(reps.drills.length===6&&new Set(reps.drills.map(x=>x.drillId)).size===1,'normal drill duplicates remain unlimited/legal');
  ok(session.meta.exactGainPrediction===false,'app explicitly does not predict exact server-side percentage-point gain');

  // ---------------------------------------------------------------------------
  // Team Training: actual players + per-player natural-role white needs + beam 250.
  // ---------------------------------------------------------------------------
  eq(D.TEAM_GROUPS,{defence:{title:'GK & Defence',positions:['GK','DL','DC','DR']},midfield:{title:'Defence & Midfield',positions:['DL','DC','DR','DMC','ML','MC','MR']},attack:{title:'Attacking Mid & Strikers',positions:['AML','AMC','AMR','ST']},all:{title:'All Positions',positions:currentRoles}},'Team Training groups exact');
  const teamPlayers=[player('a','Attacker',['ST'],{Passing:80,Dribbling:80,Shooting:80,Finishing:80,Positioning:80,Heading:80,Strength:80,Speed:80,Creativity:80}),player('keeper','Keeper',['GK'])];
  const tr=TT.buildTeamSession('attack',{normalProfile:normal,players:teamPlayers});ok(tr.drills.length===6&&tr.meta.selectedPlayerCount===1,'Team Training uses actual players in selected group');eq(tr.meta.selectedPlayerKeys,['a'],'Team Training excludes unrelated actual players');ok(tr.meta.beamWidth===250&&tr.meta.model==='30527-team-white-beam-v3-target-shape','Team Training uses six-slot beam search width 250 with verified intensity-gain strength');ok(tr.meta.greyAttributesAffectScore===false,'Team Training grey attributes have zero utility');ok(tr.meta.targetShapeAware===true,'Team Training uses the same Role+Playstyle target-shape need model as Individual Training');ok(tr.meta.apkTeamPlayModeled===false,'protocol TeamPlayTrainingDrill remains explicitly separate/unmodelled');
  const tr2=TT.buildTeamSession('attack',{normalProfile:normal,players:teamPlayers});eq(tr.drills.map(x=>x.drillId),tr2.drills.map(x=>x.drillId),'Team Training beam search deterministic');ok(TT.buildTeamSession('midfield',{normalProfile:normal,players:[teamPlayers[1]]}).error==='no-complete-players','Team Training does not fabricate players for an empty group');

  // ---------------------------------------------------------------------------
  // Specialists remain transparent companion-only logic.
  // ---------------------------------------------------------------------------
  const specA=player('pa','Penalty',['ST'],{Finishing:120,Shooting:120,Creativity:90});specA.specialAbilities=['Penalty Kick Specialist'];specA.ovr=130;const specB=player('pb','Raw Skill',['ST'],{Finishing:200,Shooting:200,Creativity:200});specB.ovr=120;const spEntries=[{player:specA,assignedRole:'ST',roleMean:120,roleFloor:90},{player:specB,assignedRole:'ST',roleMean:180,roleFloor:150}],rr=R.rankPlaymakers(spEntries);ok(rr.penalties[0].player.key==='pa','penalty specialist flag is first explicit lexicographic criterion');ok(rr.captain?.player?.key==='pa'&&/no proven gameplay effect/i.test(rr.captainNote),'Captain defaults to the highest-OVR starter only as a gameplay-neutral convenience, not as a performance formula');
  const fullSp=R.buildSetPiecePlan(spEntries);ok(fullSp.assignments.penalty1==='pa'&&fullSp.assignments.captain==='pa'&&fullSp.readiness.specialistCoverage===1&&fullSp.readiness.specialistTierSum===2&&fullSp.readiness.tieTuple.length===3,'complete set-piece package includes specialists and Captain, while Captain is excluded from readiness scoring');
  const autoSp=R.normaliseSetPieceState(null,spEntries);ok(autoSp.version===5&&autoSp.sources.penalty1==='auto'&&autoSp.sources.captain==='auto','v0.5.14 set-piece state records automatic provenance including Captain');ok(autoSp.assignments.penalty1==='pa'&&autoSp.assignments.captain==='pa','fresh automatic set-piece recommendation uses current complete-XI ranking');
  const manualSp=R.setManualSetPiece(autoSp,'penalty1','pb',spEntries),manualCaptain=R.setManualSetPiece(manualSp,'captain','pa',spEntries),preservedManual=R.normaliseSetPieceState(manualCaptain,spEntries);ok(preservedManual.assignments.penalty1==='pb'&&preservedManual.sources.penalty1==='manual'&&preservedManual.assignments.captain==='pa'&&preservedManual.sources.captain==='manual','manual set-piece and Captain overrides survive recalculation');
  const refreshedSp=R.refreshSetPieceRecommendations(manualCaptain,spEntries);ok(refreshedSp.assignments.penalty1==='pa'&&refreshedSp.assignments.captain==='pa'&&refreshedSp.sources.captain==='auto','explicit refresh replaces manual/legacy slots with current complete Team Plan recommendations');
  const migratedSp=R.normaliseSetPieceState({version:4,assignments:{penalty1:'pb',freeRight:'pb',captain:''},sources:{penalty1:'manual',freeRight:'auto',captain:'manual'}},spEntries);ok(migratedSp.assignments.penalty1==='pb'&&migratedSp.sources.penalty1==='manual'&&migratedSp.assignments.captain==='pa'&&migratedSp.sources.captain==='auto','v4 state migrates non-destructively while an unresolved blank Captain becomes automatic');
  const staleAuto={version:5,assignments:{...autoSp.assignments,penalty1:'pb'},sources:{...autoSp.sources,penalty1:'auto'}};const repairedAuto=R.normaliseSetPieceState(staleAuto,spEntries);ok(repairedAuto.assignments.penalty1==='pa','automatic set-piece slot is recalculated instead of going stale');
  const tieA={score:{totalScore:80,corePlanScore:75},setPieces:{readiness:{tieTuple:[0,0,300]}},tactics:{rawScore:40},formation:{strategic:{components:{weakLinkScore:10}},formation:{templateOrder:0}}},tieB={score:{totalScore:80,corePlanScore:75},setPieces:{readiness:{tieTuple:[1,1,250]}},tactics:{rawScore:35},formation:{strategic:{components:{weakLinkScore:9}},formation:{templateOrder:1}}};ok(TP.compareCandidates(tieA,tieB)>0,'set-piece readiness is a late tie-break after equal final/core plan score and before drain');ok(R.compareReadiness({readiness:{specialistCoverage:1,skillSum:300,captainDefaultOvr:200,tieTuple:[1,1,300]}},{readiness:{specialistCoverage:1,skillSum:300,captainDefaultOvr:50,tieTuple:[1,1,300]}})===0,'Captain quality contributes zero to Team Plan/set-piece readiness because captaincy has no proven gameplay effect');
  const liveCheap={score:{totalScore:80,corePlanScore:75},setPieces:{readiness:{tieTuple:[0,0,300]}},tactics:{drainProfile:T.DRAIN_PROFILE_LIVE,rawScore:null,mediumCount:1,highCount:0},formation:{strategic:{components:{weakLinkScore:10}},formation:{templateOrder:0}}},liveDear={score:{totalScore:80,corePlanScore:75},setPieces:{readiness:{tieTuple:[0,0,300]}},tactics:{drainProfile:T.DRAIN_PROFILE_LIVE,rawScore:null,mediumCount:2,highCount:1},formation:{strategic:{components:{weakLinkScore:10}},formation:{templateOrder:1}}};ok(TP.compareCandidates(liveCheap,liveDear)<0,'Joint Team Plan tie-break ignored a provably cheaper live intensity profile');

  // ---------------------------------------------------------------------------
  // v5.2.7 provenance-audit regressions: direct build-30527 native corrections.
  // ---------------------------------------------------------------------------
  eq(B.TACTICS.tackling.map(x=>[x.key,x.id,x.drain]),[['balanced',0,0],['stay',1,7],['aggressive',2,5]],'tackling protocol IDs/order match direct APK: Balanced=0, Stay=1, Aggressive=2 while label drain remains 0/7/5');
  ok(TAC.resolveDrainContribution(0,{intensity:0})===0&&TAC.resolveDrainContribution(0,{intensity:1})===5&&TAC.resolveDrainContribution(0,{intensity:2})===7,'numeric native ConditionDrainIntensity overrides map 0/1/2 -> 0/5/7');
  ok(TAC.resolveDrainContribution(0,1)===5&&TAC.resolveDrainContribution(0,2)===7,'raw numeric native intensity override compatibility');
  ok(!/levelSum/.test(String(F.assign))&&!/levelSum/.test(String(F.choose)),'formation whole-XI ranking no longer contains undocumented playstyle-level sum');

  console.log(`PASS ${passed} assertions`);
})().catch(err=>{console.error('FAIL',err.stack||err);process.exit(1)});
