const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={_m:new Map(),getItem(k){return this._m.has(k)?this._m.get(k):null},setItem(k,v){this._m.set(k,String(v))},removeItem(k){this._m.delete(k)},key(i){return [...this._m.keys()][i]||null},get length(){return this._m.size}};
for(const f of ['optimizer-data.js','data.js','scanner-engine.js','storage.js','drill-profile.js','players.js','training-engine.js','team-training-engine.js','recommendations.js','formation.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','js',f),'utf8'),{filename:f});
const {OptimizerData:OD,Data:D,Scanner:SC,Storage:S,DrillProfile:DP,Players:P,Training:T,TeamTraining:TT,Recommendations:R,Formation:F}=global.TE5;
let passed=0;function ok(cond,msg){if(!cond)throw new Error(msg);passed++;}function eq(a,b,msg){ok(JSON.stringify(a)===JSON.stringify(b),`${msg}\n${JSON.stringify(a)} != ${JSON.stringify(b)}`)}function near(a,b,e,msg){ok(Math.abs(a-b)<=e,`${msg}: ${a} vs ${b}`)}
(async()=>{
  ok(D.GAME_DATA_VERSION==='build_30527','game data version');ok(D.NORMAL_DRILLS.length===29,'29 authoritative normal drills');ok(D.MASTER_CAMPUS_DRILLS.length===4,'4 Master/Campus drills');ok(D.ALL_POSITIONS.length===14,'14 roles');
  for(const pos of D.ALL_POSITIONS)eq(D.POSITION_WHITE[pos],OD.whiteSkillMap.roles[pos].key_attributes,`white map exact for ${pos}`);
  eq(D.whiteSkillsForRoles(['DC','DR']),['Tackling','Marking','Positioning','Heading','Bravery','Fitness','Strength','Aggression','Crossing','Speed'],'multi-role white union preserves authoritative order');
  eq(D.applicableSkillsForRoles(['ST']),D.OUTFIELD_SKILLS,'outfield applicable pool is attributes 1-15');eq(D.applicableSkillsForRoles(['GK']),D.POSITION_WHITE.GK,'GK applicable pool is authoritative GK key pool');
  eq(D.DRILL_LEVELS.levels.map(x=>x.training_effect_percent),[10,20,30],'level effect mapping exact');
  const fast=D.NORMAL_DRILLS.find(d=>d.drillId==='FAST_COUNTER_ATTACKS');ok(fast.diff==='Very Hard'&&fast.xpPerPlayer===5&&fast.conditionDrop===3.75,'authoritative Fast Counter properties');
  const master=D.MASTER_CAMPUS_DRILLS.find(d=>d.drillId==='ATTACKING_MASTERCLASS');ok(master.additionalTrainingEffectPercent===80&&master.xpPerPlayer===5&&master.conditionDrop===3.75,'Master properties exact');

  const ovrRepair=SC.reconcileReadToTarget({value:111,candidates:[{value:111,score:.01},{value:105,score:.02}]},105.2,1.5);ok(ovrRepair.changed&&ovrRepair.read.value===105,'scanner OVR reconciliation only selects a recognised candidate that resolves the mismatch');
  const noInvent=SC.reconcileReadToTarget({value:111,candidates:[{value:111,score:.01},{value:109,score:.02}]},105.2,1.5);ok(!noInvent.changed&&noInvent.read.value===111,'scanner never invents an OVR when no recognised candidate reconciles');
  ok(SC.checkAggregate([100,100,100,100,100],106).ok===false,'scanner aggregate mismatch remains unresolved instead of silently passing');
  const alreadyValid=[{value:91,confidence:.92,candidates:[{value:91,score:.01},{value:31,score:.08}]},{value:116,confidence:.90,candidates:[{value:116,score:.01},{value:115,score:.02}]},{value:102,confidence:.91,candidates:[{value:102,score:.01}]},{value:103,confidence:.90,candidates:[{value:103,score:.01},{value:108,score:.02}]},{value:120,confidence:.93,candidates:[{value:120,score:.01}]}];const validGroup=SC.chooseGroup(alreadyValid,107);eq(validGroup.values,[91,116,102,103,120],'scanner does not alter confident values merely to make rounded group total closer');ok(!validGroup.repaired,'already-consistent aggregate is validation only');

  const seeded=await DP.ensure();ok(Object.keys(seeded.normal.drills).length===29,'normal profile seeded 29 drills');ok(Object.values(seeded.normal.drills).filter(x=>x.unlocked).length===28,'captured normal unlock snapshot preserved');eq(seeded.master.stock,{ATTACKING_MASTERCLASS:0,MIDFIELD_MASTERCLASS:0,PHYSICAL_MASTERCLASS:0,DEFENDING_MASTERCLASS:0},'captured Master stock seeded');
  await DP.setMasterStock('ATTACKING_MASTERCLASS',17);ok((await DP.getMaster()).stock.ATTACKING_MASTERCLASS===17,'Master stock has no arbitrary max');await DP.setMasterStock('ATTACKING_MASTERCLASS',0);
  await DP.setNormal('STAY_IN_LANE',{unlocked:true,level:2});let ns=await DP.getNormal();ok(ns.drills.STAY_IN_LANE.unlocked&&ns.drills.STAY_IN_LANE.level===2,'normal unlock/level persists');await DP.resetToCapturedSnapshot();

  const playerKey=await P.save({name:'Alpha Test',age:20,ovr:110,position:'DC',roles:['DC','DR'],skills:{Tackling:90,Marking:100,Positioning:110,Heading:80,Bravery:95,Fitness:105,Strength:85,Aggression:92,Crossing:70,Speed:88,Passing:50,Dribbling:50,Shooting:50,Finishing:50,Creativity:50},specialAbilities:['Defensive Wall']});let p=await P.get(playerKey);eq(p.roles,['DC','DR'],'multi roles persist');await S.set(`training:session:${playerKey}`,'stale-player-session');await P.save({...p,name:'Alpha Renamed'},playerKey);p=await P.get(playerKey);ok(p.key===playerKey&&p.name==='Alpha Renamed','stable-key player edit');ok(await S.get(`training:session:${playerKey}`)===null,'editing an existing player invalidates their saved training session');

  const normal=await DP.getNormal(),stock=await DP.getMaster();const before=JSON.stringify(p.skills);const session=T.buildIndividualSession({player:p,normalProfile:normal,masterStock:stock});ok(session.drills.length===6&&!session.error,'six-slot contract session builds');ok(JSON.stringify(p.skills)===before,'optimiser does not mutate player');eq(session.meta.roles,['DC','DR'],'optimizer uses all saved roles');ok(session.meta.whiteAttributes.includes('Crossing')&&session.meta.whiteAttributes.includes('Heading'),'multi-role union affects optimizer');ok(session.meta.exactGainPrediction===false,'no exact gain prediction');
  for(const d of session.drills){ok(d.targetedWhiteAttributes.every(a=>session.meta.whiteAttributes.includes(a)),`${d.name} targets only white attributes`);ok(d.greyApplicableAttributes.every(a=>session.meta.applicableAttributes.includes(a)&&!session.meta.whiteAttributes.includes(a)),`${d.name} grey list is applicable-only`);}
  const session2=T.buildIndividualSession({player:p,normalProfile:normal,masterStock:stock});eq(session.drills.map(d=>d.drillId),session2.drills.map(d=>d.drillId),'identical input deterministic');

  const allLocked={gameDataVersion:D.GAME_DATA_VERSION,drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:false,level:0}]))};const stSkills=Object.fromEntries(D.OUTFIELD_SKILLS.map(s=>[s,100]));Object.assign(stSkills,{Passing:70,Dribbling:70,Crossing:70,Shooting:70,Finishing:70,Positioning:100,Heading:100,Strength:100,Speed:100,Creativity:100});const st={position:'ST',roles:['ST'],skills:stSkills};
  const master2={stock:{ATTACKING_MASTERCLASS:2,MIDFIELD_MASTERCLASS:0,PHYSICAL_MASTERCLASS:0,DEFENDING_MASTERCLASS:0}};const ms=T.buildIndividualSession({player:st,normalProfile:allLocked,masterStock:master2});ok(ms.drills.length===2&&ms.meta.masterUsage.ATTACKING_MASTERCLASS===2,'Master duplicates limited by owned stock');ok(ms.drills.every(d=>d.isMaster),'only owned Master used when normals locked');
  const oneNormal={gameDataVersion:D.GAME_DATA_VERSION,drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:d.drillId==='SHOOTING_TECHNIQUE',level:d.drillId==='SHOOTING_TECHNIQUE'?3:0}]))};const rep=T.buildIndividualSession({player:st,normalProfile:oneNormal,masterStock:{stock:{}}});ok(rep.drills.length===6&&new Set(rep.drills.map(d=>d.drillId)).size===1,'normal drill duplicates allowed without uniqueness penalty');
  const shot=D.NORMAL_DRILLS.find(d=>d.drillId==='SHOOTING_TECHNIQUE');const evalOut=T.evaluateCatalogue({player:st,normalProfile:oneNormal,masterStock:{stock:{}}}).rows.find(x=>x.candidate.drillId===shot.drillId);eq(evalOut.candidate.applicableAttributes,['Shooting','Strength','Finishing'],'outfield ignores GK-only Reflexes/Agility');
  const gkSkills={Reflexes:100,Agility:90,Anticipation:100,'Rushing Out':100,Communication:100,Throwing:100,Kicking:100,Punching:100,'Aerial Reach':100,Concentration:100,Fitness:100,Strength:20,Aggression:20,Speed:20,Creativity:20};const gk={position:'GK',roles:['GK'],skills:gkSkills};const gkEval=T.evaluateCatalogue({player:gk,normalProfile:oneNormal,masterStock:{stock:{}}}).rows.find(x=>x.candidate.drillId==='SHOOTING_TECHNIQUE');eq(gkEval.candidate.applicableAttributes,['Reflexes','Agility'],'GK ignores non-GK Strength plus outfield attack fields');eq(gkEval.candidate.greyAttributes,[],'GK Shooting Technique has no applicable grey attrs under authoritative GK pool');
  const syntheticOne=T.scoreCandidate({whiteAttributes:['A'],strength:5,denominator:5},{A:10},{},new Set());const syntheticMulti=T.scoreCandidate({whiteAttributes:['A','B'],strength:5,denominator:5},{A:10,B:10},{},new Set());near(syntheticOne.score,50,1e-9,'grey/applicable denominator does not dilute a one-white hit');near(syntheticMulti.score,100,1e-9,'two useful white hits accumulate value in one drill');ok(syntheticMulti.score>syntheticOne.score,'multi-white return is rewarded at the individual-drill level');
  const stanekSkills={Reflexes:127,Agility:159,Anticipation:136,'Rushing Out':128,Communication:141,Throwing:133,Kicking:135,Punching:137,'Aerial Reach':149,Concentration:132,Fitness:168,Strength:34,Aggression:42,Speed:54,Creativity:56};const stanek={name:'Jiri Stanek',age:23,ovr:115,position:'GK',roles:['GK'],skills:stanekSkills};const stanekRows=T.evaluateCatalogue({player:stanek,normalProfile:normal,masterStock:stock}).rows;eq(stanekRows[0].candidate.drillId,'GOALKEEPER_TRAINING','Stanek ranks the five-white Goalkeeper Training drill above single-white alternatives');ok(stanekRows[0].candidate.whiteAttributes.length===5,'Goalkeeper Training exposes five useful white hits for Stanek');const stanekFast=stanekRows.find(x=>x.candidate.drillId==='FAST_COUNTER_ATTACKS');ok(stanekRows[0].metric.score>stanekFast.metric.score,'five-white useful return outranks Fast Counter single-white Communication hit');const stanekSession=T.buildIndividualSession({player:stanek,normalProfile:normal,masterStock:stock});ok(stanekSession.drills.length===6,'Stanek six-slot session builds');ok(stanekSession.drills.every(d=>d.targetedWhiteAttributes.length>=2),'Stanek seed session uses multi-white drills in every slot when stronger multi-white options exist');ok(stanekSession.meta.greyAttributesAffectScore===false&&stanekSession.meta.rankingMode==='weak-white-coverage','v5.2.4 ranking metadata records grey-independent white-coverage mode');
  const incomplete={position:'ST',roles:['ST'],skills:{Passing:100}};ok(T.buildIndividualSession({player:incomplete,normalProfile:normal,masterStock:stock}).error==='missing-white-attributes','incomplete player is rejected instead of guessed');

  await S.set(`training:session:${playerKey}`,'stale-drill-session');await S.set('training:session:other-player','stale-other-session');await DP.setNormal('STAY_IN_LANE',{unlocked:true,level:2});ok((await S.list('training:session:')).length===0,'changing My Drills invalidates all saved recommendations');await DP.resetToCapturedSnapshot();
  const usageBefore=(await DP.getMaster()).stock.ATTACKING_MASTERCLASS;await DP.setMasterStock('ATTACKING_MASTERCLASS',5);await S.set(`training:session:${playerKey}`,'stale-master-session');await DP.deductMasterUsage({ATTACKING_MASTERCLASS:2});ok((await DP.getMaster()).stock.ATTACKING_MASTERCLASS===3,'completed session deduction helper removes exact used Master cards');ok(await S.get(`training:session:${playerKey}`)===null,'Master stock deduction invalidates other saved recommendations before current completion is re-saved');await DP.setMasterStock('ATTACKING_MASTERCLASS',usageBefore);

  for(const group of Object.keys(D.TEAM_GROUPS)){const r=TT.buildTeamSession(group,{normalProfile:normal});ok(r.drills.length===6,`${group} group session builds`);ok(r.drills.every(d=>!d.isMaster),`${group} does not mix Master/TeamPlay into group normal planner`);ok(r.meta.apkTeamPlayModeled===false,`${group} explicitly excludes TeamPlay protocol`);}
  for(const formation of F.FORMATIONS){ok(formation.slots.length===11&&formation.layout.length===11,`${formation.name} has 11 slots`);ok(new Set(formation.layout.map(x=>x.join(','))).size===11,`${formation.name} has no duplicate pitch coordinates`);}

  const baseSkills={Passing:100,Creativity:100,Shooting:100,Finishing:100,Crossing:100,Tackling:100,Marking:100,Positioning:100,Bravery:100,Fitness:100,Dribbling:100,Heading:100};const squad=[{name:'A',age:23,ovr:110,position:'ST',roles:['ST'],skills:{...baseSkills,Finishing:145,Shooting:140},specialAbilities:['Penalty Kick Specialist']},{name:'B',age:25,ovr:108,position:'MR',roles:['MR'],skills:{...baseSkills,Crossing:150,Passing:135},specialAbilities:['Corner Specialist']},{name:'C',age:26,ovr:112,position:'MC',roles:['MC'],skills:{...baseSkills,Shooting:145,Passing:135},specialAbilities:['Free Kick Specialist']}];const ranks=R.rankPlaymakers(squad);ok(ranks.penalties[0].player.name==='A','penalty rank retained');ok(ranks.corner.player.name==='B','corner rank retained');ok(ranks.freeKick.player.name==='C','free kick rank retained');ok(R.MENTORS.length===7,'seven mentors retained');
  await P.remove(playerKey);
  console.log(`PASS ${passed} assertions`);console.log('Contract session:',session.drills.map(d=>`${d.name}${d.isMaster?' [MASTER]':''}`).join(' | '));
})().catch(err=>{console.error('FAIL',err.stack||err);process.exit(1)});
