const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={_m:new Map(),getItem(k){return this._m.has(k)?this._m.get(k):null},setItem(k,v){this._m.set(k,String(v))},removeItem(k){this._m.delete(k)},key(i){return [...this._m.keys()][i]||null},clear(){this._m.clear()},get length(){return this._m.size}};
const ROOT=path.join(__dirname,'..');
for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','squad-coverage-engine.js','scanner-engine.js','storage.js','drill-profile.js','players.js','training-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {Data:D,Strategy:S,Training:T}=global.TE5;
const skills={Tackling:123,Marking:121,Positioning:157,Heading:46,Bravery:122,Passing:189,Dribbling:164,Crossing:51,Shooting:118,Finishing:59,Fitness:138,Strength:33,Aggression:46,Speed:137,Creativity:99};
const player={key:'stefano-luiu-integrity',name:'Stefano Luiu',position:'MC',roles:['MC'],relatedRoles:[],age:22,ovr:107,skills,playstyle:{type:'Mezzala',level:3},specialAbilities:['Playmaker']};
const normalProfile={drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:true,level:3}]))};
const hierarchy=S.trainingPriorityProfile(player,{roles:['MC'],developmentRole:'MC'});
const catalogue=T.evaluateCatalogue({player,roles:['MC'],position:'MC',skills,normalProfile,masterStock:{},developmentRole:'MC'});
const session=T.buildIndividualSession({player,roles:['MC'],position:'MC',skills,normalProfile,masterStock:{},slots:6,mode:'maxGrowth',developmentRole:'MC'});
const failures=[];let assertions=0;const check=(cond,msg)=>{assertions++;if(!cond)failures.push(msg)};
check(hierarchy.playstyle==='Mezzala'&&hierarchy.playstyleActive===true,'Mezzala Intermediate must be active for MC');
check(hierarchy.profileSource==='playstyle-role','Luiu must use the MC+Mezzala profile');
const creativity=hierarchy.priorities.find(x=>x.attribute==='Creativity'),passing=hierarchy.priorities.find(x=>x.attribute==='Passing');
check(creativity?.specialAbilitySignals?.includes('Playmaker'),'Playmaker must contribute to Creativity training context');
check(passing?.specialAbilitySignals?.includes('Playmaker'),'Playmaker must contribute to Passing training context');
const topNeed=session.meta?.priorityAttributes?.[0];
check(topNeed?.attribute==='Creativity','Creativity 99 should be Luiu\'s highest current development need');
const topDrill=catalogue.rows?.[0]?.candidate;
check(topDrill?.name==='Fast Counter-Attacks','Fast Counter-Attacks should be Luiu\'s highest-scoring first drill with all normal drills World Class');
check(session.drills?.[0]?.name==='Fast Counter-Attacks','maxGrowth session should begin with Fast Counter-Attacks');
const repeated=(session.drills||[]).filter(x=>x.name==='Fast Counter-Attacks').length;
console.log(JSON.stringify({assertions,failures,highestNeed:topNeed&&{attribute:topNeed.attribute,value:topNeed.value,target:Number(topNeed.target?.toFixed?.(2)??topNeed.target),gap:Number(topNeed.gap?.toFixed?.(2)??topNeed.gap),need:Number(topNeed.need?.toFixed?.(2)??topNeed.need)},topDrill:topDrill?.name,topDrillScore:Number(catalogue.rows?.[0]?.metric?.score?.toFixed?.(2)??catalogue.rows?.[0]?.metric?.score),maxGrowthFastCounterAttackSlots:repeated,session:(session.drills||[]).map(x=>x.name)},null,2));
if(failures.length)process.exitCode=1;
