const fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){},key(){return null},get length(){return 0}};
const ROOT=path.join(__dirname,'..');for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','squad-coverage-engine.js','scanner-engine.js','storage.js','drill-profile.js','players.js','training-engine.js','team-training-engine.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','team-plan-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {Data:D,BibleData:B,Formation:F,Tactics:T,Mentor:M,Recommendations:R,TeamPlan:TP}=TE5,A=Object.keys(D.ATTRIBUTE_IDS);let assertions=0,failures=[];const ok=(c,m)=>{assertions++;if(!c)failures.push(m)};
function mk(k,roles,v=120,ps=null,sa=[]){const skills=Object.fromEntries(A.map((a,i)=>[a,v+((k.charCodeAt(0)+i*7)%9)-4]));return{key:k,name:k,position:roles[0],roles:[...roles],relatedRoles:[],age:20,ovr:v,specialAbilities:sa,playstyle:ps?{type:ps,level:3}:null,skills};}
const squad=[mk('a',['GK'],123,'Sweeper Keeper'),mk('b',['DL'],121,'Full Back'),mk('c',['DC'],126,'Stopper'),mk('d',['DC','DMC'],124,'No-Nonsense DC'),mk('e',['DR'],122,'Wing Back'),mk('f',['DMC','MC'],129,'Regista'),mk('g',['MC'],131,'Box-to-Box'),mk('h',['AML'],134,'Winger',['Corner Specialist']),mk('i',['AMC'],133,'Enganche',['Free Kick Specialist']),mk('j',['AMR'],132,'Inside Forward',['Set Piece Taker']),mk('k',['ST'],136,'Poacher',['Penalty Kick Specialist']),mk('l',['MC'],114,'Mezzala'),mk('m',['ST'],112,'Target Man')];
for(const p of squad){if(['h','j','k'].includes(p.key)){p.skills.Speed+=15;p.skills.Dribbling+=10;p.skills.Finishing+=12;}if(['f','g','i'].includes(p.key)){p.skills.Passing+=14;p.skills.Creativity+=14;}}
M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:true,level:10}])));
const starterSig=r=>({formation:r.formation.id,score:Number(r.strategic.totalScore.toFixed(9)),starters:r.chosen.map(s=>`${s.assignedRole}:${s.player.key}:${s.suitability}`).sort()});
function winner(players){return F.rankStrategic(players).find(x=>!x.error)}
const orders=[squad,[...squad].reverse(),[squad[5],squad[11],squad[1],squad[9],squad[12],squad[2],squad[7],squad[0],squad[10],squad[4],squad[8],squad[3],squad[6]]],wins=orders.map(winner),baseSig=starterSig(wins[0]);
for(let i=1;i<wins.length;i++)ok(JSON.stringify(starterSig(wins[i]))===JSON.stringify(baseSig),`roster order ${i} changed Formation/XI selection`);
function downstream(w){const starters=w.chosen,tactics=T.recommendAuto(starters,{drainLimit:'High',drainProfile:T.DRAIN_PROFILE_LIVE}),mentor=M.recommend(starters,tactics,{drainLimit:'High'}),sp=R.buildSetPiecePlan(starters),dev=TP.developmentContext(starters,tactics);return{tactics:{approach:tactics.approachKey,values:tactics.values,medium:tactics.mediumCount,high:tactics.highCount,score:Number(tactics.decisionScore.toFixed(9))},mentor:mentor.best?{id:mentor.best.mentor.id,adj:Number(mentor.best.planAdjustment.toFixed(9))}:null,setPieces:sp.assignments,development:dev.map(x=>`${x.playerKey}:${x.assignedRole}:${x.developmentRole}:${x.playstyle||''}`).sort()};}
const downs=wins.map(downstream),downBase=JSON.stringify(downs[0]);for(let i=1;i<downs.length;i++)ok(JSON.stringify(downs[i])===downBase,`roster order ${i} changed stitched downstream plan`);
console.log(JSON.stringify({assertions,failures,formation:baseSig.formation,tactics:downs[0].tactics,mentor:downs[0].mentor?.id,setPieces:downs[0].setPieces},null,2));if(failures.length)process.exitCode=1;
