const fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){},key(){return null},get length(){return 0}};
const ROOT=path.join(__dirname,'..');for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','squad-coverage-engine.js','scanner-engine.js','storage.js','drill-profile.js','players.js','training-engine.js','team-training-engine.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','team-plan-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {Data:D,BibleData:B,Formation:F,Tactics:T,Mentor:M,Recommendations:R,TeamPlan:TP,Training:TR}=TE5,A=Object.keys(D.ATTRIBUTE_IDS);let failures=[],assertions=0;function ok(c,m){assertions++;if(!c)failures.push(m)}
function mk(k,r,v=120,sa=[],ps=null){return{key:k,name:k,position:r,roles:[r],relatedRoles:[],age:18,ovr:v,skills:Object.fromEntries(A.map(a=>[a,v])),specialAbilities:sa,playstyle:ps?{type:ps,level:3}:null}}
const players=[mk('gk','GK',118),mk('dl','DL',120),mk('dc1','DC',124),mk('dc2','DC',122),mk('dr','DR',121),mk('dmc','DMC',125),mk('mc','MC',126),mk('aml','AML',130,['Corner Specialist'],'Winger'),mk('amc','AMC',128,['Free Kick Specialist'],'Enganche'),mk('amr','AMR',129,['Set Piece Taker'],'Winger'),mk('st','ST',132,['Penalty Kick Specialist'],'Poacher')];
// Give the Poacher a deliberately flat white profile so target-shape logic has work to do.
for(const a of D.POSITION_WHITE.ST)players.find(x=>x.key==='st').skills[a]=150;
const assigned=F.assign(players,F.FORMATIONS.find(x=>x.id==='41131'));ok(!assigned.error&&assigned.chosen.length===11,'Could not form stitched calibration XI');const starters=assigned.chosen;
const tactics=T.recommendAuto(starters,{drainLimit:'High',drainProfile:T.DRAIN_PROFILE_LIVE});ok(!tactics.error,'Stitched tactic stage failed');ok(tactics.drainProfile===T.DRAIN_PROFILE_LIVE&&tactics.rawScore===null&&tactics.relativeScore===null&&tactics.normalized===null&&Number.isInteger(tactics.mediumCount)&&Number.isInteger(tactics.highCount)&&tactics.decisionComponents?.drainEfficiencyScore===5,'Stitched tactic stage did not use unresolved live-intensity drain safely');
M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:true,level:10}])));const mentor=M.recommend(starters,tactics,{drainLimit:'High'});ok(!!mentor.best&&!mentor.error,'Stitched Mentor stage returned no recommendation');
const sp=R.buildSetPiecePlan(starters),keys=new Set(starters.map(x=>x.player.key));for(const [slot,k] of Object.entries(sp.assignments))ok(keys.has(k),`Set-piece slot ${slot} references a non-starter`);ok(sp.assignments.captain,'Stitched package has blank captain');ok(sp.assignments.penalty1==='st','Penalty specialist was not selected in stitched plan');ok(sp.assignments.freeRight==='amc'&&sp.assignments.freeLeft==='amc','Free-kick specialist was not selected in stitched plan');ok(sp.assignments.cornerRight==='aml'&&sp.assignments.cornerLeft==='aml','Corner specialist was not selected in stitched plan');
const dev=TP.developmentContext(starters,tactics),devKeys=new Set(dev.map(x=>x.playerKey));ok(dev.length===11&&devKeys.size===11&&[...keys].every(k=>devKeys.has(k)),'Development context is not the exact winning XI');const stDev=dev.find(x=>x.playerKey==='st');ok(stDev.assignedRole==='ST'&&stDev.developmentRole==='ST'&&stDev.playstyle==='Poacher'&&stDev.profileSource==='playstyle-role','Winning ST did not carry ST+Poacher development identity');
const stP=players.find(x=>x.key==='st'),normalProfile={drills:Object.fromEntries(D.NORMAL_DRILLS.map(d=>[d.drillId,{unlocked:true,level:3}]))},session=TR.buildIndividualSession({player:stP,roles:stP.roles,position:stP.position,skills:stP.skills,normalProfile,masterStock:{},slots:6,mode:'maxGrowth',developmentRole:stDev.developmentRole,tactics:tactics.values});ok(!session.error&&session.drills.length===6,'Winning-plan Training stage did not build six drills');ok(session.meta.hierarchy.developmentRole===stDev.developmentRole&&session.meta.hierarchy.playstyle===stDev.playstyle,'Training recalculated a different development identity than Team Plan');
const pr=Object.fromEntries(session.meta.priorityAttributes.map(x=>[x.attribute,x]));ok(pr.Finishing.target>pr.Passing.target&&pr.Shooting.target>pr.Strength.target,'Stitched Training lost the Poacher target tilt');ok(session.meta.priorityAttributes[0].need>=session.meta.priorityAttributes.at(-1).need,'Training priority output is not ordered by need');
const joint=TP.jointScore({strategic:assigned.strategic||{totalScore:100}},tactics,mentor,sp);ok(Number.isFinite(joint.totalScore)&&joint.components.setPieceReadiness===sp.readiness,'Joint score does not carry stitched Set-Piece readiness');
console.log(JSON.stringify({assertions,failures,formation:assigned.formation.id,tactics:tactics.values,relativeDrain:tactics.rawScore,mentor:mentor.best?.mentor.displayName,setPieces:sp.assignments,poacherTopNeeds:session.meta.priorityAttributes.slice(0,5).map(x=>[x.attribute,Number(x.need.toFixed(2)),Number(x.target.toFixed(1))])},null,2));if(failures.length)process.exitCode=1;
