const fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;global.localStorage={getItem(){return null},setItem(){},removeItem(){},key(){return null},get length(){return 0}};
const ROOT=path.join(__dirname,'..');for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','squad-coverage-engine.js','storage.js','players.js','recommendations.js','formation.js','tactics-engine.js','mentor-engine.js','team-plan-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {Data:D,Formation:F,Tactics:T,Mentor:M,Recommendations:R,TeamPlan:TP,BibleData:B}=TE5,A=Object.keys(D.ATTRIBUTE_IDS);let assertions=0,failures=[];function ok(c,m){assertions++;if(!c)failures.push(m)}
function mk(k,r,v=120,ps=null,sa=[]){return{key:k,name:k,position:r,roles:[r],relatedRoles:[],age:20,ovr:v,skills:Object.fromEntries(A.map(a=>[a,v])),playstyle:ps?{type:ps,level:3}:null,specialAbilities:sa}}
function squad(){return [mk('gk','GK',118),mk('dl','DL',120),mk('dc1','DC',124),mk('dc2','DC',122),mk('dr','DR',121),mk('dmc','DMC',125),mk('mc','MC',126),mk('aml','AML',130,'Winger',['Corner Specialist']),mk('amc','AMC',128,'Enganche',['Free Kick Specialist']),mk('amr','AMR',129,'Winger',['Set Piece Taker']),mk('st','ST',132,'Poacher',['Penalty Kick Specialist'])]}
M.setStateOverrides(Object.fromEntries(B.MENTORS.map(m=>[m.id,{unlocked:true,level:10}])));
function plan(players){const formation=F.rankStrategic(players).find(x=>!x.error),starters=formation.chosen,tactics=T.recommendAuto(starters,{drainLimit:'High',drainProfile:T.DRAIN_PROFILE_LIVE}),mentor=M.recommend(starters,tactics,{drainLimit:'High'}),sp=R.buildSetPiecePlan(starters),dev=TP.developmentContext(starters,tactics);return{formation,tactics,mentor,sp,dev,starterKeys:starters.map(x=>x.player.key).sort()}}
const a=plan(squad()),weak=[...squad(),mk('bench-bad','ST',20)],b=plan(weak);
ok(a.formation.formation.id===b.formation.formation.id,'Unused weak bench player changed Formation');ok(JSON.stringify(a.starterKeys)===JSON.stringify(b.starterKeys),'Unused weak bench player changed XI');ok(JSON.stringify(a.tactics.values)===JSON.stringify(b.tactics.values)&&Math.abs(a.tactics.decisionScore-b.tactics.decisionScore)<1e-9,'Unused weak bench player changed Tactics');ok(a.mentor.best?.mentor.id===b.mentor.best?.mentor.id,'Unused weak bench player changed Mentor');ok(JSON.stringify(a.sp.assignments)===JSON.stringify(b.sp.assignments),'Unused weak bench player changed Set Pieces/Captain');ok(JSON.stringify(a.dev)===JSON.stringify(b.dev),'Unused weak bench player changed starter Training identities');
const elite=[...squad(),mk('elite-st','ST',200,'Poacher',['Penalty Kick Specialist'])],c=plan(elite);ok(c.starterKeys.includes('elite-st'),'Genuinely elite added player failed to enter XI');ok(!c.starterKeys.includes('st'),'Elite role replacement failed to displace weaker starter');
console.log(JSON.stringify({assertions,failures,baseFormation:a.formation.formation.id,weakBenchFormation:b.formation.formation.id,eliteFormation:c.formation.formation.id,baseTactics:a.tactics.values,eliteTactics:c.tactics.values},null,2));if(failures.length)process.exitCode=1;
