const fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;const ROOT=path.join(__dirname,'..');for(const f of ['optimizer-data.js','bible-data.js','data.js','strategy-data.js','strategy-logic.js','formation.js','tactics-engine.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,'js',f),'utf8'),{filename:f});
const {Data:D,Formation:F,Tactics:T}=TE5,A=Object.keys(D.ATTRIBUTE_IDS);function mk(k,r,v=100,ps=null){return{key:k,name:k,position:r,roles:[r],relatedRoles:[],skills:Object.fromEntries(A.map(a=>[a,v])),ovr:v,specialAbilities:[],playstyle:ps?{type:ps,level:3}:null}}function base(){return [['gk','GK'],['dl','DL'],['dc1','DC'],['dc2','DC'],['dr','DR'],['dmc','DMC'],['mc','MC'],['aml','AML'],['amc','AMC'],['amr','AMR'],['st','ST']].map(x=>mk(...x));}function set(p,keys,attrs,v){for(const x of p.filter(z=>keys.includes(z.key)))for(const a of attrs)x.skills[a]=v;}function ps(p,key,name){p.find(x=>x.key===key).playstyle={type:name,level:3}}function sa(p,key,name){p.find(x=>x.key===key).specialAbilities=[name]}
function run(name,mut,approach='balanced'){const p=base();mut?.(p);const s=F.assign(p,F.FORMATIONS.find(x=>x.id==='41131')).chosen;const r=T.recommend(s,{approach,drainLimit:'High',drainProfile:T.DRAIN_PROFILE_LIVE});return{name,values:r.values,score:Number(r.decisionScore.toFixed(3)),m:r.mediumCount,h:r.highCount,own:r.contextFit?.own};}
const rows=[];
rows.push(run('neutral',p=>{}));
rows.push(run('technical-build',p=>set(p,['dmc','mc','amc'],['Passing','Creativity','Dribbling'],190)));
rows.push(run('mixed-balance',p=>{set(p,['dmc','mc','amc'],['Passing','Creativity','Dribbling'],125);set(p,['st'],['Strength','Positioning','Heading','Speed','Dribbling','Passing','Finishing'],125);}));
rows.push(run('target-direct-wide',p=>{set(p,['st'],['Heading','Strength','Positioning'],195);ps(p,'st','Target Man');set(p,['aml','amr'],['Crossing','Speed','Dribbling'],180);ps(p,'aml','Winger');ps(p,'amr','Winger');}));
rows.push(run('counter-runners',p=>{set(p,['st','aml','amr'],['Speed','Dribbling','Passing','Finishing','Positioning'],185);ps(p,'st','Poacher');ps(p,'aml','Inside Forward');ps(p,'amr','Inside Forward');}));
rows.push(run('box-finishers',p=>set(p,['st','amc'],['Finishing','Positioning','Dribbling'],190)));
rows.push(run('long-shotters',p=>{set(p,['st','amc','mc'],['Shooting','Creativity'],190);sa(p,'amc','Shadow Striker');}));
rows.push(run('left-lane',p=>{set(p,['dl','aml'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],195);set(p,['dr','amr'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],70);}));
rows.push(run('right-lane',p=>{set(p,['dr','amr'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],195);set(p,['dl','aml'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],70);}));
rows.push(run('centre-lane',p=>{set(p,['dmc','mc','amc','st'],['Passing','Creativity','Dribbling','Shooting','Finishing','Speed'],190);set(p,['aml','amr'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],65);}));
rows.push(run('both-wings',p=>{set(p,['aml','amr'],['Passing','Creativity','Dribbling','Crossing','Shooting','Finishing','Speed'],190);set(p,['amc'],['Passing','Creativity','Dribbling','Shooting','Finishing','Speed'],70);}));
rows.push(run('low-press',p=>{set(p,p.filter(x=>x.key!=='gk').map(x=>x.key),['Fitness','Aggression','Tackling','Bravery','Speed'],60);set(p,['dl','dc1','dc2','dr','dmc'],['Marking','Positioning'],180);}));
rows.push(run('high-press',p=>set(p,p.filter(x=>x.key!=='gk').map(x=>x.key),['Fitness','Aggression','Tackling','Bravery','Speed'],185)));
rows.push(run('fast-line',p=>{set(p,['dl','dc1','dc2','dr','dmc'],['Speed','Positioning','Bravery'],190);set(p,p.filter(x=>x.key!=='gk').map(x=>x.key),['Fitness','Aggression','Tackling'],175);}));
rows.push(run('slow-line',p=>set(p,['dl','dc1','dc2','dr','dmc'],['Speed','Positioning','Bravery'],55)));
rows.push(run('marker-monsters',p=>set(p,['dl','dc1','dc2','dr','dmc'],['Marking','Speed','Strength','Positioning'],195)));
rows.push(run('ballwinner-stop',p=>{ps(p,'dmc','Ball Winner');ps(p,'dc1','Stopper');set(p,['dmc','dc1'],['Tackling','Bravery','Aggression'],190);}));
console.log(JSON.stringify(rows.map(r=>({name:r.name,values:r.values,score:r.score,m:r.m,h:r.h,features:{technical:r.own?.technicalBuild,press:r.own?.pressCapacity,line:r.own?.lineSpeed,marker:r.own?.markerCapacity,direct:r.own?.directOutletStrong,counter:r.own?.counterOutletStrong,box:r.own?.boxFinishing,long:r.own?.longShotThreat}})),null,2));
