#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..');
global.window=global;global.document={};
for(const file of ['js/optimizer-data.js','js/bible-data.js','js/data.js','js/strategy-data.js','js/strategy-logic.js','js/recommendations.js','js/formation.js','js/tactics-engine.js','js/mentor-engine.js']) vm.runInThisContext(fs.readFileSync(path.join(ROOT,file),'utf8'),{filename:file});
const TE=global.TE5,{Data:D,StrategyData:CFG,Strategy:STRAT,Formation:F,Tactics:TAC,Mentor:M,Recommendations:R,BibleData:B}=TE;
const MODEL='best-in-slot-goal-v2-role-identity-only',DRAIN_LIMIT='Medium',DRAIN_RANK={Low:0,Medium:1,High:2};
const APPROACHES=Object.values(B.APPROACHES||{});
const SET_PIECES=[
  {ability:'Corner Specialist',duty:'Corners',rolePreference:['MC','ML','MR','DL','DR']},
  {ability:'Free Kick Specialist',duty:'Free Kicks',rolePreference:['AMC','MC','ST','AML','AMR','DMC','ML','MR','DL','DC','DR']},
  {ability:'Penalty Kick Specialist',duty:'Penalties',rolePreference:['ST','AMC','AML','AMR','MC','ML','MR','DMC','DL','DC','DR']}
];
function alias(s){return String(s||'').replace(/[^A-Za-z0-9]/g,'');}
function affinity(row,values){let score=0;if(!row)return 0;for(const r of row.supports||[])if((r.options||[]).includes(values?.[r.dimension]))score+=Number(r.points)||0;for(const r of row.opposes||[])if((r.options||[]).includes(values?.[r.dimension]))score+=Number(r.points)||0;return score;}
function roleVariants(formation){let out=[[]];for(const slot of formation.slots){const opts=F.options(slot);const next=[];for(const pre of out)for(const role of opts)next.push([...pre,role]);out=next;}const seen=new Set(),uniq=[];for(const roles of out){const key=roles.join('|');if(seen.has(key))continue;seen.add(key);uniq.push(roles);}return uniq;}
function identityCounts(ids){const playstyles={},abilities={};for(const x of ids){if(x.playstyle)playstyles[alias(x.playstyle)]=(playstyles[alias(x.playstyle)]||0)+1;for(const sa of x.specialAbilities||[])abilities[alias(sa)]=(abilities[alias(sa)]||0)+1;}return{playstyles,abilities};}
function neutralOwn(roles,ids,values={}){
  const shape=STRAT.analyseShape(roles),counts=identityCounts(ids),ps=counts.playstyles;
  const aerialOutlet=(ps.TargetMan||0)>0;
  const counterOutlet=(ps.Poacher||0)>0||(ps.InsideForward||0)>0;
  const directOutlet=aerialOutlet||counterOutlet||shape.strikers>0;
  const dribbleStyles=new Set(['FalseNine','Enganche','InsideForward']);
  let dribbleCount=0;for(let i=0;i<roles.length;i++)if(['AMC','AML','AMR','ST'].includes(roles[i])&&dribbleStyles.has(alias(ids[i]?.playstyle)))dribbleCount++;
  const defensiveActionDemand=['defending','hardDefending'].includes(values.mentality)||(values.pressing==='high'&&values.lost==='counterPress')?'high':(values.pressing==='mid'||values.tackling==='aggressive')?'medium':'low';
  return{...shape,xiQualityMedian:0,aerialOutlet,aerialOutletStrong:aerialOutlet,counterOutlet,counterOutletStrong:counterOutlet,directOutlet,directOutletStrong:aerialOutlet||counterOutlet,technicalBuildValue:0,technicalBuild:'medium',pressCapacity:'medium',lineSpeed:'medium',markerCapacity:'medium',boxFinishing:0,longShotThreat:0,dribbleReliance:dribbleCount>=2,defensiveActionDemand,directSupport:0,attackUnitQuality:0,defenseUnitQuality:0,attackDefenseDelta:0,playstyles:counts.playstyles,abilities:counts.abilities,margin:Number(CFG.feature_model?.skill_reference?.comparison_margin_points)||5};
}
function makeStarters(formation,roles,ids){const rows=roles.map((role,i)=>({player:{key:`bis-${formation.id}-${i+1}`,name:`Ideal ${role}`,position:role,roles:[role],relatedRoles:[],skills:{},playstyle:ids[i]?.playstyle?{name:ids[i].playstyle,level:5}:null,specialAbilities:[...(ids[i]?.specialAbilities||[])]},assignedRole:role,suitability:'NATURAL',roleMean:null,roleFloor:null,playstyleFit:ids[i]?.playstyle?1:0,playstyleLevel:ids[i]?.playstyle?5:0,activePlaystyle:!!ids[i]?.playstyle,weakest:[]}));return F.applyCoordinates(rows);}
function initialIdentities(roles,values){return roles.map(role=>{const pss=D.playstylesForRoles([role]).map((name,order)=>({name,order,score:affinity(CFG.tactics?.playstyle_affinities?.[name],values)})).sort((a,b)=>b.score-a.score||a.order-b.order);const sas=D.specialAbilitiesForRoles([role]).map((name,order)=>({name,order,row:CFG.tactics?.special_ability_affinities?.[name],score:affinity(CFG.tactics?.special_ability_affinities?.[name],values)})).filter(x=>x.row?.active&&x.score>0).sort((a,b)=>b.score-a.score||a.order-b.order);return{playstyle:pss[0]?.name||null,specialAbilities:sas[0]?[sas[0].name]:[],preferredTacticalSA:sas[0]?.name||null};});}
function formationStructure(roles){const own={...STRAT.analyseShape(roles),playstyles:{},abilities:{},margin:5},ctx={own,values:{},playstyles:{},abilities:{},margin:5},ev=STRAT.evaluateRules(CFG.formation?.rules||[],ctx);return{raw:ev.score,score:F.structureComponent(ev.score),reasons:ev.contributions.map(x=>({id:x.id,points:x.points,reason:x.message}))};}
function tacticComponents(values,formation,roles,ids,drain){const starters=makeStarters(formation,roles,ids),own=neutralOwn(roles,ids,values),context=STRAT.scoreTacticContext(values,starters,own),b=context.buckets||{};const components={ownSquadStructure:TAC.calibratedBucket(Number(b.own_squad_structure)||0,'own_squad_structure',{negativeCap:13,positiveCap:31,max:26,neutral:13}),internalCoherence:TAC.calibratedBucket(Number(b.internal_coherence)||0,'internal_coherence',{negativeCap:10,positiveCap:26,max:18,neutral:9}),playstyleAndSA:TAC.calibratedBucket(Number(b.playstyle_and_sa_fit)||0,'playstyle_and_sa_fit',{negativeCap:2,positiveCap:74,max:14,neutral:0}),drainEfficiency:TAC.drainEfficiency(drain.rawScore,DRAIN_LIMIT,{},TAC.DRAIN_PROFILE_LEGACY,null)};return{starters,own,context,components,score:Object.values(components).reduce((a,x)=>a+x,0)};}
function optimiseIdentities(formation,roles,values,drain){let ids=initialIdentities(roles,values);let cur=tacticComponents(values,formation,roles,ids,drain);for(let pass=0;pass<2;pass++){
  for(let i=0;i<roles.length;i++){
    let best={ids,cur};for(const ps of D.playstylesForRoles([roles[i]])){const next=ids.map(x=>({...x,specialAbilities:[...(x.specialAbilities||[])]}));next[i].playstyle=ps;const sc=tacticComponents(values,formation,roles,next,drain);if(sc.score>best.cur.score+1e-12)best={ids:next,cur:sc};}ids=best.ids;cur=best.cur;
    best={ids,cur};const saOptions=[null,...D.specialAbilitiesForRoles([roles[i]]).filter(sa=>CFG.tactics?.special_ability_affinities?.[sa]?.active)];for(const sa of saOptions){const next=ids.map(x=>({...x,specialAbilities:[...(x.specialAbilities||[])]}));next[i].specialAbilities=sa?[sa]:[];next[i].preferredTacticalSA=sa;const sc=tacticComponents(values,formation,roles,next,drain);if(sc.score>best.cur.score+1e-12)best={ids:next,cur:sc};}ids=best.ids;cur=best.cur;
  }
 }
 return{ids,...cur};}
function addSetPieceCoverage(roles,ids){const out=ids.map(x=>({...x,specialAbilities:[...(x.specialAbilities||[])]})),assignments=[];for(const target of SET_PIECES){if(out.some(x=>(x.specialAbilities||[]).includes(target.ability))){const idx=out.findIndex(x=>x.specialAbilities.includes(target.ability));assignments.push({duty:target.duty,ability:target.ability,slot:idx});continue;}let chosen=-1,bestRank=1e9;for(let i=0;i<roles.length;i++){if(out[i].specialAbilities.length>=2||!D.isSpecialAbilityEligibleForRoles(target.ability,[roles[i]]))continue;const rank=target.rolePreference.indexOf(roles[i]);const r=rank<0?999:rank;if(r<bestRank){bestRank=r;chosen=i;}}if(chosen>=0){out[chosen].specialAbilities.push(target.ability);assignments.push({duty:target.duty,ability:target.ability,slot:chosen});}}
 return{ids:out,assignments,coverage:assignments.length,tierSum:assignments.length*2};}
function mentorComparison(starters,roles,ids,values,drainClass){const own=neutralOwn(roles,ids,values),ctx={own,values,playstyles:own.playstyles,abilities:own.abilities,margin:own.margin},rows=[];for(const [stableOrder,raw] of B.MENTORS.entries()){const c=CFG.mentors?.mentors?.[raw.id]||{},t=c.tactical||{},s=c.signature||{};let tactical=0,tActive=false;if(t.scoring!=='unavailable_in_prematch_own_squad_mode'){if(t.when){tActive=STRAT.conditionMatches(t.when,ctx);tactical=tActive?(Number(t.max_points)||40):0;}else if(t.feature){const v=own[t.feature];tactical=v===true||v==='high'?40:v==='medium'?20:0;tActive=tactical>0;}}
 const attr=M.attributeCoverage({...raw,unlocked:true,level:10},starters,{values});let sig=0,sActive=false;if(s.scoring!=='unavailable_in_prematch_own_squad_mode'){if(s.when){sActive=STRAT.conditionMatches(s.when,ctx);sig=sActive?(Number(s.max_points)||30):0;}else if(s.feature){const v=own[s.feature];sActive=v===true||v==='high';sig=sActive?(Number(s.max_points)||30):0;}}
 let trade=0;for(const tr of c.tradeoffs||[]){const applies=tr.when==='tacticalActive'?tActive:tr.when==='signatureActive'?sActive:false;if(!applies)continue;let p=Number(tr.severity_by_drain_limit?.[drainClass]);if(!Number.isFinite(p))p=Number(tr.penalty_max)||0;trade-=Math.abs(p);}const rawScore=Math.max(0,tactical+attr.score+sig+trade),planAdjustment=10*Math.max(0,Math.min(1,rawScore/95));rows.push({id:raw.id,name:raw.displayName,title:raw.title,stableOrder,tacticalPoints:tactical,attributeScore:attr.score,signaturePoints:sig,tradeoffPoints:trade,rawScore,planAdjustment});}
 rows.sort((a,b)=>b.planAdjustment-a.planAdjustment||b.rawScore-a.rawScore||a.stableOrder-b.stableOrder);return{best:rows[0],alternatives:rows.slice(1,3)};}
function quickPotential(roles,values){let n=0;for(const role of roles){const p=Math.max(0,...D.playstylesForRoles([role]).map(name=>affinity(CFG.tactics?.playstyle_affinities?.[name],values)));const s=Math.max(0,...D.specialAbilitiesForRoles([role]).map(name=>CFG.tactics?.special_ability_affinities?.[name]?.active?affinity(CFG.tactics.special_ability_affinities[name],values):0));n+=p+s;}return n;}
function quickShapeScore(roles,values,drain){const shape=STRAT.analyseShape(roles);let s=quickPotential(roles,values)+TAC.drainEfficiency(drain.rawScore,DRAIN_LIMIT,{},TAC.DRAIN_PROFILE_LEGACY,null);if(values.focus==='left'&&!shape.hasLeftProgression)s-=10;if(values.focus==='right'&&!shape.hasRightProgression)s-=10;if(values.focus==='both'&&!(shape.hasLeftProgression&&shape.hasRightProgression))s-=8;if(values.focus==='center'&&!shape.hasAMC&&shape.centralSupport<2)s-=6;if(values.cross==='high'&&!(shape.hasLeftProgression||shape.hasRightProgression))s-=6;if(values.passing==='short'&&shape.centralSupport>=3)s+=3;if(values.passing==='long'&&values.won==='counter')s+=3;if(values.passing==='short'&&values.won==='buildup')s+=3;if(values.lost==='regroup'&&values.pressing==='low')s+=3;if(values.lost==='counterPress'&&values.pressing==='high')s+=3;if(values.backLine==='offside'&&values.pressing==='high')s+=2;if(values.backLine==='track'&&(values.pressing==='low'||values.lost==='regroup'))s+=2;return s;}
let GLOBAL_TACTIC_POOL=null;
function globalTacticPool(){if(GLOBAL_TACTIC_POOL)return GLOBAL_TACTIC_POOL;const rows=[];const allPS=Object.keys(CFG.tactics?.playstyle_affinities||{}),allSA=Object.entries(CFG.tactics?.special_ability_affinities||{}).filter(([,r])=>r?.active).map(([n])=>n);for(const a of APPROACHES){TAC.enumerate(values=>{const drain=TAC.calculateDrain(values);if(DRAIN_RANK[drain.drainClass]>DRAIN_RANK[DRAIN_LIMIT])return;let semantic=0;if(values.passing==='long'&&values.won==='counter')semantic+=3;if(values.passing==='short'&&values.won==='buildup')semantic+=3;if(values.lost==='regroup'&&values.pressing==='low')semantic+=3;if(values.lost==='counterPress'&&values.pressing==='high')semantic+=3;if(values.backLine==='offside'&&values.pressing==='high')semantic+=2;if(values.backLine==='track'&&(values.pressing==='low'||values.lost==='regroup'))semantic+=2;if(['left','right','both'].includes(values.focus)&&['medium','high'].includes(values.cross))semantic+=2;if(values.mentality==='normal')semantic+=1;const psBest=allPS.reduce((m,n)=>Math.max(m,affinity(CFG.tactics.playstyle_affinities[n],values)),0),saBest=allSA.reduce((m,n)=>Math.max(m,affinity(CFG.tactics.special_ability_affinities[n],values)),0);const global=semantic+psBest+saBest+TAC.drainEfficiency(drain.rawScore,DRAIN_LIMIT,{},TAC.DRAIN_PROFILE_LEGACY,null);rows.push({values:{...values},approach:a.label,approachKey:Object.keys(B.APPROACHES).find(k=>B.APPROACHES[k]===a)||'',drain,global});},a.mentality);}rows.sort((a,b)=>b.global-a.global||a.drain.rawScore-b.drain.rawScore||JSON.stringify(a.values).localeCompare(JSON.stringify(b.values)));GLOBAL_TACTIC_POOL=rows.slice(0,1800);return GLOBAL_TACTIC_POOL;}
function shortlistTactics(roles){const rows=globalTacticPool().map(r=>({...r,quick:quickShapeScore(roles,r.values,r.drain)}));rows.sort((a,b)=>b.quick-a.quick||b.global-a.global||a.drain.rawScore-b.drain.rawScore||JSON.stringify(a.values).localeCompare(JSON.stringify(b.values)));return rows.slice(0,45);}
function evaluatePackage(formation,roles,tRow){const identities=optimiseIdentities(formation,roles,tRow.values,tRow.drain),sp=addSetPieceCoverage(roles,identities.ids),finalTac=tacticComponents(tRow.values,formation,roles,sp.ids,tRow.drain),starters=makeStarters(formation,roles,sp.ids),form=formationStructure(roles),mentor=mentorComparison(starters,roles,sp.ids,tRow.values,tRow.drain.drainClass),total=form.score+finalTac.score+(mentor.best?.planAdjustment||0);return{formation,roles,ids:sp.ids,starters,form,tactics:{...tRow,...finalTac},mentor,setPieces:sp,total};}
function compare(a,b){if(Math.abs(b.total-a.total)>1e-12)return b.total-a.total;if(Math.abs(b.form.score-a.form.score)>1e-12)return b.form.score-a.form.score;if(Math.abs(b.tactics.score-a.tactics.score)>1e-12)return b.tactics.score-a.tactics.score;if(b.setPieces.coverage!==a.setPieces.coverage)return b.setPieces.coverage-a.setPieces.coverage;if(a.tactics.drain.rawScore!==b.tactics.drain.rawScore)return a.tactics.drain.rawScore-b.tactics.drain.rawScore;return a.formation.templateOrder-b.formation.templateOrder;}
function serialise(row){return{model:MODEL,generatedAt:new Date().toISOString(),sourceModels:{gameData:D.GAME_DATA_VERSION,strategy:STRAT.MODEL_VERSION,formation:F.MODEL_VERSION,tactics:TAC.MODEL_VERSION,mentor:M.MODEL_VERSION,setPieces:R.SET_PIECE_MODEL,saEligibility:'v0.5.17-user-current-role-contract'},objective:{label:'Long-term Best-in-Slot goal',playerStats:'Not used. Best-in-Slot compares role coverage, formation shape, role-eligible Playstyles/SAs, Tactics, Set Pieces and Mentor synergy only.',coveragePolicy:'Every Best-in-Slot slot is an ideal natural-role player. Related/wrong-role assignments are not part of the goal XI.',approach:'Auto — Best Fit across all five mentalities',drainLimit:DRAIN_LIMIT,mentorAssumption:'All mentors compared as hypothetically unlocked at Level 10.',saPolicy:'Choose only role-eligible SAs. Open-play preference requires current tactic compatibility; dedicated corner/free-kick/penalty specialists may fill a second SA slot.',squadBalancePolicy:'Official Top Eleven Squad Balance is server-owned and is not fabricated offline. Formation structure/role coverage is companion logic.',opponentPolicy:'No opponent information is used.'},formation:{id:row.formation.id,name:row.formation.name,roles:[...row.roles],structure:{raw:row.form.raw,score:row.form.score,reasons:row.form.reasons}},score:{formationStructure:row.form.score,tacticCompatibility:row.tactics.score,mentorAdjustment:row.mentor.best?.planAdjustment||0,totalScore:row.total,setPieceCoverage:row.setPieces.coverage},tactics:{approach:row.tactics.approach,approachKey:row.tactics.approachKey,values:row.tactics.values,compatibilityScore:row.tactics.score,components:row.tactics.components,drainClass:row.tactics.drain.drainClass,rawScore:row.tactics.drain.rawScore},mentor:row.mentor.best?{id:row.mentor.best.id,name:row.mentor.best.name,title:row.mentor.best.title,planAdjustment:row.mentor.best.planAdjustment,rawScore:row.mentor.best.rawScore}:null,setPieces:{coverage:row.setPieces.coverage,tierSum:row.setPieces.tierSum,assignments:row.setPieces.assignments.map(x=>({...x,role:row.roles[x.slot]}))},slots:row.starters.map((s,i)=>{const id=row.ids[i],allEligible=D.specialAbilitiesForRoles([s.assignedRole]);return{slot:i+1,role:s.assignedRole,x:s.x,y:s.y,playstyle:id.playstyle,playstyleLevelTarget:'Master',specialAbilities:[...(id.specialAbilities||[])],preferredTacticalSA:id.preferredTacticalSA||null,saPreferenceStatus:id.preferredTacticalSA?'tactic-compatible':'no-proven-open-play-preference',eligibleSpecialAbilities:allEligible};})};}
function generate(){const rows=[];for(const formation of F.FORMATIONS){for(const roles of roleVariants(formation)){for(const t of shortlistTactics(roles))rows.push(evaluatePackage(formation,roles,t));}}rows.sort(compare);const best=serialise(rows[0]);best.alternatives=rows.slice(1,4).map(r=>({formation:{id:r.formation.id,name:r.formation.name,roles:r.roles},score:{totalScore:r.total,formationStructure:r.form.score,tacticCompatibility:r.tactics.score,mentorAdjustment:r.mentor.best?.planAdjustment||0},tactics:{approach:r.tactics.approach,values:r.tactics.values,drainClass:r.tactics.drain.drainClass},mentor:r.mentor.best?.name||null}));return best;}
const result=generate(),jsonPath=path.join(ROOT,'data/build_30527/index/best_in_slot_v1.json'),jsPath=path.join(ROOT,'js/best-in-slot-data.js');fs.writeFileSync(jsonPath,JSON.stringify(result,null,2)+'\n');fs.writeFileSync(jsPath,`(()=>{const TE=window.TE5=window.TE5||{};TE.BestInSlotData=${JSON.stringify(result)};})();\n`);console.log(JSON.stringify({formation:result.formation,tactics:result.tactics,mentor:result.mentor,score:result.score,slots:result.slots.map(s=>({role:s.role,playstyle:s.playstyle,specialAbilities:s.specialAbilities}))},null,2));
